/** Data Explorer acceptance journeys against the actual numerical API. */
import { mkdir, writeFile, readFile } from 'node:fs/promises'
import { chromium } from '../../apps/web/node_modules/@playwright/test/index.mjs'
const base=process.env.FARMTACT_BASE_URL||'http://127.0.0.1:8080'
const dir=process.env.FARMTACT_EXPLORER_SCREENSHOTS||'apps/web/screenshots/explorer'
const output=process.env.FARMTACT_EXPLORER_REPORT||'reports/explorer_browser.json'
const report={status:'RUNNING',base_url:base,checks:[],failures:[],screenshots:[],page_errors:[],inference_requests:[],branches:[]}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms))
function check(name,value,detail){report.checks.push({name,pass:Boolean(value),...(detail===undefined?{}:{detail})});if(!value)throw new Error(name+(detail?': '+JSON.stringify(detail):''))}
async function json(response){if(!response.ok())throw new Error(`API ${response.status()}: ${await response.text()}`);return response.json()}
async function click(page,name){await page.getByRole('button',{name,exact:true}).filter({visible:true}).first().click()}
async function done(request,id){const until=Date.now()+180000;while(Date.now()<until){const s=await json(await request.get(`${base}/api/v1/scenarios/${id}`));if(['COMPLETED','FAILED'].includes(s.status))return s;await pause(1000)}throw new Error('Numerical branch timeout')}
async function screenshot(page,name){const path=`${dir}/${name}.png`;await page.screenshot({path,fullPage:true,animations:'disabled'});report.screenshots.push(path)}
async function fit(page,width){check(`${width}px has no document overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));check(`${width}px no page errors`,report.page_errors.length===0,report.page_errors)}
await mkdir(dir,{recursive:true})
let browser,page
try{
  browser=await chromium.launch({headless:true})
  const context=await browser.newContext({viewport:{width:360,height:844},reducedMotion:'reduce',acceptDownloads:true})
  if(process.env.FARMTACT_BROWSER_SESSION_STATE){
    const state=JSON.parse(await readFile(process.env.FARMTACT_BROWSER_SESSION_STATE,'utf8'))
    await context.addCookies([{name:'farmtact_session',value:state.cookie,url:base,httpOnly:true,sameSite:'Strict'}])
  }
  const journeyName=`Explorer acceptance ${Date.now().toString(36)}`
  page=await context.newPage()
  page.on('pageerror',e=>report.page_errors.push(e.message))
  page.on('request',r=>{if(r.method()==='POST'&&/\/conversations\/[^/]+\/(messages|invite|council)/.test(r.url()))report.inference_requests.push(r.url())})
  await page.goto(base,{waitUntil:'networkidle'})
  const original=await json(await context.request.get(`${base}/api/v1/bootstrap`))
  await click(page,'Data')
  await page.locator('.explorer-page').waitFor()
  await page.getByRole('combobox',{name:'Dataset snapshot',exact:true}).waitFor()
  await page.locator('.explorer-chart').first().waitFor()
  check('Explorer starts from the original reference',await page.getByRole('combobox',{name:'Dataset snapshot',exact:true}).inputValue()==='reference')
  await page.locator('.explorer-chart').first().waitFor()
  await fit(page,360)
  await screenshot(page,'overview-360')
  const ref=await json(await context.request.get(`${base}/api/v1/data-explorer/snapshots/reference`))
  await page.getByRole('combobox',{name:'Crop filter',exact:true}).selectOption('caixin')
  check('Crop filter changes plotted records',await page.locator('.explorer-chart').first().locator('[role="button"]').count()===20)
  await page.getByLabel('Start date',{exact:true}).fill('2026-08-01')
  check('Date filter changes plotted records',await page.locator('.explorer-chart').first().locator('[role="button"]').count()===13)
  const firstPoint=page.locator('.explorer-chart').first().locator('[role="button"]').first()
  await firstPoint.focus();await page.keyboard.press('Enter')
  await page.locator('.record-inspector').last().waitFor()
  check('Keyboard point selection opens actual records',(await page.locator('.record-inspector').last().innerText()).includes('history:caixin:'))
  check('Charts and records retain shared crop filter',await page.getByRole('combobox',{name:'Crop filter',exact:true}).inputValue()==='caixin')
  await click(page,'Overview')
  const shortageDate='2026-09-21'
  check('Identify a delivery date with demand and no scheduled harvest',ref.records.forecast.some(r=>r.date===shortageDate&&r.expected_kg>0)&&!ref.records.batches.some(r=>r.date===shortageDate))
  const compact=new Intl.DateTimeFormat('en-SG',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(shortageDate))
  const exposedPoint=page.getByRole('button',{name:new RegExp(`Caixin.*Expected Kg.*${compact}`)}).first()
  await exposedPoint.focus();await page.keyboard.press('Enter')
  check('Inspect the order records contributing to that forecast',(await page.locator('.record-inspector').last().innerText()).includes('order-0-1'))
  await page.getByRole('combobox',{name:'Record set',exact:true}).selectOption('history')
  await page.getByLabel('Start date',{exact:true}).fill(ref.date_extent.start)
  await page.getByLabel('End date',{exact:true}).fill(ref.date_extent.end)
  await page.getByRole('combobox',{name:'Crop filter',exact:true}).selectOption('')
  await page.getByPlaceholder('ID, crop or value').fill('pak_choi')
  check('Search filters the actual table',await page.locator('.records-table tbody tr').count()===12)
  const exportLink=page.getByRole('link',{name:'JSON',exact:true})
  const exported=await json(await context.request.get(new URL(await exportLink.getAttribute('href'),base).href))
  check('Filtered JSON export matches table',exported.records.length===12&&exported.records.every(r=>r.crop_id==='pak_choi'))
  const csvDownload=page.waitForEvent('download')
  await page.getByRole('link',{name:'CSV',exact:true}).click()
  const csv=await csvDownload;await csv.saveAs('/tmp/farmtact-explorer-filtered.csv')
  check('CSV downloads the filtered record set',(await readFile('/tmp/farmtact-explorer-filtered.csv','utf8')).trim().split('\n').length===13)
  await page.getByPlaceholder('ID, crop or value').fill('absent-record-999')
  check('Empty filter is explicit',await page.getByText('No records match the current filters.',{exact:true}).isVisible())
  await page.getByPlaceholder('ID, crop or value').fill('')
  check('Records paginate at 25 rows',await page.locator('.records-table tbody tr').count()===25)
  await click(page,'Next')
  check('Pagination shows remaining 23 records',await page.locator('.records-table tbody tr').count()===23)
  await click(page,'Generator')
  const generatorControls=page.locator('.generator-controls .dual-control')
  check('All six generator and smoothing controls are present',await generatorControls.count()===6)
  for(let i=0;i<6;i++){
    const control=generatorControls.nth(i),slider=control.getByRole('slider'),input=control.getByRole('spinbutton')
    await slider.focus();await page.keyboard.press('Home')
    check(`Control ${i+1} keyboard minimum matches numeric input`,Number(await input.inputValue())===Number(await slider.getAttribute('min')))
    await page.keyboard.press('End')
    check(`Control ${i+1} keyboard maximum matches numeric input`,Number(await input.inputValue())===Number(await slider.getAttribute('max')))
  }
  for(let i=0;i<6;i++){
    const control=generatorControls.nth(i)
    await control.getByRole('button',{name:/^Reset /}).click()
    check(`Control ${i+1} individual reset restores its default`,Number(await control.getByRole('spinbutton').inputValue())===[100,0,100,100,100,.35][i])
  }
  await click(page,'Reset all')
  check('Reset restores all declared defaults',JSON.stringify(await generatorControls.getByRole('spinbutton').evaluateAll(nodes=>nodes.map(n=>Number(n.value))))===JSON.stringify([100,0,100,100,100,.35]))
  const historyControl=page.getByRole('spinbutton',{name:'Historical demand multiplier numeric value',exact:true})
  const alphaControl=page.getByRole('spinbutton',{name:'Forecast smoothing alpha numeric value',exact:true})
  await historyControl.fill('151');await pause(900)
  check('Out-of-range assumptions cannot be saved',await page.getByRole('button',{name:'Save dataset and run strategies',exact:true}).isDisabled())
  await historyControl.fill('130');await alphaControl.fill('0.8')
  await page.getByLabel('Saved dataset name',{exact:true}).fill(journeyName)
  await page.getByRole('button',{name:'Save dataset and run strategies',exact:true}).waitFor({state:'visible'})
  await page.waitForFunction(()=>!document.querySelector('[aria-label="Save dataset and run strategies"]')?.disabled)
  const preview=await json(await context.request.post(`${base}/api/v1/data-explorer/preview`,{data:{generator_settings:{history_multiplier:1.3},forecast_settings:{alpha:.8}}}))
  check('Playground alpha and multiplier preview numerically',preview.forecast_settings.alpha===.8&&Number(preview.records.history[0].ordered_kg)===35.1)
  await screenshot(page,'generator-360')
  const createdResponse=page.waitForResponse(r=>r.url().endsWith('/api/v1/scenarios')&&r.request().method()==='POST')
  await click(page,'Save dataset and run strategies')
  const created=await (await createdResponse).json()
  const branch=await done(context.request,created.id)
  check('Save and run freezes the selected settings',branch.status==='COMPLETED'&&branch.forecast_settings.alpha===.8&&branch.generator_settings.history_multiplier===1.3)
  check('Planner consumes the preview forecast',JSON.stringify(branch.result.forecast)===JSON.stringify(preview.forecast))
  check('Playground baseline is original at alpha 0.35',branch.baseline.forecast.forecast_settings.alpha===.35)
  report.branches.push({id:branch.id,status:branch.status,alpha:branch.forecast_settings.alpha})
  await page.waitForFunction(id=>document.querySelector('[aria-label="Dataset snapshot"]')?.value===`scenario:${id}`,branch.id)
  check('Save and run automatically opens the frozen result',await page.getByRole('combobox',{name:'Dataset snapshot',exact:true}).inputValue()===`scenario:${branch.id}`)
  // Select the completed branch explicitly; it must be reloadable without recalculation.
  await click(page,'Overview')
  await page.reload({waitUntil:'networkidle'});await click(page,'Data')
  await page.getByRole('combobox',{name:'Dataset snapshot',exact:true}).selectOption(`scenario:${branch.id}`)
  await click(page,'Experiments')
  await page.getByRole('button',{name:'Ask advisor',exact:true}).waitFor({state:'visible',timeout:10000})
  const convoResponse=page.waitForResponse(r=>r.url().endsWith('/api/v1/conversations')&&r.request().method()==='POST')
  await click(page,'Ask advisor')
  const convo=await (await convoResponse).json()
  const conversation=await json(await context.request.get(`${base}/api/v1/conversations/${convo.id}`))
  check('Explicit advisor opens the correct frozen result',conversation.snapshot_ref.kind==='scenario'&&conversation.snapshot_ref.id===branch.id&&conversation.snapshot_ref.hash===branch.input_hash)
  await page.getByRole('dialog').getByRole('button',{name:/Close/}).first().click()
  await page.getByRole('spinbutton',{name:'Harvest delay numeric value',exact:true}).fill('14')
  await page.getByRole('spinbutton',{name:'Labour numeric value',exact:true}).fill('50')
  await page.getByRole('spinbutton',{name:'Cash numeric value',exact:true}).fill('50')
  const childResponse=page.waitForResponse(r=>r.url().endsWith('/api/v1/scenarios')&&r.request().method()==='POST')
  await click(page,'Run frozen scenario')
  const childCreated=await (await childResponse).json()
  const child=await done(context.request,childCreated.id)
  check('Experiment continues the selected frozen dataset',child.parent_scenario_id===branch.id&&child.forecast_settings.alpha===.8)
  check('Infeasible policies retain inspectable results',child.status==='COMPLETED'&&child.result.strategies.some(s=>s.violations.length>0))
  report.branches.push({id:child.id,status:child.status,simulation_status:child.simulation_status})
  await page.getByRole('combobox',{name:'Dataset snapshot',exact:true}).selectOption(`scenario:${child.id}`)
  await page.getByRole('button',{name:'Compare selected',exact:true}).waitFor({state:'visible'})
  const checkboxes=page.locator('.branch-picker label').filter({hasText:journeyName}).locator('input[type="checkbox"]')
  for(let i=0;i<await checkboxes.count();i++)await checkboxes.nth(i).check()
  await click(page,'Compare selected')
  await page.getByRole('heading',{name:'What changed against the baseline',exact:true}).waitFor()
  await page.locator('.explorer-comparison-table thead th').nth(3).waitFor()
  check('Comparison shows the original baseline and two branches',await page.locator('.explorer-comparison-table thead th').count()===4)
  for(const policy of ['Lean','Balanced','Resilient']){
    await click(page,policy)
    check(`${policy} comparison uses the same policy`,(await page.locator('.explorer-comparison-table caption').innerText()).includes(policy))
    check(`${policy} includes delivery, waste, labour, cash, margin and constraints`,await page.locator('.explorer-comparison-table tbody tr').count()===6)
  }
  await page.getByRole('button',{name:/^Trace .* to numerical evidence$/}).first().click()
  check('Computed tradeoff opens frozen numerical evidence',await page.locator('[id^="explorer-evidence-"][open]').count()===1)
  await screenshot(page,'comparison-360')
  await click(page,'Overview')
  for(const [index,width] of [390,430,1280].entries()){
    await page.setViewportSize({width,height:width===1280?900:844})
    await click(page,'Overview')
    await fit(page,width)
    await screenshot(page,`overview-${width}`)
    await click(page,'Generator')
    const price=page.getByRole('spinbutton',{name:/Selling.price multiplier numeric value|Order price numeric value/})
    await price.fill(String(105+index*5))
    await page.getByLabel('Saved dataset name',{exact:true}).fill(`${journeyName} ${width}px`)
    await page.waitForFunction(()=>!document.querySelector('[aria-label="Save dataset and run strategies"]')?.disabled)
    await screenshot(page,`generator-${width}`)
    const response=page.waitForResponse(r=>r.url().endsWith('/api/v1/scenarios')&&r.request().method()==='POST')
    await click(page,'Save dataset and run strategies')
    const nextCreated=await (await response).json(),next=await done(context.request,nextCreated.id)
    check(`${width}px completes changed-assumption strategy run`,next.status==='COMPLETED'&&next.generator_settings.price_multiplier===(105+index*5)/100)
    report.branches.push({id:next.id,status:next.status,width})
    await page.getByRole('combobox',{name:'Dataset snapshot',exact:true}).selectOption(`scenario:${next.id}`)
    await click(page,'Experiments')
    await page.getByRole('button',{name:'Compare selected',exact:true}).waitFor({state:'visible'})
    await click(page,'Compare selected')
    await page.getByRole('heading',{name:'What changed against the baseline',exact:true}).waitFor()
    check(`${width}px compares consequences with baseline`,await page.locator('.explorer-comparison-table tbody tr').count()===6)
    await fit(page,width)
    await screenshot(page,`comparison-${width}`)
  }
  check('No inference while browsing',report.inference_requests.length===0)
  const after=await json(await context.request.get(`${base}/api/v1/bootstrap`))
  check('Browsing preserves main farm and recorded run',JSON.stringify(after.farm)===JSON.stringify(original.farm)&&JSON.stringify(after.latest_run)===JSON.stringify(original.latest_run))
  report.status='PASS'
}catch(error){report.status='FAIL';report.failures.push(String(error));if(page){await screenshot(page,'failure').catch(()=>{});report.overflow=await page.evaluate(()=>[...document.querySelectorAll('main *')].map(n=>({tag:n.tagName,class:n.className?.baseVal||n.className,left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right})).filter(n=>n.right>innerWidth+2||n.left< -2).slice(0,25)).catch(()=>[])}process.exitCode=1}
finally{if(browser)await browser.close();await writeFile(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,checks:report.checks.length,failures:report.failures,report:output}))}
