import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "../../apps/web/node_modules/@playwright/test/index.mjs";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"../.."),baseURL=process.env.BASE_URL||"http://127.0.0.1:4194",reportPath=resolve(root,"reports/v15/records-extended-browser.json");
const report={started_at:new Date().toISOString(),base_url:baseURL,checks:[],failures:[],prerequisites:[],controlled_fixtures:[]};
function check(name,pass,detail=""){report.checks.push({name,pass:Boolean(pass),detail});if(!pass)throw new Error(`${name}: ${detail}`)}
let browser;
try{
 browser=await chromium.launch({headless:true});const statePath="/tmp/farmtact-v15-records-extended-storage.json",context=await browser.newContext({viewport:{width:390,height:844},...(existsSync(statePath)?{storageState:statePath}:{})}),page=await context.newPage();
 const api=(path,init)=>page.evaluate(async({path,init})=>{const r=await fetch(`/api/v1${path}`,{...init,headers:{"Content-Type":"application/json",...(init?.method==="POST"?{"Idempotency-Key":crypto.randomUUID()}:{}),...(init?.headers||{})}}),t=await r.text();if(!r.ok)throw new Error(`${path}: ${r.status} ${t}`);return t?JSON.parse(t):null},{path,init});
 await page.goto(baseURL,{waitUntil:"networkidle"});await context.storageState({path:statePath});
 const openTools=async()=>{const more=page.getByRole("button",{name:"More",exact:true}).filter({visible:true}).first();if(await more.isVisible().catch(()=>false))await more.click()};
 const openTool=async title=>{for(let i=0;i<4&&!(await page.locator(".ic-path").isVisible().catch(()=>false));i++){const back=page.getByRole("button",{name:"Back",exact:true}).filter({visible:true}).first();if(await back.isVisible().catch(()=>false))await back.click();else break}if(!(await page.locator(".ic-path").isVisible().catch(()=>false)))await openTools();const order=["Plan","Records & work","Knowledge & evidence","Experiments","History & preferences"];for(let i=0;i<7&&!(await page.getByText(title,{exact:true}).isVisible().catch(()=>false));i++){const path=await page.locator(".ic-path").textContent(),current=order.findIndex(x=>path?.endsWith(x)),target=order.indexOf(title),name=current>target?/Previous/:/Next/;await page.getByRole("button",{name}).filter({visible:true}).first().click()}await page.getByRole("button",{name:"Open tool",exact:true}).click()};
 const choose=async name=>{for(let i=0;i<12&&!(await page.getByRole("heading",{name,exact:true}).isVisible().catch(()=>false));i++)await page.getByRole("button",{name:/Next/}).filter({visible:true}).first().click();await page.getByRole("button",{name:"Open",exact:true}).click()};
 await openTool("Records & work");await choose("Farm records");

 // Real local CSV parsing, source inspection and explicit confirmation.
 const add=page.getByRole("button",{name:"Add candidate",exact:true});if(await add.isVisible())await add.click();
 const csvStamp=Date.now(),csvName=`v15-accounting-${csvStamp}.csv`,csvReference=`EXT-CSV-${csvStamp}`;await page.getByLabel("Candidate file").setInputFiles({name:csvName,mimeType:"text/csv",buffer:Buffer.from(`date,kind,reference,description,amount,currency\n2026-09-17,expense,${csvReference},Nutrients,18.50,SGD\n`)});
 await page.getByRole("button",{name:"Upload accounting candidate",exact:true}).click();await page.getByLabel("Candidate file").waitFor({state:"detached"});
 const workflowAfterCsv=await api("/farm-workflow"),csv=workflowAfterCsv.inbox.find(x=>x.source_name===csvName);check("CSV upload creates real candidate",csv?.source_kind==="accounting_export"&&csv.status==="candidate",JSON.stringify(csv));
 for(let i=0;i<30&&!(await page.getByRole("heading",{name:csv.source_name,exact:true}).isVisible().catch(()=>false));i++){const next=page.getByRole("button",{name:/Next/}).filter({visible:true}).first();if(await next.isDisabled())break;await next.click()}
 await page.getByRole("button",{name:"Source",exact:true}).click();await page.getByRole("button",{name:"Inspect source",exact:true}).click();await page.locator(".ir-source-text").getByText(new RegExp(csvReference)).waitFor();const sourceText=await page.evaluate(async id=>await (await fetch(`/api/v1/farm-workflow/imports/${id}/source`)).text(),csv.candidate_id);check("candidate source opens inline through authenticated endpoint",String(sourceText).includes(csvReference)&&await page.locator(".ir-source-text").innerText().then(text=>text.includes(csvReference)));
 await page.getByRole("button",{name:"Back",exact:true}).click();await page.getByRole("button",{name:"Review candidate",exact:true}).click();const confirmCandidate=page.getByRole("button",{name:"Confirm reviewed fields",exact:true});await confirmCandidate.click();await confirmCandidate.waitFor({state:"detached"});check("accounting candidate explicitly confirmed",(await api("/farm-workflow")).inbox.find(x=>x.candidate_id===csv.candidate_id)?.status==="confirmed");

 // Controlled AI outage: no provider call is forwarded.
 await page.getByRole("button",{name:"Add candidate",exact:true}).click();await page.getByLabel("Candidate file").setInputFiles({name:"controlled-five-page.pdf",mimeType:"application/pdf",buffer:Buffer.from("%PDF-1.4 controlled fixture")});
 check("document card discloses one explicit provider request",await page.getByText(/one bounded provider extraction request/).isVisible());
 let intercepted=0;await page.route("**/api/v1/farm-workflow/imports/upload**",route=>{intercepted++;return route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({detail:"Controlled AI extraction outage; provider not called"})})});
 await page.getByRole("button",{name:"Submit for AI extraction",exact:true}).click();await page.getByRole("alert").getByText(/Controlled AI extraction outage/).waitFor();check("AI outage retains selected document",await page.getByLabel("Candidate file").evaluate(input=>input.files?.[0]?.name)==="controlled-five-page.pdf");check("controlled outage made no provider request",intercepted===1,String(intercepted));report.controlled_fixtures.push("PDF upload endpoint returned labelled 503 before any backend/provider call.");await page.unroute("**/api/v1/farm-workflow/imports/upload**");
 const fixtureCandidate={candidate_id:`controlled-photo-${Date.now()}`,source_name:"controlled-five-page.pdf",source_kind:"document_extraction",status:"candidate",authority:"observation_only",planning_eligible:false,warnings:["Controlled fixture: extraction fields are unverified."],rows:[{observation:"Controlled retained field",crop_id:"caixin",quantity_text:"18 kg"}]};
 await page.route("**/api/v1/farm-workflow/imports/upload**",route=>route.fulfill({status:201,contentType:"application/json",body:JSON.stringify(fixtureCandidate)}));await page.route("**/api/v1/farm-workflow",async route=>{if(route.request().method()!=="GET")return route.continue();const response=await route.fetch(),body=await response.json();body.inbox.push(fixtureCandidate);return route.fulfill({response,json:body})});
 await page.getByRole("button",{name:"Submit for AI extraction",exact:true}).click();for(let i=0;i<50&&!(await page.getByRole("heading",{name:fixtureCandidate.source_name,exact:true}).isVisible().catch(()=>false));i++){const next=page.getByRole("button",{name:/Next/}).filter({visible:true}).first();if(await next.isDisabled())break;await next.click()}await page.getByText("Inspect extracted fields").click();check("controlled extraction retains labelled fields",await page.getByText("Controlled retained field",{exact:true}).isVisible()&&await page.getByText("18 kg",{exact:true}).isVisible());check("controlled extraction remains non-authoritative candidate",await page.getByText(/Inactive until reviewed/).isVisible());report.controlled_fixtures.push("Labelled document candidate response supplied retained fields without invoking a provider; no business mutation claim.");await page.unroute("**/api/v1/farm-workflow/imports/upload**");await page.unroute("**/api/v1/farm-workflow");await page.getByRole("button",{name:"Back",exact:true}).click();

 // Prepare a real applied proposal; approval itself remains a UI action.
 let sessions=await api("/planning-sessions"),rememberedId=await page.evaluate(ids=>Object.values(localStorage).find(value=>ids.includes(value)),sessions.sessions.map(x=>x.id)),summary=sessions.sessions.find(x=>x.id===rememberedId)||sessions.sessions.find(x=>x.workflow),session=await api(`/planning-sessions/${summary.id}`);
 const waitSession=async()=>{for(let i=0;i<100;i++){session=await api(`/planning-sessions/${session.id}`);if(!["QUEUED","RUNNING"].includes(session.job?.status||""))return;await page.waitForTimeout(300)}throw new Error("planning job timeout")};
 if(!session.result?.strategies?.length){await api(`/planning-sessions/${session.id}/calculate`,{method:"POST",body:JSON.stringify({revision:session.revision})});await waitSession()}
 const strategy=session.result.strategies.find(x=>String(x.status).toUpperCase()==="FEASIBLE")||session.result.strategies[0],start=session.farm.planning_date||session.farm.cutoff.slice(0,10),crop=strategy.allocations[0]?.crop_id||session.farm.orders[0].crop_id;
 const assumptions={tentative_orders:[],future_demand:[{crop_id:crop,start_date:start,end_date:start,percent:100}],seasonal:[],order_changes:[],reservations:[],capacity:{nursery_sites:session.farm.resources.nursery_sites,labour_hours_per_week:session.farm.resources.labour_hours_per_week,cash_sgd:session.farm.resources.cash_sgd}};
 let proposal=await api("/farm-workflow/proposals",{method:"POST",body:JSON.stringify({session_id:session.id,base_revision:session.revision,changes:[{kind:"planning_assumptions",assumptions}],selected_strategy_id:strategy.id,source_candidate_ids:[],idempotency_key:crypto.randomUUID()})});await api(`/farm-workflow/proposals/${proposal.id}/apply`,{method:"POST",body:JSON.stringify({proposal_id:proposal.id,expected_base_revision:proposal.base_revision,idempotency_key:crypto.randomUUID()})});for(let i=0;i<120;i++){proposal=(await api("/farm-workflow")).proposals.find(x=>x.id===proposal.id);if(proposal?.status==="applied"&&proposal.recalculated_strategy_id)break;await page.waitForTimeout(500)}check("API prerequisite recalculation completed",proposal?.status==="applied"&&Boolean(proposal.recalculated_strategy_id),proposal?.status);report.prerequisites.push(`Created/applied proposal ${proposal.id} through real API; approval is tested in UI.`);
 await page.evaluate(()=>window.dispatchEvent(new Event("farmtact-workflow-refresh")));await page.waitForTimeout(300);await choose("Proposal approvals");for(let i=0;i<40&&!(await page.getByText(proposal.id,{exact:true}).isVisible().catch(()=>false));i++){const next=page.getByRole("button",{name:/Next/}).filter({visible:true}).first();if(await next.isDisabled())break;await next.click()}check("proposal card binds prerequisite identity",await page.getByText(proposal.id,{exact:true}).isVisible(),proposal.id);
 await page.getByRole("button",{name:"Review approval",exact:true}).click();const approvePattern=`**/api/v1/farm-workflow/proposals/${proposal.id}/approve-actions`;await page.route(approvePattern,async route=>route.fulfill({status:409,contentType:"application/json",body:JSON.stringify({detail:"Controlled stale proposal revision; refresh and review again."})}),{times:1});let approveButton=page.getByRole("button",{name:/Approve revision & create tasks/});await approveButton.click();const staleAlert=page.getByRole("alert");await staleAlert.waitFor({timeout:15000});check("stale approval is rejected and proposal review retained",(await staleAlert.textContent())?.includes("Controlled stale proposal revision")&&await approveButton.isVisible()&&(await api("/farm-workflow")).tasks.filter(x=>x.proposal_id===proposal.id).length===0,await staleAlert.textContent()||"");report.controlled_fixtures.push("One labelled HTTP 409 approval response verified stale review retention; backend eligibility is covered separately and no task was created.");await page.unroute(approvePattern);await approveButton.click();let approvedState,tasks=[];for(let i=0;i<60;i++){approvedState=await api("/farm-workflow");tasks=approvedState.tasks.filter(x=>x.proposal_id===proposal.id);if(tasks.length)break;await page.waitForTimeout(250)}check("Records UI approval creates tasks",tasks.length>0,(await page.getByRole("alert").allTextContents()).join(" | "));

 // Record a failed result through the card and verify recovery-required state.
 await page.getByRole("button",{name:"Back",exact:true}).click();await choose("Tasks & results");const target=tasks[0];for(let i=0;i<100&&!(await page.getByText(new RegExp(target.id)).isVisible().catch(()=>false));i++){const next=page.getByRole("button",{name:/Next/}).filter({visible:true}).first();if(await next.isDisabled())break;await next.click()}
 await page.getByRole("button",{name:"Record result",exact:true}).click();const resultTitle=target.action.replaceAll("_"," ");await page.locator(".ir-card").focus();await page.keyboard.press("ArrowRight");await page.locator(".integrated-records").dispatchEvent("touchstart",{touches:[{identifier:1,clientX:300,clientY:200}]});await page.locator(".integrated-records").dispatchEvent("touchend",{changedTouches:[{identifier:1,clientX:100,clientY:200}]});check("form arrow and swipe keep task binding",await page.getByRole("heading",{name:resultTitle,exact:true}).isVisible()&&await page.getByLabel("Result").isVisible(),`${target.id}: ${resultTitle}`);await page.getByLabel("Result").selectOption("failed");for(const box of await page.getByRole("checkbox").all())await box.check();await page.getByLabel("Farmer note").fill("Controlled failed result for recovery acceptance");const saveResult=page.getByRole("button",{name:"Save reported result",exact:true});await saveResult.click();await saveResult.waitFor({state:"detached",timeout:15000});
 let failed;for(let i=0;i<60;i++){failed=(await api("/farm-workflow")).tasks.find(x=>x.id===target.id);if(failed?.status==="recovery_required"&&failed.event_revision>0)break;await page.waitForTimeout(250)}check("failed task result becomes recovery-required",failed?.status==="recovery_required"&&failed.event_revision>0,JSON.stringify({status:failed?.status,revision:failed?.event_revision}));const reportedSnapshot=JSON.stringify({actual:failed.actual_quantity,note:failed.result_note,revision:failed.event_revision});await page.evaluate(()=>window.dispatchEvent(new Event("farmtact-workflow-refresh")));for(let i=0;i<100&&!(await page.getByText(target.id,{exact:true}).isVisible().catch(()=>false));i++){const next=page.getByRole("button",{name:/Next/}).filter({visible:true}).first();if(await next.isDisabled())break;await next.click()}

 // Future-only recovery handoff; return position/focus must be restored.
 const replan=page.getByRole("button",{name:"Replan future work",exact:true});await replan.scrollIntoViewIfNeeded();await replan.focus();const beforeScroll=await page.evaluate(()=>window.scrollY);await replan.click();for(let i=0;i<2;i++)await page.getByRole("button",{name:"Next",exact:true}).click();await page.getByRole("button",{name:"Open",exact:true}).click();await page.getByRole("button",{name:"Review",exact:true}).click();await page.getByRole("button",{name:"Create proposal",exact:true}).click();await page.getByRole("button",{name:"Apply & recalculate",exact:true}).click();await page.getByRole("button",{name:"Refresh result",exact:true}).waitFor({timeout:120000});await page.getByRole("button",{name:"Back",exact:true}).click();await page.getByRole("button",{name:"Previous",exact:true}).click();await page.getByRole("button",{name:"Open",exact:true}).click();await page.getByRole("button",{name:"Compare retained schedule",exact:true}).click();check("recovery exposes retained-schedule comparison",await page.getByText("Changed allocations and metrics",{exact:true}).isVisible()&&await page.getByText(/does not recalculate/).isVisible());await page.getByRole("button",{name:"Back to strategies",exact:true}).click();await page.getByRole("button",{name:"Back",exact:true}).click();await page.getByRole("button",{name:"Back",exact:true}).click();
 await page.getByRole("button",{name:"Replan future work",exact:true}).waitFor();await page.waitForFunction(({label,scroll})=>document.activeElement?.textContent?.trim()===label&&Math.abs(window.scrollY-scroll)<3,{label:"Replan future work",scroll:beforeScroll},{timeout:2000}).catch(()=>{});const afterScroll=await page.evaluate(()=>window.scrollY),focus=await page.evaluate(()=>document.activeElement?.textContent?.trim());check("recovery returns focus to originating action",focus==="Replan future work",String(focus));check("recovery restores originating scroll",Math.abs(afterScroll-beforeScroll)<3,`${beforeScroll}->${afterScroll}`);
 const retained=(await api("/farm-workflow")).tasks.find(x=>x.id===target.id);check("future-only replan preserves reported work",JSON.stringify({actual:retained.actual_quantity,note:retained.result_note,revision:retained.event_revision})===reportedSnapshot);

 // Atomic transition must not expose the old session's proposal/tasks in the new farm deck.
 await page.getByRole("button",{name:"Back",exact:true}).click();for(let i=0;i<12&&!(await page.getByRole("heading",{name:"Farm setup",exact:true}).isVisible().catch(()=>false));i++)await page.getByRole("button",{name:/Previous/}).filter({visible:true}).first().click();await page.getByRole("button",{name:"Open",exact:true}).click();await page.getByRole("button",{name:"Review demo load",exact:true}).click();await page.getByRole("button",{name:"Confirm atomic demo load",exact:true}).click();await page.getByRole("heading",{name:"Farm setup",exact:true}).waitFor();await page.getByRole("button",{name:"Back",exact:true}).click();
 await choose("Proposal approvals");check("new session proposal deck excludes old proposal",await page.getByText(proposal.id,{exact:true}).count()===0);await page.getByRole("button",{name:"Back",exact:true}).click();await choose("Tasks & results");check("new session task deck excludes old task",await page.getByText(new RegExp(target.id)).count()===0);
}catch(error){report.failures.push({name:"browser run",detail:error instanceof Error?error.stack:String(error)})}finally{report.finished_at=new Date().toISOString();report.status=report.failures.length?"FAILED":"PASSED";await mkdir(dirname(reportPath),{recursive:true});await writeFile(reportPath,JSON.stringify(report,null,2));await browser?.close()}
if(report.failures.length){console.error(JSON.stringify(report.failures,null,2));process.exitCode=1}else console.log(`V15 records extended checks passed (${report.checks.length}).`);
