import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "../../apps/web/node_modules/@playwright/test/index.mjs";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"../.."),baseURL=process.env.BASE_URL||"http://127.0.0.1:4196",reportPath=resolve(root,"reports/v15/records-gaps-browser.json"),statePath="/tmp/farmtact-v15-records-extended-storage.json";
const report={started_at:new Date().toISOString(),base_url:baseURL,checks:[],failures:[],prerequisites:[],controlled_fixtures:[]};
const check=(name,pass,detail="")=>{report.checks.push({name,pass:Boolean(pass),detail});if(!pass)throw new Error(`${name}: ${detail}`)};
let browser;
try{
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},...(existsSync(statePath)?{storageState:statePath}:{})}),page=await context.newPage();
 const api=(path,init)=>page.evaluate(async({path,init})=>{const r=await fetch(`/api/v1${path}`,{...init,headers:{"Content-Type":"application/json",...(init?.method==="POST"?{"Idempotency-Key":crypto.randomUUID()}:{}),...(init?.headers||{})}}),text=await r.text();if(!r.ok)throw new Error(`${path}: ${r.status} ${text}`);return text?JSON.parse(text):null},{path,init});
 await page.goto(baseURL,{waitUntil:"networkidle"});
 const tools=async()=>{for(let i=0;i<4&&!(await page.locator(".ic-path").isVisible().catch(()=>false));i++){const back=page.getByRole("button",{name:"Back",exact:true}).filter({visible:true}).first();if(await back.isVisible().catch(()=>false))await back.click();else break}const more=page.getByRole("button",{name:"More",exact:true}).filter({visible:true}).first();if(await more.isVisible().catch(()=>false))await more.click()};
 const openRecords=async()=>{await tools();for(let i=0;i<7&&!(await page.getByText("Records & work",{exact:true}).isVisible().catch(()=>false));i++)await page.getByRole("button",{name:/Next/}).filter({visible:true}).first().click();await page.getByRole("button",{name:"Open tool",exact:true}).click()};
 const category=async name=>{const order=["Farm setup","Farm records","Confirmed orders","Growing spaces","Inventory","Proposal approvals","Tasks & results","Verify & recover","Workflow history"];for(let i=0;i<12&&!(await page.getByRole("heading",{name,exact:true}).isVisible().catch(()=>false));i++){const current=await page.locator(".ir-card h3").textContent(),button=page.getByRole("button",{name:order.indexOf(current||"")>order.indexOf(name)?/Previous/:/Next/}).filter({visible:true}).first();if(await button.isDisabled())break;await button.click()}await page.getByRole("button",{name:"Open",exact:true}).click()};
 const home=async()=>{await page.getByRole("button",{name:"Back",exact:true}).click()};
 await openRecords();

 // Ordinary farm record facts.
 await category("Confirmed orders");check("order card exposes identity quantity and date",await page.getByText("Stable record ID",{exact:true}).isVisible()&&await page.getByText("Booked quantity",{exact:true}).isVisible()&&await page.getByText("Due date",{exact:true}).isVisible());await home();
 await category("Growing spaces");const bedFacts=await page.locator(".ir-card dt").allTextContents(),emptyBeds=await page.getByText(/No bed records/).isVisible().catch(()=>false);check("bed path renders facts or explicit empty state",emptyBeds||["Stable record ID","Area","System","Reported crop"].every(value=>bedFacts.includes(value)),`${bedFacts.join(" | ")} :: ${(await page.locator("body").innerText()).slice(-400)}`);await home();
 await category("Inventory");const emptyInventory=await page.getByText(/No lot records/).isVisible().catch(()=>false);check("inventory path renders facts or explicit empty state",emptyInventory||await page.getByText("Reported quantity",{exact:true}).isVisible());await home();

 // Real XLSX candidate, source parser, and explicit rejection.
 await category("Farm records");const add=page.getByRole("button",{name:"Add candidate",exact:true});if(await add.isVisible())await add.click();
 const stamp=Date.now(),xlsxPath=`/tmp/v15-records-${stamp}.xlsx`,sourceName=`v15-records-${stamp}.xlsx`;
 execFileSync("python3",["-c",`from zipfile import ZipFile
import sys
ref=sys.argv[2]
sheet='''<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>date</t></is></c><c r="B1" t="inlineStr"><is><t>kind</t></is></c><c r="C1" t="inlineStr"><is><t>reference</t></is></c><c r="D1" t="inlineStr"><is><t>description</t></is></c><c r="E1" t="inlineStr"><is><t>amount</t></is></c><c r="F1" t="inlineStr"><is><t>currency</t></is></c></row><row r="2"><c r="A2" s="1"><v>46282</v></c><c r="B2" t="inlineStr"><is><t>expense</t></is></c><c r="C2" t="inlineStr"><is><t>'''+ref+'''</t></is></c><c r="D2" t="inlineStr"><is><t>XLSX nutrients</t></is></c><c r="E2"><v>9.75</v></c><c r="F2" t="inlineStr"><is><t>SGD</t></is></c></row></sheetData></worksheet>'''
styles='''<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><cellXfs count="2"><xf numFmtId="0"/><xf numFmtId="14"/></cellXfs></styleSheet>'''
with ZipFile(sys.argv[1],'w') as z:z.writestr('xl/worksheets/sheet1.xml',sheet);z.writestr('xl/styles.xml',styles)`,xlsxPath,`XLSX-${stamp}`]);
 await page.getByLabel("Candidate file").setInputFiles({name:sourceName,mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",buffer:await readFile(xlsxPath)});await page.getByRole("button",{name:"Upload accounting candidate",exact:true}).click();await page.getByLabel("Candidate file").waitFor({state:"detached"});
 const state=await api("/farm-workflow"),candidate=state.inbox.find(x=>x.source_name===sourceName);check("real XLSX upload creates parsed accounting candidate",candidate?.source_kind==="accounting_export"&&candidate?.rows?.[0]?.reference===`XLSX-${stamp}`,JSON.stringify(candidate));
 for(let i=0;i<100&&!(await page.getByRole("heading",{name:sourceName,exact:true}).isVisible().catch(()=>false));i++){const next=page.getByRole("button",{name:/Next/}).filter({visible:true}).first();if(await next.isDisabled())break;await next.click()}await page.getByRole("button",{name:"Review candidate",exact:true}).click();await page.getByRole("button",{name:"Reject candidate",exact:true}).click();for(let i=0;i<40;i++){if((await api("/farm-workflow")).inbox.find(x=>x.candidate_id===candidate.candidate_id)?.status==="rejected")break;await page.waitForTimeout(200)}check("candidate rejection persists without authority",(await api("/farm-workflow")).inbox.find(x=>x.candidate_id===candidate.candidate_id)?.status==="rejected");
 // Labelled image transport outage; request never reaches provider/backend.
 await page.getByRole("button",{name:"Add candidate",exact:true}).click();const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64");let imageRequests=0;await page.route("**/api/v1/farm-workflow/imports/upload**",route=>{imageRequests++;return route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({detail:"Controlled image extraction outage"})})},{times:1});await page.getByLabel("Candidate file").setInputFiles({name:"controlled-observation.png",mimeType:"image/png",buffer:png});await page.getByRole("button",{name:"Submit for AI extraction",exact:true}).click();await page.getByRole("alert").getByText(/Controlled image extraction outage/).waitFor();check("image outage retains file and makes one controlled request",imageRequests===1&&await page.getByLabel("Candidate file").evaluate(input=>input.files?.[0]?.name)==="controlled-observation.png");report.controlled_fixtures.push("One labelled PNG extraction 503 was fulfilled in-browser before backend/provider access.");await page.unroute("**/api/v1/farm-workflow/imports/upload**");await home();await home();

 // Create a task prerequisite, then complete and correct it through Records cards.
 let sessions=await api("/planning-sessions"),remembered=await page.evaluate(ids=>Object.values(localStorage).find(v=>ids.includes(v)),sessions.sessions.map(x=>x.id)),summary=sessions.sessions.find(x=>x.id===remembered)||sessions.sessions.find(x=>x.workflow),session=await api(`/planning-sessions/${summary.id}`);const wait=async()=>{for(let i=0;i<120;i++){session=await api(`/planning-sessions/${session.id}`);if(!["QUEUED","RUNNING"].includes(session.job?.status||""))return;await page.waitForTimeout(300)}throw new Error("planning timeout")};if(!session.result?.strategies?.length){await api(`/planning-sessions/${session.id}/calculate`,{method:"POST",body:JSON.stringify({revision:session.revision})});await wait()}
 const strategy=session.result.strategies.find(x=>String(x.status).toUpperCase()==="FEASIBLE")||session.result.strategies[0],start=session.farm.planning_date||session.farm.cutoff.slice(0,10),crop=strategy.allocations[0]?.crop_id||session.farm.orders[0].crop_id,assumptions={tentative_orders:[],future_demand:[{crop_id:crop,start_date:start,end_date:start,percent:100}],seasonal:[],order_changes:[],reservations:[],capacity:{nursery_sites:session.farm.resources.nursery_sites,labour_hours_per_week:session.farm.resources.labour_hours_per_week,cash_sgd:session.farm.resources.cash_sgd}};
 let proposal=await api("/farm-workflow/proposals",{method:"POST",body:JSON.stringify({session_id:session.id,base_revision:session.revision,changes:[{kind:"planning_assumptions",assumptions}],selected_strategy_id:strategy.id,source_candidate_ids:[],idempotency_key:crypto.randomUUID()})});await api(`/farm-workflow/proposals/${proposal.id}/apply`,{method:"POST",body:JSON.stringify({proposal_id:proposal.id,expected_base_revision:proposal.base_revision,idempotency_key:crypto.randomUUID()})});for(let i=0;i<120;i++){proposal=(await api("/farm-workflow")).proposals.find(x=>x.id===proposal.id);if(proposal?.status==="applied"&&proposal.recalculated_strategy_id)break;await page.waitForTimeout(300)}const approved=await api(`/farm-workflow/proposals/${proposal.id}/approve-actions`,{method:"POST",body:JSON.stringify({proposal_id:proposal.id,proposal_revision:proposal.proposal_revision,selected_strategy_id:proposal.recalculated_strategy_id,idempotency_key:crypto.randomUUID()})}),task=approved.tasks.find(x=>x.status==="pending"&&x.action!=="delivery")||approved.tasks[0];report.prerequisites.push(`Created and approved proposal ${proposal.id}; task decisions below use UI.`);
 await page.evaluate(()=>new Promise(resolve=>{window.addEventListener("farmtact-workflow-refreshed",resolve,{once:true});window.dispatchEvent(new Event("farmtact-workflow-refresh"))}));await category("Tasks & results");for(let i=0;i<200&&!(await page.getByText(task.id,{exact:true}).isVisible().catch(()=>false));i++){const next=page.getByRole("button",{name:/Next/}).filter({visible:true}).first();if(await next.isDisabled())break;await next.click()}check("task card binds completed-result prerequisite",await page.getByText(task.id,{exact:true}).isVisible(),task.id);await page.getByRole("button",{name:"Record result",exact:true}).click();await page.getByLabel("Result").selectOption("completed");for(const box of await page.getByRole("checkbox").all())await box.check();await page.getByLabel("Farmer note").fill("Completed through Records gaps acceptance");const save=page.getByRole("button",{name:"Save reported result",exact:true});await save.click();await save.waitFor({state:"detached",timeout:15000});let completed;for(let i=0;i<60;i++){completed=(await api("/farm-workflow")).tasks.find(x=>x.id===task.id);if(completed?.status==="completed")break;await page.waitForTimeout(200)}check("completed result submitted through task card",completed?.status==="completed"&&completed.event_revision>0,JSON.stringify(completed));
 await page.evaluate(()=>new Promise(resolve=>{window.addEventListener("farmtact-workflow-refreshed",resolve,{once:true});window.dispatchEvent(new Event("farmtact-workflow-refresh"))}));const priorTask=page.getByRole("button",{name:/Previous/}).filter({visible:true}).first();for(let i=0;i<200&&!(await priorTask.isDisabled());i++)await priorTask.click();for(let i=0;i<200&&!(await page.getByText(task.id,{exact:true}).isVisible().catch(()=>false));i++){const next=page.getByRole("button",{name:/Next/}).filter({visible:true}).first();if(await next.isDisabled())break;await next.click()}check("completed task remains addressable for correction",await page.getByText(task.id,{exact:true}).isVisible(),task.id);await page.getByRole("button",{name:"Correct record",exact:true}).click();await page.getByLabel("Field").selectOption("note");await page.getByLabel("Corrected value").fill("Corrected farmer note through Records UI");await page.getByLabel("Reason").fill("Correcting note wording for acceptance");const correction=page.getByRole("button",{name:"Save auditable correction",exact:true});await correction.click();await correction.waitFor({state:"detached",timeout:15000});let corrected;for(let i=0;i<60;i++){corrected=(await api("/farm-workflow")).tasks.find(x=>x.id===task.id);if(corrected?.result_note==="Corrected farmer note through Records UI")break;await page.waitForTimeout(200)}check("non-default result-note correction is audited",corrected?.result_note==="Corrected farmer note through Records UI"&&corrected.event_revision>completed.event_revision,JSON.stringify(corrected));
 await home();await category("Verify & recover");check("Verify card exposes farmer-reported forecast and source result",await page.getByText("Farmer-reported outcome",{exact:true}).isVisible()&&await page.getByText("Source result",{exact:true}).isVisible()&&await page.getByText(/not independently verified/i).isVisible());await home();
 await category("Workflow history");let foundEvent=await page.getByText(task.id,{exact:true}).isVisible().catch(()=>false);for(let i=0;i<120&&!foundEvent;i++){const next=page.getByRole("button",{name:/Next/}).filter({visible:true}).first();if(await next.isDisabled())break;await next.click();foundEvent=await page.getByText(task.id,{exact:true}).isVisible().catch(()=>false)}check("Records history replays task event read-only",foundEvent&&await page.getByText(/Saved replay only/).isVisible());
}catch(error){report.failures.push({name:"browser run",detail:error instanceof Error?error.stack:String(error)})}finally{report.finished_at=new Date().toISOString();report.status=report.failures.length?"FAILED":"PASSED";await mkdir(dirname(reportPath),{recursive:true});await writeFile(reportPath,JSON.stringify(report,null,2));await browser?.close()}
if(report.failures.length){console.error(JSON.stringify(report.failures,null,2));process.exitCode=1}else console.log(`V15 records gap checks passed (${report.checks.length}).`);
