import { access, mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from '../../apps/web/node_modules/@playwright/test/index.mjs';

const root=resolve(new URL('../..',import.meta.url).pathname),base=(process.env.BASE_URL||'http://127.0.0.1:4196').replace(/\/$/,'');
const report={status:'RUNNING',base,checks:[],failures:[]};
const check=(name,pass,detail)=>{report.checks.push({name,pass:Boolean(pass),detail});if(!pass)throw Error(`${name}: ${JSON.stringify(detail)}`)};
const state=async preferred=>{for(const path of preferred)try{await access(path);return path}catch{}throw Error(`No private browser storage fixture: ${preferred.join(', ')}`)};
const attrs=locator=>locator.evaluate(node=>({id:node.getAttribute('data-card-id'),entityId:node.getAttribute('data-entity-id'),entityKind:node.getAttribute('data-entity-kind'),sessionId:node.getAttribute('data-session-id'),inputHash:node.getAttribute('data-input-hash'),revision:node.getAttribute('data-session-revision'),resultId:node.getAttribute('data-result-id'),snapshotId:node.getAttribute('data-snapshot-id'),provenance:JSON.parse(node.getAttribute('data-provenance')||'[]'),targets:JSON.parse(node.getAttribute('data-board-targets')||'[]'),basis:node.getAttribute('data-outcome-basis'),actions:JSON.parse(node.getAttribute('data-card-actions')||'[]'),authority:JSON.parse(node.getAttribute('data-action-authority')||'{}'),eligibility:JSON.parse(node.getAttribute('data-action-eligibility')||'{}')}));
async function visibleLabels(page,selector){return page.locator(`${selector} button:visible`).evaluateAll(nodes=>nodes.map(node=>({label:(node.textContent||'').trim(),disabled:node.disabled})))}
function verifyActions(name,card,buttons){const actual=card.actions.map(x=>x.label),labels=buttons.map(x=>x.label);check(`${name}: metadata action labels match visible footer`,labels.every(label=>actual.includes(label)),{labels,actual});for(const action of card.actions){const button=buttons.find(item=>item.label===action.label);check(`${name}: action authority, eligibility and visible disabled state agree`,['local_navigation','server_mutation'].includes(action.authority)&&['local','server'].includes(action.eligibilitySource)&&typeof action.eligible==='boolean'&&(!button||button.disabled===!action.eligible),{action,button})}}
async function api(page,path){return page.evaluate(async path=>{const response=await fetch(`/api/v1${path}`);if(!response.ok)throw Error(`${path}: ${response.status}`);return response.json()},path)}
async function open(page){await page.goto(`${base}/play`,{waitUntil:'domcontentloaded'});await page.locator('.ic-shell').waitFor()}
async function openTool(page,title){if(!await page.locator('.ic-path').isVisible().catch(()=>false))await page.getByRole('button',{name:'More',exact:true}).click();const order=['Plan','Records & work','Knowledge & evidence','Experiments','History & preferences'];for(let i=0;i<7&&!await page.getByText(title,{exact:true}).isVisible().catch(()=>false);i++){const text=await page.locator('.ic-path').innerText(),from=order.findIndex(x=>text.endsWith(x)),to=order.indexOf(title);await page.getByRole('button',{name:from>to?'← Previous':'Next →',exact:true}).click()}await page.getByRole('button',{name:'Open tool',exact:true}).click()}
async function closeTool(page){for(let i=0;i<8&&await page.locator('.integrated-tool,.integrated-records,.ik-shell').count();i++){const back=page.getByRole('button',{name:'Back',exact:true}).filter({visible:true}).first(),close=page.getByRole('button',{name:'Close',exact:true}).filter({visible:true}).first();if(await back.count())await back.click();else if(await close.count())await close.click();else break}if(await page.locator('.ic-path').count())await page.getByRole('button',{name:'Back',exact:true}).click()}
async function restoreMission(page){for(let i=0;i<16;i++){if(await page.getByRole('button',{name:'More',exact:true}).isVisible().catch(()=>false))return;const back=page.getByRole('button',{name:'Back',exact:true}).filter({visible:true}).first();if(!await back.count())break;await back.click();await page.waitForTimeout(80)}throw Error('Could not restore the mission card from persisted navigation')}

let browser;
try{
 browser=await chromium.launch({headless:true});
 const cardsState=await state(['/tmp/farmtact-v15-cards-storage.json','/tmp/farmtact-v15-records-extended-storage.json']);
 const context=await browser.newContext({viewport:{width:390,height:844},storageState:cardsState,reducedMotion:'reduce'}),page=await context.newPage();await open(page);
 const sessions=await api(page,'/planning-sessions'),summary=sessions.sessions.find(x=>x.workflow),session=await api(page,`/planning-sessions/${summary.id}`);
 const mission=await attrs(page.locator('.ic-card'));check('mission canonical entity matches shown ordinary order',mission.entityKind==='order'&&mission.entityId===session.farm.orders[0].id,mission);check('mission frozen planning binding matches server',mission.sessionId===session.id&&mission.inputHash===session.input_hash&&Number(mission.revision)===session.revision,mission);verifyActions('mission',mission,await visibleLabels(page,'.ic-keys'));

 await openTool(page,'Plan');await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('button',{name:'Open',exact:true}).click();const strategyId=await page.getByLabel('Compare strategy').inputValue(),strategy=session.result.strategies.find(x=>x.id===strategyId),planStrategy=await attrs(page.locator('.integrated-tool__card'));check('Plan strategy canonical identity and board targets match server result',planStrategy.entityKind==='strategy'&&planStrategy.entityId===strategyId&&strategy.allocations.every(x=>planStrategy.targets.includes(x.bed_id)),planStrategy);verifyActions('Plan strategy',planStrategy,await visibleLabels(page,'.integrated-tool footer'));
 await page.getByRole('button',{name:'Back',exact:true}).click();for(let i=0;i<2;i++)await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('button',{name:'Open',exact:true}).click();await page.getByRole('button',{name:'Load latest proposal',exact:true}).click();await page.getByRole('heading',{name:'Proposal and recalculation',exact:true}).waitFor();const proposalCard=await attrs(page.locator('.integrated-tool__card')),workflow=await api(page,'/farm-workflow'),proposal=workflow.proposals.find(x=>x.id===proposalCard.entityId);check('Plan proposal identity/revision matches saved proposal',proposalCard.entityKind==='proposal'&&proposal&&Number(proposalCard.revision)===proposal.proposal_revision,proposalCard);verifyActions('Plan proposal',proposalCard,await visibleLabels(page,'.integrated-tool footer'));await closeTool(page);await closeTool(page);

 await openTool(page,'Records & work');for(let i=0;i<6;i++)await page.getByRole('button',{name:/Next/}).filter({visible:true}).first().click();await page.getByRole('button',{name:'Open',exact:true}).click();for(let i=0;i<workflow.tasks.length&&!await page.getByRole('button',{name:'Record result',exact:true}).count();i++){const next=page.getByRole('button',{name:/Next/}).filter({visible:true}).first();if(!await next.isEnabled())break;await next.click()}const taskCard=await attrs(page.locator('.ir-card[data-card-id]')),shownTask=(await page.getByText(/Stable task ID/).locator('xpath=following-sibling::dd').first().innerText()).trim(),task=workflow.tasks.find(x=>x.id===shownTask),taskProposal=workflow.proposals.find(x=>x.id===task?.proposal_id);check('Records task canonical ID/revision matches saved task',taskCard.entityKind==='workflow_task'&&taskCard.entityId===shownTask&&task&&Number(taskCard.revision)===task.event_revision,taskCard);check('Records task uses proposal frozen result binding',Boolean(taskProposal)&&taskCard.inputHash===(taskProposal.session_input_hash||null)&&taskCard.resultId===(taskProposal.approved_result_id||null),{taskCard,taskProposal});verifyActions('Records task',taskCard,await visibleLabels(page,'.ir-actions'));
 const recordResult=page.getByRole('button',{name:'Record result',exact:true});if(await recordResult.count()){await recordResult.click();await page.getByRole('button',{name:'Save reported result',exact:true}).waitFor();await page.waitForFunction(()=>{const card=document.querySelector('.ir-card[data-card-id]'),button=Array.from(document.querySelectorAll('.ir-actions button')).find(node=>node.textContent?.trim()==='Save reported result'),action=JSON.parse(card?.getAttribute('data-card-actions')||'[]').find(item=>item.label==='Save reported result');return Boolean(button&&action&&button.disabled===!action.eligible)});const resultForm=await attrs(page.locator('.ir-card[data-card-id]'));check('Records result form retains exact task identity and frozen proposal binding',resultForm.entityKind==='workflow_task'&&resultForm.entityId===shownTask&&resultForm.inputHash===taskCard.inputHash&&resultForm.resultId===taskCard.resultId&&Number(resultForm.revision)===task.event_revision,{taskCard,resultForm});verifyActions('Records result form',resultForm,await visibleLabels(page,'.ir-actions'));await page.getByRole('button',{name:'Back',exact:true}).click()}
 await closeTool(page);

 await openTool(page,'Knowledge & evidence');while(await page.getByRole('button',{name:'Previous',exact:true}).isEnabled())await page.getByRole('button',{name:'Previous',exact:true}).click();const cropCard=await attrs(page.locator('.ik-card'));check('Knowledge crop has no invented planning binding',cropCard.entityKind==='crop'&&[cropCard.sessionId,cropCard.inputHash,cropCard.revision,cropCard.resultId,cropCard.snapshotId].every(value=>value===null),cropCard);let sourceCard;for(let i=0;i<40;i++){const card=await attrs(page.locator('.ik-card'));if(card.entityKind==='source'){sourceCard=card;break}await page.getByRole('button',{name:'Next',exact:true}).click()}check('Knowledge source has canonical identity and no invented planning binding',sourceCard?.entityKind==='source'&&sourceCard.entityId&&[sourceCard.sessionId,sourceCard.inputHash,sourceCard.revision,sourceCard.resultId,sourceCard.snapshotId].every(value=>value===null),sourceCard);verifyActions('Knowledge source',sourceCard,await visibleLabels(page,'.ik-actions'));
 // Saved conversation fixture is read-only and its displayed ID must become the canonical card identity.
 const conversation={id:'bound-contract-conversation',title:'Bound contract replay',status:'COMPLETED',replay:true,snapshot_ref:{kind:'planning',id:'historical-session:historical-result',hash:'historical-input-hash',version:'planning-snapshot-v1'},messages:[]};
 await page.route('**/api/v1/conversations',route=>route.request().method()==='GET'&&new URL(route.request().url()).pathname.endsWith('/conversations')?route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({conversations:[conversation]})}):route.continue());
 await page.route(new RegExp(`/api/v1/conversations/${conversation.id}/replay(?:\\?.*)?$`),route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(conversation)}));
 await page.reload({waitUntil:'domcontentloaded'});await page.locator('.ik-card').waitFor();for(let i=0;i<80&&!await page.getByRole('heading',{name:'Complete adviser transcripts',exact:true}).count();i++)await page.getByRole('button',{name:'Next',exact:true}).click();await page.waitForTimeout(300);await page.getByLabel('Saved thread').selectOption(conversation.id);const replayButton=page.getByRole('button',{name:'Open read-only replay',exact:true});await replayButton.waitFor();await page.waitForFunction(()=>!Array.from(document.querySelectorAll('button')).find(button=>button.textContent?.trim()==='Open read-only replay')?.disabled);await Promise.all([page.waitForResponse(response=>new URL(response.url()).pathname.endsWith(`/conversations/${conversation.id}/replay`)&&response.ok()),replayButton.click()]);await page.waitForFunction(id=>document.querySelector('.ik-card')?.getAttribute('data-entity-id')===id,conversation.id);const conversationCard=await attrs(page.locator('.ik-card'));check('Knowledge conversation decodes its historical planning snapshot without inventing a revision',conversationCard.entityKind==='conversation'&&conversationCard.entityId===conversation.id&&conversationCard.snapshotId===conversation.snapshot_ref.id&&conversationCard.sessionId==='historical-session'&&conversationCard.inputHash===conversation.snapshot_ref.hash&&conversationCard.revision===null&&conversationCard.resultId==='historical-result',{conversationCard,currentSession:session.id,snapshotRef:conversation.snapshot_ref});await closeTool(page);

 await openTool(page,'History & preferences');await page.getByRole('button',{name:'Open',exact:true}).click();await page.getByRole('button',{name:'Read-only replay',exact:true}).waitFor();const historyList=await attrs(page.locator('.integrated-tool__card')),historyId=(await page.locator('.integrated-tool__card p').filter({hasText:/^[a-f0-9]{20,}$/}).first().innerText()).trim();check('History saved plan canonical ID matches shown saved record',historyList.entityKind==='planning_session'&&historyList.entityId===historyId,historyList);verifyActions('History saved plan',historyList,await visibleLabels(page,'.integrated-tool footer'));await page.getByRole('button',{name:'Read-only replay',exact:true}).click();await page.getByRole('button',{name:'Saved versions',exact:true}).click();const requestedResult=await page.getByLabel('Saved result').inputValue();await page.getByRole('button',{name:'Replay saved result',exact:true}).click();await page.waitForFunction(result=>document.querySelector('.integrated-tool__card')?.getAttribute('data-result-id')===result,requestedResult);const frozenHistory=await attrs(page.locator('.integrated-tool__card'));check('History frozen replay binds exact requested result with unknown revision',frozenHistory.entityKind==='planning_result'&&frozenHistory.entityId===requestedResult&&frozenHistory.resultId===requestedResult&&frozenHistory.revision===null,frozenHistory);await context.close();

 const scenarioState=await state([`/tmp/farmtact-v15-scenarios-${new URL(base).port}.json`,cardsState]);const expContext=await browser.newContext({viewport:{width:430,height:900},storageState:scenarioState}),exp=await expContext.newPage();await open(exp);await restoreMission(exp);await openTool(exp,'Experiments');await exp.getByRole('button',{name:'Open',exact:true}).click();const scenarioCard=await attrs(exp.locator('.integrated-tool__card'));check('Experiments scenario ID/hash match shown saved scenario',scenarioCard.entityKind==='scenario'&&scenarioCard.entityId&&scenarioCard.inputHash,scenarioCard);verifyActions('Experiments scenario',scenarioCard,await visibleLabels(exp,'.integrated-tool footer'));await exp.getByRole('button',{name:'Back',exact:true}).click();await exp.getByRole('button',{name:'Next',exact:true}).click();await exp.getByRole('button',{name:'Open',exact:true}).click();const datasetCard=await attrs(exp.locator('.integrated-tool__card'));check('Experiments dataset has canonical snapshot and absent unrelated planning binding',datasetCard.entityKind==='dataset_snapshot'&&datasetCard.entityId===datasetCard.snapshotId&&datasetCard.sessionId===null&&datasetCard.revision===null,datasetCard);await exp.getByRole('button',{name:'Inspect records',exact:true}).click();const recordCard=await attrs(exp.locator('.integrated-tool__card'));check('Experiments record view remains bound to exact frozen dataset',recordCard.entityKind==='dataset_snapshot'&&recordCard.entityId===datasetCard.entityId&&recordCard.snapshotId===datasetCard.snapshotId,recordCard);verifyActions('Experiments record',recordCard,await visibleLabels(exp,'.integrated-tool footer'));await expContext.close();
 report.status='PASS';
}catch(error){report.status='FAIL';report.failures.push(error instanceof Error?error.stack:String(error));process.exitCode=1}finally{await browser?.close();await mkdir(resolve(root,'reports/v15'),{recursive:true});await writeFile(resolve(root,'reports/v15/bound-card-contract.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))}
