import { chromium } from "../../apps/web/node_modules/@playwright/test/index.mjs";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const base=(process.env.BASE_URL||"http://127.0.0.1:4192").replace(/\/$/,"");
const report={status:"RUNNING",checks:[],failures:[]};
const check=(name,pass,detail)=>{report.checks.push({name,pass:Boolean(pass),detail});if(!pass)throw new Error(`${name}: ${JSON.stringify(detail)}`)};
const click=(page,name)=>page.getByRole("button",{name,exact:true}).click();
let browser;
try{
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:"reduce"});const page=await context.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));
 const live=await (await fetch(`${base}/api/v1/planning-sessions`)).json().catch(()=>({sessions:[]}));
 const listed=live.sessions?.[0];const existing=listed?await(await fetch(`${base}/api/v1/planning-sessions/${listed.id}`)).json():null;
 const planning={...(existing||{}),id:existing?.id||"v15-knowledge-planning",revision:existing?.revision||1,farm:existing?.farm||{orders:[{id:"focus-order",crop_id:"lettuce",due_date:"2026-10-01",quantity_kg:20}],beds:[{id:"focus-bed",name:"Focus bed",area_m2:10,system:"sheltered_hydroponic"}]},selected_strategy_id:existing?.selected_strategy_id||existing?.result?.strategies?.[0]?.id||"balanced",result:existing?.result?.strategies?.length?existing.result:{strategies:[{id:"balanced",name:"Balanced",status:"FEASIBLE",metrics:{},allocations:[],violations:[]}]},assumptions:existing?.assumptions||{tentative_orders:[],future_demand:[],seasonal:[],order_changes:[],reservations:[]}};
 const conversation={id:"v15-gateway-fixture",title:"Validated gateway fixture",advisor_id:"asha",status:"COMPLETED",created_at:"2026-09-17T00:00:00Z",updated_at:"2026-09-17T00:00:00Z",last_request_status:"COMPLETED",messages:[]};let creates=0,direct=0,invites=0,councils=0,createBody,uncertainSend=false,failNextGet=false;const directKeys=[];
 const partial={id:"partial-finding",speaker:"advisor",speaker_name:"Asha",content:"The recorded answer is partial because one public source is stale.",validation_status:"references_verified",evidence_status:"partial",interpretation_status:"qualitative_unverified",fact_refs:[],rendered_facts:[],proposed_actions:[]};
 const withheld={id:"withheld-finding",speaker:"advisor",speaker_name:"Idris",content:"The specialist withheld a recommendation because evidence was insufficient.",validation_status:"withheld",evidence_status:"withheld",interpretation_status:"withheld",fact_refs:[],rendered_facts:[],proposed_actions:[]};
 const council={id:"council-finding",speaker:"advisor",speaker_name:"Planning Council",content:"The Council recorded a bounded reviewed finding.",validation_status:"references_verified",evidence_status:"validated",interpretation_status:"qualitative_unverified",fact_refs:[],rendered_facts:[],proposed_actions:[]};
 await page.route("**/api/v1/planning-sessions",r=>r.request().method()==="GET"?r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({sessions:[planning]})}):r.continue());
 await page.route(`**/api/v1/planning-sessions/${planning.id}`,r=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify(planning)}));
 await page.route("**/api/v1/planning-sessions/*",r=>r.request().method()==="GET"?r.fulfill({status:200,contentType:"application/json",body:JSON.stringify(new URL(r.request().url()).pathname.endsWith("/planning-sessions")?{sessions:[planning]}:planning)}):r.continue());
 await page.route("**/api/v1/conversations",async r=>{if(r.request().method()==="GET")return r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({conversations:[]})});creates++;createBody=r.request().postDataJSON();return r.fulfill({status:201,contentType:"application/json",body:JSON.stringify({id:conversation.id,status:"READY"})})});
 await page.route(`**/api/v1/conversations/${conversation.id}`,r=>{if(failNextGet){failNextGet=false;return r.fulfill({status:503,contentType:"application/json",body:JSON.stringify({detail:"Fixture transcript unavailable"})})}return r.fulfill({status:200,contentType:"application/json",body:JSON.stringify(conversation)})});
 await page.route(`**/api/v1/conversations/${conversation.id}/messages`,async r=>{direct++;directKeys.push(r.request().headers()["idempotency-key"]);const content=r.request().postDataJSON().content;if(!conversation.messages.some(message=>message.speaker==="user"&&message.content===content))conversation.messages.push({id:`direct-question-${direct}`,speaker:"user",content,validation_status:"recorded"},{...partial,id:`partial-finding-${direct}`});if(uncertainSend){uncertainSend=false;return r.fulfill({status:503,contentType:"application/json",body:JSON.stringify({detail:"Fixture response lost after commit"})})}return r.fulfill({status:202,contentType:"application/json",body:JSON.stringify({id:`direct-request-${direct}`,conversation_id:conversation.id,status:"COMPLETED"})})});
 await page.route(`**/api/v1/conversations/${conversation.id}/invite`,async r=>{invites++;conversation.messages.push({id:"invite-question",speaker:"user",content:r.request().postDataJSON().question,validation_status:"recorded"},withheld);return r.fulfill({status:202,contentType:"application/json",body:JSON.stringify({id:"invite-request",conversation_id:conversation.id,status:"COMPLETED"})})});
 await page.route(`**/api/v1/conversations/${conversation.id}/council`,async r=>{councils++;conversation.messages.push({id:"council-question",speaker:"user",content:r.request().postDataJSON().question,validation_status:"recorded"},council);return r.fulfill({status:202,contentType:"application/json",body:JSON.stringify({id:"council-request",conversation_id:conversation.id,status:"COMPLETED"})})});

 await page.goto(base,{waitUntil:"domcontentloaded"});await page.locator(".ic-shell").waitFor();await click(page,"More");for(let i=0;i<2;i++)await click(page,"Next →");await click(page,"Open tool");await page.getByRole("heading",{name:"Inspect the facts. Ask deliberately.",exact:true}).waitFor();
 for(let i=0;i<13;i++)await click(page,"Next");
 await page.getByLabel("Frozen focus").selectOption(`order:${planning.farm.orders[0].id}`);
 await page.getByLabel("Question about the frozen planning session").fill("Explain the frozen demand trade-off.");await click(page,"Submit question");await page.getByText(partial.content,{exact:true}).waitFor();
 check("V15 direct adviser fixture records partial validated result",creates===1&&direct===1&&/partial/i.test(await page.locator(".ik-message").last().innerText()),{creates,direct});
 check("V15 adviser submission uses exact canonical selected focus",createBody?.focus?.card_id===`order-${planning.farm.orders[0].id}`&&createBody?.focus?.entity_kind==="order"&&createBody?.focus?.entity_id===planning.farm.orders[0].id,createBody?.focus);

 await page.getByLabel("Discussion action").selectOption("invite");await page.getByLabel("Reply to saved specialist finding").selectOption("partial-finding-1");await page.getByLabel("Question about the frozen planning session").fill("Ask another specialist to review this finding.");await click(page,"Invite specialist");await page.getByText(withheld.content,{exact:true}).waitFor();
 check("V15 invite fixture retains withheld specialist finding",invites===1&&/withheld/i.test(await page.locator(".ik-message").last().innerText()),invites);

 await page.getByLabel("Discussion action").selectOption("council");await page.getByLabel("Reply to saved specialist finding").selectOption(withheld.id);await page.getByLabel("Question about the frozen planning session").fill("Convene the Council on the recorded findings.");await click(page,"Convene Council");await page.getByText(council.content,{exact:true}).waitFor();
 check("V15 conversational Council fixture completes through explicit submit",councils===1&&/references verified/i.test(await page.locator(".ik-message").last().innerText()),councils);
 check("V15 adviser fixtures preserve the full recorded transcript",conversation.messages.length===6&&await page.locator(".ik-message").count()===6,conversation.messages.length);

 // Explicit post-commit outage fixture: the server records the user turn but the response is lost.
 await page.getByLabel("Frozen focus").selectOption(`bed:${planning.farm.beds[0].id}`);await click(page,"Start new focused thread");await page.getByLabel("Discussion action").selectOption("direct");await page.getByLabel("Question about the frozen planning session").fill("Retain this uncertain submission draft.");uncertainSend=true;const beforeUncertain=direct,keyOffset=directKeys.length;await click(page,"Submit question");await page.getByRole("alert").filter({hasText:/response lost after commit/i}).waitFor();check("uncertain adviser submission retains its draft",await page.getByLabel("Question about the frozen planning session").inputValue()==="Retain this uncertain submission draft.");await click(page,"Submit question");await page.getByText("Retain this uncertain submission draft.",{exact:true}).waitFor();check("explicit retry uses the same thread and idempotency identity",direct===beforeUncertain+2&&creates===2&&directKeys[keyOffset]===directKeys[keyOffset+1],{direct,creates,keysMatch:directKeys[keyOffset]===directKeys[keyOffset+1]});

 // Accepted POST followed by transcript GET outage must offer refresh, never resend.
 await page.getByLabel("Frozen focus").selectOption(`strategy:${planning.result.strategies[0].id}`);await click(page,"Start new focused thread");await page.getByLabel("Question about the frozen planning session").fill("Accepted before transcript refresh.");const beforeAccepted=direct;failNextGet=true;await click(page,"Submit question");await page.getByRole("button",{name:"Refresh accepted submission",exact:true}).waitFor();check("accepted adviser POST clears resend state before transcript refresh",direct===beforeAccepted+1&&await page.getByLabel("Question about the frozen planning session").inputValue()==="",direct);await click(page,"Refresh accepted submission");check("read-only refresh does not resubmit accepted provider work",direct===beforeAccepted+1,direct);
 check("V15 Knowledge gateway fixture has no browser errors",errors.length===0,errors);report.status="PASS";
}catch(error){report.status="FAIL";report.failures.push(error instanceof Error?error.stack:String(error));process.exitCode=1}finally{if(browser)await browser.close();await mkdir(resolve("reports/v15"),{recursive:true});await writeFile(resolve("reports/v15/knowledge-browser.json"),JSON.stringify(report,null,2)+"\n");process.stdout.write(JSON.stringify(report,null,2)+"\n")}
