import { chromium } from '../../apps/web/node_modules/@playwright/test/index.mjs';
import { access, mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root=resolve(new URL('../..',import.meta.url).pathname),base=(process.env.BASE_URL||'http://127.0.0.1:4192').replace(/\/$/,'');
const storage=process.env.STORAGE_STATE||'/tmp/farmtact-v15-tools-storage.json';await access(storage);
const widths=[360,390,430,1280],report={status:'RUNNING',base,build:'index-C2Hgt_dH.js',checks:[],screenshots:[],requests:{writes:[]},failures:[]};
const check=(name,pass,detail)=>{report.checks.push({name,pass:Boolean(pass),detail});if(!pass)throw Error(`${name}: ${JSON.stringify(detail)}`)};
const click=(page,name)=>page.getByRole('button',{name,exact:true}).click();
const shell=async page=>{await page.getByRole('button',{name:/^(More|Back)$/}).first().waitFor();for(let depth=0;depth<12;depth++){if(await page.getByRole('button',{name:'More',exact:true}).count())return;const back=page.getByRole('button',{name:'Back',exact:true});if(await back.count()){await back.last().click();continue}throw Error('Cannot return to shared shell')}throw Error('Shared shell depth exceeded')};
const openTool=async(page,offset,heading)=>{await shell(page);await click(page,'More');for(let i=0;i<offset;i++)await click(page,'Next →');await click(page,'Open tool');await page.getByRole('heading',{name:heading,exact:true}).waitFor()};
const audit=async(page,width,key,cardSelector,actionsSelector)=>{
 const card=page.locator(cardSelector).filter({visible:true}).first(),actions=page.locator(actionsSelector).filter({visible:true}).first();await card.waitFor();
 const dimensions=await page.evaluate(selector=>{const node=document.querySelector(selector),root=document.documentElement,rect=node?.getBoundingClientRect();return{documentScrollWidth:root.scrollWidth,documentClientWidth:root.clientWidth,documentScrollHeight:root.scrollHeight,viewportHeight:innerHeight,cardLeft:rect?.left,cardRight:rect?.right,cardScrollWidth:node?.scrollWidth,cardClientWidth:node?.clientWidth}},cardSelector);
 check(`${width} ${key}: no horizontal overflow`,dimensions.documentScrollWidth<=dimensions.documentClientWidth+1&&Number(dimensions.cardLeft)>=-1&&Number(dimensions.cardRight)<=width+1&&Number(dimensions.cardScrollWidth)<=Number(dimensions.cardClientWidth)+1,dimensions);
 const actionCount=await actions.locator('button:visible,a:visible').count();check(`${width} ${key}: action area has at most three controls`,actionCount<=3,{actionCount});
 const scroll=await page.evaluate(()=>{const before=scrollY;scrollTo(0,document.documentElement.scrollHeight);const after=scrollY;scrollTo(0,before);return{before,after,content:document.documentElement.scrollHeight,viewport:innerHeight}});check(`${width} ${key}: content fits or scrolls vertically`,scroll.content<=scroll.viewport+1||scroll.after>0,scroll);
 const focusTarget=actions.locator('button:not([disabled]),a[href]').first();await focusTarget.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');const focus=await focusTarget.evaluate(node=>{const css=getComputedStyle(node);return{active:document.activeElement===node,focusVisible:node.matches(':focus-visible'),outlineStyle:css.outlineStyle,outlineWidth:css.outlineWidth,boxShadow:css.boxShadow}});check(`${width} ${key}: keyboard focus is visible`,focus.active&&focus.focusVisible&&(focus.outlineStyle!=='none'&&focus.outlineWidth!=='0px'||focus.boxShadow!=='none'),focus);
 const path=resolve(root,`reports/v15/responsive-decks-${width}-${key}.png`);await page.screenshot({path,fullPage:true,animations:'disabled'});report.screenshots.push(`reports/v15/responsive-decks-${width}-${key}.png`);
};
let browser;
try{browser=await chromium.launch({headless:true});const context=await browser.newContext({storageState:storage,reducedMotion:'reduce'});
 for(const width of widths){const page=await context.newPage();await page.setViewportSize({width,height:width>500?900:844});const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(!['GET','HEAD','OPTIONS'].includes(request.method()))report.requests.writes.push(`${request.method()} ${new URL(request.url()).pathname}`)});await page.route('**/api/v1/**',route=>['GET','HEAD','OPTIONS'].includes(route.request().method())?route.continue():route.abort('blockedbyclient'));await page.goto(`${base}/play`,{waitUntil:'domcontentloaded'});await page.locator('.ic-shell').waitFor();
  await openTool(page,0,'Objectives & all demand');for(let i=0;i<2;i++)await click(page,'Next');await click(page,'Open');await page.getByRole('heading',{name:'Resource & demand assumptions',exact:true}).waitFor();await audit(page,width,'plan-assumptions','.integrated-tool__card','.integrated-tool > footer');
  await openTool(page,1,'Records & work');await click(page,'Next');await click(page,'Open');await click(page,'Add candidate');await page.getByRole('heading',{name:'Import a farm record',exact:true}).waitFor();await audit(page,width,'records-import','.ir-card','.ir-actions');
  await openTool(page,2,'Inspect the facts. Ask deliberately.');await page.locator('.ik-crop-art').waitFor();await audit(page,width,'knowledge-crop','.ik-card','.ik-actions');for(let i=0;i<20&&!await page.getByText('Export policy',{exact:true}).count();i++){await click(page,'Next');await page.waitForTimeout(40)}await page.getByText('Export policy',{exact:true}).waitFor();await audit(page,width,'knowledge-source','.ik-card','.ik-actions');
  await openTool(page,3,'Scenarios & quests');for(let i=0;i<2;i++)await click(page,'Next');await click(page,'Open');await page.getByRole('heading',{name:'Dataset & forecast settings',exact:true}).waitFor();await audit(page,width,'experiments-controls','.integrated-tool__card','.integrated-tool > footer');
  await openTool(page,4,'Saved plans');await click(page,'Open');await page.getByRole('heading',{name:'Saved plans',exact:true}).waitFor();await audit(page,width,'history-identities','.integrated-tool__card','.integrated-tool > footer');
  check(`${width}: sampled decks have no browser error`,errors.length===0,errors);await page.close();
 }
 check('responsive deck audit sends zero POST/write requests',report.requests.writes.length===0,report.requests.writes);report.status='PASS';await context.close();
}catch(error){report.status='FAIL';report.failures.push(error instanceof Error?error.stack:String(error));process.exitCode=1}finally{await browser?.close();await mkdir(resolve(root,'reports/v15'),{recursive:true});await writeFile(resolve(root,'reports/v15/responsive-decks.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))}
