import { access, mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from '../../apps/web/node_modules/@playwright/test/index.mjs';
const root=resolve(new URL('../..',import.meta.url).pathname),base=(process.env.BASE_URL||'http://127.0.0.1:4196').replace(/\/$/,'');
const storage='/tmp/farmtact-v15-cards-storage.json';await access(storage);
const report={status:'RUNNING',base,checks:[],failures:[],screenshots:[]};const check=(name,pass,detail)=>{report.checks.push({name,pass:Boolean(pass),detail});if(!pass)throw Error(`${name}: ${JSON.stringify(detail)}`)};
let browser;
try{browser=await chromium.launch({headless:true});const context=await browser.newContext({storageState:storage,reducedMotion:'reduce'});
 for(const width of [360,390,430,1280]){const page=await context.newPage();await page.setViewportSize({width,height:width>500?900:844});const posts=[],errors=[];page.on('request',r=>{if(r.method()==='POST')posts.push(new URL(r.url()).pathname)});page.on('pageerror',e=>errors.push(String(e)));await page.goto(`${base}/play`,{waitUntil:'domcontentloaded'});await page.locator('.ic-shell').waitFor();
  while(await page.locator('.integrated-tool').count())await page.locator('.integrated-tool').getByRole('button',{name:'Back',exact:true}).click();if((await page.locator('.ic-deck-nav').innerText()).includes('Farm tools'))await page.getByRole('button',{name:'Back',exact:true}).click();
  check(`${width}: one card and one three-action area`,await page.locator('.ic-card').count()===1&&await page.locator('.ic-keys>button').count()===3);check(`${width}: no horizontal overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));check(`${width}: card publishes canonical identity`,Boolean(await page.locator('.ic-card').getAttribute('data-entity-id')));check(`${width}: passive scene is not four-bed fixture`,await page.locator('.ic-beds article').count()>4);check(`${width}: read-only open has no mutation`,posts.length===0,posts);check(`${width}: no browser error`,errors.length===0,errors);const path=resolve(root,`reports/v15/responsive-contract-${width}.png`);await page.screenshot({path,fullPage:true,animations:'disabled'});report.screenshots.push(`reports/v15/responsive-contract-${width}.png`);await page.close()}
 const page=await context.newPage();const posts=[];page.on('request',r=>{if(r.method()==='POST')posts.push(new URL(r.url()).pathname)});await page.goto(`${base}/play`,{waitUntil:'domcontentloaded'});await page.locator('.ic-shell').waitFor();while(await page.locator('.integrated-tool').count())await page.locator('.integrated-tool').getByRole('button',{name:'Back',exact:true}).click();if((await page.locator('.ic-deck-nav').innerText()).includes('Farm tools'))await page.getByRole('button',{name:'Back',exact:true}).click();
 while(await page.getByRole('button',{name:'← Previous'}).isEnabled())await page.getByRole('button',{name:'← Previous'}).click();const before=await page.locator('.ic-card').evaluate(node=>({id:node.getAttribute('data-card-id'),session:node.getAttribute('data-session-id'),revision:node.getAttribute('data-session-revision')}));await page.getByRole('button',{name:'Explain'}).click();if(await page.getByRole('button',{name:'Skip guide'}).count()){await page.getByRole('button',{name:'Skip guide'}).click();await page.getByRole('button',{name:'Resume guide'}).waitFor()}const resume=page.getByRole('button',{name:'Resume guide'});if(!await resume.count())throw Error('Guide toggle unavailable on the ordinary mission card');await resume.click();await page.getByRole('button',{name:'Skip guide'}).waitFor();await page.reload({waitUntil:'domcontentloaded'});await page.locator('.ic-shell').waitFor();if(!await page.getByRole('button',{name:'Skip guide'}).count())await page.getByRole('button',{name:'Explain'}).click();await page.getByRole('button',{name:'Skip guide'}).click();await page.getByRole('button',{name:'Resume guide'}).waitFor();const after=await page.locator('.ic-card').evaluate(node=>({id:node.getAttribute('data-card-id'),session:node.getAttribute('data-session-id'),revision:node.getAttribute('data-session-revision')}));check('guide resume then skip preserves exact session and planner revision',before.session===after.session&&before.revision===after.revision,{before,after});check('guide skip and resume use only guidance mutations',posts.length>=2&&posts.every(path=>/\/guidance$/.test(path)),posts);await context.close();report.status='PASS';
}catch(error){report.status='FAIL';report.failures.push(error instanceof Error?error.stack:String(error));process.exitCode=1}finally{await browser?.close();await mkdir(resolve(root,'reports/v15'),{recursive:true});await writeFile(resolve(root,'reports/v15/responsive-guide-contract.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))}
