import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from '../../apps/web/node_modules/@playwright/test/index.mjs';
const root=resolve(new URL('../..',import.meta.url).pathname),base=(process.env.BASE_URL||'http://127.0.0.1:4196').replace(/\/$/,''),reportDir=process.env.REPORT_DIR||'v16',storageState=process.env.STORAGE_STATE||'/tmp/farmtact-v15-cards-storage.json';
const report={status:'RUNNING',base,checks:[],mission_stages:[],defects:[],requests:{posts:[],providers:[]}};
const check=(name,pass,detail)=>{report.checks.push({name,pass:Boolean(pass),detail});if(!pass)report.defects.push({name,detail})};
let browser;
try {
 browser=await chromium.launch({headless:true}); const context=await browser.newContext({viewport:{width:390,height:844},storageState});await context.addInitScript(()=>{const prior=localStorage.getItem('farmtact:v15:planning-session');if(prior&&!localStorage.getItem('farmtact:v16:planning-session'))localStorage.setItem('farmtact:v16:planning-session',prior)}); const page=await context.newPage();
 page.on('request',r=>{const u=new URL(r.url());if(r.method()==='POST')report.requests.posts.push(u.pathname);if(/provider|adviser|advisor|council|research/i.test(u.pathname)&&r.method()!=='GET')report.requests.providers.push(u.pathname)});
 await page.route('**/api/v1/**',route=>route.request().method()==='GET'?route.continue():route.abort('blockedbyclient'));
 await page.goto(base+'/play',{waitUntil:'domcontentloaded'}); await page.locator('.ic-shell').waitFor();
 // Normalize to the first mission card without relying on persisted navigation.
 while(await page.getByRole('button',{name:'Back',exact:true}).count()&&await page.locator('.ic-path').count()) await page.getByRole('button',{name:'Back',exact:true}).click();
 for(let i=0;i<20&&!await page.getByRole('button',{name:'← Previous',exact:true}).isDisabled();i++) await page.getByRole('button',{name:'← Previous',exact:true}).click();
 const seen=new Set();
 for(let guard=0;guard<20;guard++){
  const card=page.locator('.ic-card'); const id=await card.getAttribute('data-card-id'); if(!id||seen.has(id))break; seen.add(id);
  const title=await card.locator('h1').innerText(); const resultId=await card.getAttribute('data-result-id'); const basis=await card.getAttribute('data-outcome-basis');
  await page.getByRole('button',{name:'Explain',exact:true}).click(); const explain=page.locator('.ic-explanation'); await explain.waitFor();
  const terms=await explain.locator('dt').allInnerTexts(), values=await explain.locator('dd').allInnerTexts();
  const expected=['What changed','Why','Tradeoff','Evidence / limits','Next action'];
  check(`A04 ${id} has five-part Explain`,expected.every((x,n)=>terms[n]===x)&&terms.length>=5,{id,title,terms});
  check(`A04 ${id} exposes facts without invented fallback`,values.length>=5&&values.slice(0,5).every(v=>v.trim()&& !/undefined|\[object Object\]|Reason not available for this saved result|\{.*"reservations"/i.test(v)),{id,title,values,resultId,basis});
  check(`A04 ${id} retains authoritative binding/evidence`,Boolean(resultId)&&['projection','recorded_simulation'].includes(basis||'')&&values[3].trim().length>8,{id,resultId,basis,evidence:values[3]});
  const relevant=id==='situation'?/frozen.*order records.*grow spaces/i.test(values[0])&&/objective.*kg.*due/i.test(values[1])&&/planning input/i.test(values[3])
    :id.startsWith('strategy-')?/preview.not saved/i.test(values[0])&&/delivery.*shortfall.*cost/i.test(values[2])&&/bed-.*\d{4}-\d{2}-\d{2}/i.test(values[3])
    :id==='reservation'?/bed-\d+.*(?:reserved|reservation|unavailable)/i.test(values[0])&&/target bed-\d+/i.test(values[3])
    :id==='approved'?/(?:persisted|current-result|previously saved) sandbox task/i.test(values[0])&&/physical farm operations remain disabled/i.test(values[0])&&/proposal.*task ids/i.test(values[3])
    :id==='simulation-result'?/recorded simulation date/i.test(values[0])&&/recorded totals/i.test(values[2])&&/event.*affected entities/i.test(values[3]):false;
  check(`A04 ${id} explanation is stage-specific`,relevant,{id,values:values.slice(0,5)});
  report.mission_stages.push({id,title,resultId,basis,terms,values}); await page.getByRole('button',{name:'Back',exact:true}).click();
  const next=page.getByRole('button',{name:'Next →',exact:true}); if(await next.isDisabled())break; await next.click();
 }
 check('A04 enumerated every rendered core mission stage',seen.size>=5,{count:seen.size,ids:[...seen]});
 // Keyboard and click must invoke the same visible primary decision action.
 for(let i=0;i<20&&!await page.getByRole('button',{name:'← Previous',exact:true}).isDisabled();i++)await page.getByRole('button',{name:'← Previous',exact:true}).click();
 const primary=page.locator('.ic-actions .is-primary'),primaryLabel=(await primary.innerText()).trim(),originId=await page.locator('.ic-card').getAttribute('data-card-id');
 await primary.click();const clickState=await page.locator('.ic-card').getAttribute('data-card-id');if(await page.locator('.ic-path').count())await page.getByRole('button',{name:'Back',exact:true}).click();else if(clickState!==originId){const previous=page.getByRole('button',{name:'← Previous',exact:true});if(!await previous.isDisabled())await previous.click()}
 await page.locator(`.ic-card[data-card-id="${originId}"]`).focus();await page.keyboard.press('Enter');const keyState=await page.locator('.ic-card').getAttribute('data-card-id');
 check('A14 Enter and click activate the same primary decision action',clickState===keyState&&clickState!==originId,{originId,primaryLabel,clickState,keyState});
 check('A14 keyboard/click activation attempted no write',report.requests.posts.length===0&&report.requests.providers.length===0,report.requests);
 const live=await page.evaluate(async()=>{const id=localStorage.getItem('farmtact:v16:planning-session');const [session,workflow]=await Promise.all([fetch(`/api/v1/planning-sessions/${id}`).then(r=>r.json()),fetch('/api/v1/farm-workflow').then(r=>r.json())]);return {id,session,workflow}});
 const fixturePage=async(session,workflow)=>{const p=await context.newPage();await p.addInitScript(id=>localStorage.removeItem(`farmtact:v16:integrated-cards-navigation:${id}`),live.id);await p.route(`**/api/v1/planning-sessions/${live.id}`,r=>r.request().method()==='GET'?r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(session)}):r.abort('blockedbyclient'));await p.route('**/api/v1/farm-workflow',r=>r.request().method()==='GET'?r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(workflow)}):r.abort('blockedbyclient'));await p.goto(base+'/play',{waitUntil:'domcontentloaded'});await p.locator('.ic-shell').waitFor();for(let i=0;i<20;i++){const previous=p.getByRole('button',{name:'← Previous',exact:true});if(await previous.isDisabled())break;await previous.click()}return p};
 const noResult=structuredClone(live.session);noResult.status='DRAFT';noResult.result=null;noResult.result_id=null;noResult.job=null;noResult.selected_strategy_id=null;if(noResult.tactical_context?.planning_snapshot)noResult.tactical_context.planning_snapshot.result_id=null;const noResultWorkflow={...structuredClone(live.workflow),proposals:[],tasks:[]};const beforePage=await fixturePage(noResult,noResultWorkflow);const beforeCard=beforePage.locator('.ic-card');check('A04 pre-calculation situation has null outcome basis',await beforeCard.getAttribute('data-outcome-basis')===null,{basis:await beforeCard.getAttribute('data-outcome-basis')});await beforePage.getByRole('button',{name:'Explain',exact:true}).click();check('A04 pre-calculation explanation labels frozen input without fake projection',/Frozen planning input.*no calculated result bound/i.test(await beforePage.locator('.ic-explanation').innerText()),await beforePage.locator('.ic-explanation').innerText());await beforePage.close();
 const mixedSession=structuredClone(live.session),mixedWorkflow=structuredClone(live.workflow),target=mixedSession.tactical_context?.grow_space?.id,mixed=mixedWorkflow.proposals?.find(p=>p.recalculation_job?.id===mixedSession.result_id);if(!mixed||!target)throw Error('mixed fixture requires current-result proposal and tactical target');{const current={tentative_orders:[],future_demand:[],seasonal:[],order_changes:[{id:'mixed-order-change'}],reservations:[{bed_id:target,start_date:'2026-12-01',end_date:'2026-12-20'}]};const previous={tentative_orders:[],future_demand:[],seasonal:[],order_changes:[],reservations:[{bed_id:target,start_date:'2026-11-01',end_date:'2026-11-20'}]};mixed.changes=[{kind:'planning_assumptions',assumptions:current}];mixed.inverse_changes=[{kind:'planning_assumptions',assumptions:previous}];mixed.explanation={...mixed.explanation,why:'GENERAL_SENTINEL_MIXED',tradeoff:{coverage_kg:999},allocation_changes:[]}}const mixedPage=await fixturePage(mixedSession,mixedWorkflow);for(let i=0;i<10&&await mixedPage.locator('.ic-card').getAttribute('data-card-id')!=='reservation';i++)await mixedPage.getByRole('button',{name:'Next →',exact:true}).click();await mixedPage.getByRole('button',{name:'Explain',exact:true}).click();const mixedText=await mixedPage.locator('.ic-explanation').innerText();check('A04 mixed proposal shows exact target dates without attributing whole-proposal deltas',/2026-11-01.*2026-11-20.*2026-12-01.*2026-12-20/is.test(mixedText)&&/No target-specific signed delta/i.test(mixedText)&&!/GENERAL_SENTINEL|999/.test(mixedText),mixedText);await mixedPage.close();
 const edgeSession=structuredClone(live.session),edgeWorkflow=structuredClone(live.workflow);if(!edgeSession.simulation)throw Error('edge fixture requires saved simulation');for(const strategy of edgeSession.result?.strategies||[]){strategy.metrics={...strategy.metrics,fill_rate:null,shortfall_kg:null,cost_sgd:null};strategy.allocations=[]}if(edgeSession.simulation)delete edgeSession.simulation.scene_transition;const bound=edgeWorkflow.proposals?.find(p=>p.recalculation_job?.id===edgeSession.result_id);if(!bound)throw Error('edge fixture requires current-result proposal');{bound.inverse_changes=[];bound.explanation={...bound.explanation,why:'GENERAL_SENTINEL_UNRELATED',tradeoff:{nested:{unsafe:true}},allocation_changes:[]}}const edgePage=await fixturePage(edgeSession,edgeWorkflow);
 await edgePage.getByRole('button',{name:'Next →',exact:true}).click();await edgePage.getByRole('button',{name:'Explain',exact:true}).click();const missingStrategy=await edgePage.locator('.ic-explanation').innerText();check('A04 missing strategy metrics and allocations stay explicitly unknown',/Delivery —%.*shortfall — kg.*cost SGD —/is.test(missingStrategy)&&/no dated allocations reported/i.test(missingStrategy)&&!/±0|\[object Object\]/.test(missingStrategy),missingStrategy);await edgePage.getByRole('button',{name:'Back',exact:true}).click();
 for(let i=0;i<10&&await edgePage.locator('.ic-card').getAttribute('data-card-id')!=='reservation';i++)await edgePage.getByRole('button',{name:'Next →',exact:true}).click();await edgePage.getByRole('button',{name:'Explain',exact:true}).click();const unrelated=await edgePage.locator('.ic-explanation').innerText();check('A04 unrelated general proposal cannot supply reservation causality',/before\/after reservation facts are unavailable/i.test(unrelated)&&/No target-specific signed delta/i.test(unrelated)&&!/GENERAL_SENTINEL|\[object Object\]/.test(unrelated),unrelated);await edgePage.getByRole('button',{name:'Back',exact:true}).click();
 for(let i=0;i<10&&await edgePage.locator('.ic-card').getAttribute('data-card-id')!=='simulation-result';i++)await edgePage.getByRole('button',{name:'Next →',exact:true}).click();await edgePage.getByRole('button',{name:'Explain',exact:true}).click();const missingTransition=await edgePage.locator('.ic-explanation').innerText();check('A04 simulation without transition reports missing event facts without invention',/event not reported.*affected entities not reported/is.test(missingTransition)&&!/undefined|\[object Object\]/.test(missingTransition),missingTransition);await edgePage.close();
 await context.close();
 // Asset audit: seven stable portrait identities, self-contained SVG references and unique IDs.
 const advisorDir=resolve(root,'apps/web/public/art/advisors'), names=(await readdir(advisorDir)).filter(x=>x.endsWith('.svg')).sort();
 check('A12 seven portrait identities are present',names.length===7,{names});
 for(const name of names){const svg=await readFile(resolve(advisorDir,name),'utf8');const ids=[...svg.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]);const refs=[...svg.matchAll(/(?:href|src)=["']([^"']+)["']/g)].map(m=>m[1]);check(`A12 ${name} has unique IDs and no external references`,new Set(ids).size===ids.length&&refs.every(x=>x.startsWith('#')||x.startsWith('data:')),{ids:ids.length,duplicates:ids.filter((x,i)=>ids.indexOf(x)!==i),external:refs.filter(x=>!x.startsWith('#')&&!x.startsWith('data:'))})}
 const cropDir=resolve(root,'apps/web/public/art/crops'), crops=(await readdir(cropDir)).filter(x=>x.endsWith('.svg'));
 let cropUnsafe=[];for(const name of crops){const svg=await readFile(resolve(cropDir,name),'utf8');const ids=[...svg.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]);const refs=[...svg.matchAll(/(?:href|src)=["']([^"']+)["']/g)].map(m=>m[1]);if(new Set(ids).size!==ids.length||refs.some(x=>!x.startsWith('#')&&!x.startsWith('data:')))cropUnsafe.push(name)}
 check('A12 crop SVGs are duplicate-ID safe and self-contained',cropUnsafe.length===0,{assets:crops.length,unsafe:cropUnsafe});
 const source=await readFile(resolve(root,'apps/web/src/components/IntegratedCards.tsx'),'utf8');
 check('A12 unknown and unsupported stages fall back to literal recorded labels',/stage\.replaceAll\("_", " "\)/.test(source)&&/stage === "harvested"/.test(source)&&/stage === "sanitation"/.test(source)&&/stage === "empty"/.test(source),{source:'IntegratedCards.tsx stage branch'});
 const assetContext=await browser.newContext({viewport:{width:390,height:844}}),assetPage=await assetContext.newPage();await assetPage.setContent(`<main><figure><img data-size="54" src="${base}/art/crops/caixin-growing.svg" style="width:54px;height:54px"><figcaption>Caixin</figcaption></figure><figure><img data-size="64" src="${base}/art/crops/kailan-ready.svg" style="width:64px;height:64px"><figcaption>Kailan</figcaption></figure></main>`);await assetPage.waitForFunction(()=>[...document.images].every(image=>image.complete));
 const assetInspection=await assetPage.evaluate(()=>[...document.querySelectorAll('figure')].map(figure=>{const image=figure.querySelector('img'),box=image.getBoundingClientRect();return {requested:Number(image.dataset.size),width:box.width,height:box.height,name:figure.querySelector('figcaption').textContent?.trim(),decoded:image.naturalWidth>0}}));
 check('A12 crop assets and names remain readable at explicit 54px and 64px inspections',assetInspection.length===2&&assetInspection.every(row=>row.decoded&&row.width===row.requested&&row.height===row.requested&&Boolean(row.name)),assetInspection);await assetContext.close();
 const knowledgeCss=await readFile(resolve(root,'apps/web/src/components/IntegratedKnowledge.css'),'utf8'),portraitSizes=[...knowledgeCss.matchAll(/\.ik-title-row>img\{[^}]*width:(\d+)px/g)].map(m=>Number(m[1]));
 check('A12 primary portrait retains the specified 64px compact identity',portraitSizes.includes(64),{declaredWidths:portraitSizes});
 report.status=report.defects.length?'FAIL':'PASS';
}catch(e){report.status='ERROR';report.defects.push({name:'suite error',detail:e instanceof Error?e.stack:String(e)});process.exitCode=1}finally{await browser?.close();await mkdir(resolve(root,`reports/${reportDir}`),{recursive:true});await writeFile(resolve(root,`reports/${reportDir}/final-semantics.json`),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,checks:report.checks.length,defects:report.defects},null,2))}
