/**
 * Read-only public V9 proof for persisted mission, conversation, and research UI.
 *
 * This harness must run only after the release operator says the private state is
 * ready. It forwards GET/HEAD requests only. The one optional conversation-open
 * POST generated by the UI is satisfied locally with the already persisted ID;
 * no mutation reaches the public service. Provider-capable actions are blocked.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { chromium } from '../../apps/web/node_modules/@playwright/test/index.mjs'

const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..')
const base=(process.env.FARMTACT_PUBLIC_V9_URL||'https://farmtact.fly.dev/v9/').replace(/\/?$/,'/')
const conversationStatePath=process.env.FARMTACT_V9_CONVERSATION_STATE||'/tmp/farmtact-v9-public-conversation-state.json'
const planningStatePath=process.env.FARMTACT_V9_PLANNING_STATE||'/tmp/farmtact-v9-public-planning-browser.json'
const planningEvidencePath=resolve(root,'reports/v9/planning-public.json')
const reportPath=resolve(root,process.env.FARMTACT_V9_LIVE_UI_REPORT||'reports/v9/ui-live-replay.json')
const screenshotDir=resolve(root,process.env.FARMTACT_V9_LIVE_UI_SCREENSHOTS||'reports/v9/ui-live-replay')
const expectedSourcePrefix=process.env.FARMTACT_V9_SOURCE_PREFIX||'89d29cc'
const advisorNames={ravi:'Ravi',hana:'Hana',idris:'Idris',mei:'Mei',lina:'Lina',ben:'Ben',asha:'Asha'}
const expectedCouncilSpeakers=Object.keys(advisorNames)

const report={
  status:'RUNNING',started_at:new Date().toISOString(),base_url:base,expected_source_prefix:expectedSourcePrefix,
  method:'Public V9, authenticated tenant-scoped GET-only browser replay at 390px and 1280px. All public mutations and direct provider traffic are intercepted before network dispatch.',
  checks:[],failures:[],page_errors:[],console_errors:[],blocked_requests:[],local_navigation_shims:[],mutation_attempts:[],public_mutations_forwarded:[],provider_requests:[],screenshots:[],
  observed:{conversation_messages:null,council_speakers:[],conversation_fact_cards:null,mission_claims:null,mission_fact_cards:null,research_fact_cards:null},
  limitations:[
    'This reads already persisted public records and makes no new inference or numerical calculation.',
    'When a saved scenario discussion is not the currently selected UI context, the browser may ask to create a matching conversation. The harness answers that request locally with the existing persisted conversation ID; it never forwards the POST.',
    'Headless Chromium checks rendering and geometry, not provider quality, physical devices, assistive technology, or human usability.',
    'Mission Council checks prove retrieval and rendering only. A validated status chip is a reference/contract result and is not semantic validation; the recorded Supply Chain semantic score is known to be false.',
    'The mission bootstrap response is adjusted in-browser to place the actual saved public run from reports/v9/planning-public.json in the existing latest_run slot. This prevents a later zero-inference execution trial from changing which persisted run the UI displays.',
  ],
}
const check=(name,pass,detail='')=>{const row={name,pass:Boolean(pass),detail:String(detail).replace(/\s+/g,' ').trim().slice(0,900)};report.checks.push(row);if(!row.pass)report.failures.push(row)}
const idFrom=(state,...keys)=>{for(const key of keys){const direct=state?.[key],nested=state?.ids?.[key];if(typeof direct==='string'&&direct)return direct;if(typeof nested==='string'&&nested)return nested}return''}
const safePath=url=>{try{return new URL(url).pathname}catch{return String(url)}}
const json=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)})
const screenshot=async(page,name)=>{const path=resolve(screenshotDir,`${name}.png`);await page.screenshot({path,animations:'disabled',caret:'hide'});report.screenshots.push(relative(root,path))}
const visibleWithinViewport=(page,locator)=>locator.evaluateAll((nodes,width)=>nodes.every(node=>{const box=node.getBoundingClientRect();return box.left>=-1&&box.right<=width+1}),page.viewportSize()?.width||0)

async function loadState(path){
  const state=JSON.parse(await readFile(path,'utf8'))
  const input=Array.isArray(state.cookies)?state.cookies.find(cookie=>cookie.name==='farmtact_v9_session'):null
  const legacy=typeof state.cookie==='string'?{name:'farmtact_v9_session',value:state.cookie,domain:new URL(base).hostname,httpOnly:true,secure:true,sameSite:'Strict'}:null
  const cookie=input||legacy
  if(!cookie||typeof cookie.value!=='string'||!cookie.value)throw Error(`${path} does not contain farmtact_v9_session credentials`)
  return {raw:state,storageState:{cookies:[{...cookie,name:'farmtact_v9_session',domain:cookie.domain||new URL(base).hostname,path:'/v9/',secure:true,httpOnly:true,sameSite:cookie.sameSite||'Strict'}],origins:Array.isArray(state.origins)?state.origins:[]}}
}

async function guardedContext(browser,storageState,viewport){
  const context=await browser.newContext({storageState,viewport,hasTouch:viewport.width<700,isMobile:viewport.width<700,reducedMotion:'reduce'})
  await context.route('**/*',async route=>{
    const request=route.request(),url=request.url(),method=request.method().toUpperCase(),parsed=new URL(url)
    if(/(?:api\.)?(?:deepseek|openai|anthropic)\./i.test(parsed.hostname)){
      report.provider_requests.push({method,path:parsed.pathname});return route.abort('blockedbyclient')
    }
    if(['GET','HEAD','OPTIONS'].includes(method))return route.continue()
    const path=parsed.pathname
    if(method==='POST'&&path==='/v9/api/v1/conversations'&&context.__existingConversationId){
      report.local_navigation_shims.push({method,path,purpose:'open_existing_persisted_conversation'})
      return json(route,{id:context.__existingConversationId,status:'COMPLETED',reused:true},200)
    }
    report.blocked_requests.push({method,path})
    if(/\/conversations\/[^/]+\/(?:messages|invite|council)$|\/planning-runs|\/council-research/.test(path))report.provider_requests.push({method,path})
    return json(route,{detail:'Mutation disabled by the read-only V9 replay harness'},599)
  })
  const cookies=await context.cookies(base)
  const scoped=cookies.filter(cookie=>cookie.name==='farmtact_v9_session')
  check('browser uses only the V9 tenant cookie at the V9 path',scoped.length===1&&scoped[0].path==='/v9/'&&scoped[0].secure,scoped.map(cookie=>({name:cookie.name,path:cookie.path,domain:cookie.domain,secure:cookie.secure})))
  return context
}

function observePage(page,label){
  page.on('pageerror',error=>report.page_errors.push(`${label}: ${error.message}`))
  page.on('console',message=>{if(message.type()==='error')report.console_errors.push(`${label}: ${message.text()}`)})
  page.on('request',request=>{if(!['GET','HEAD','OPTIONS'].includes(request.method().toUpperCase()))report.mutation_attempts.push({method:request.method(),path:safePath(request.url())})})
}

async function fetchJSON(page,path){
  return page.evaluate(async path=>{const response=await fetch(path,{method:'GET',credentials:'same-origin'});if(!response.ok)throw Error(`${path} returned ${response.status}`);return response.json()},path)
}

async function openPersistedConversation(page,context,conversation){
  context.__existingConversationId=conversation.id
  const advisor=advisorNames[conversation.advisor_id]||advisorNames[conversation.messages.find(message=>message.speaker==='advisor')?.speaker_id]||'Asha'
  const launcher=page.getByRole('button',{name:new RegExp(`^Talk to ${advisor},`)})
  await launcher.first().click()
  const dialog=page.getByRole('dialog',{name:new RegExp(`^${advisor} ·`)})
  await dialog.waitFor({timeout:30_000})
  const saved=dialog.getByLabel('Saved discussions')
  await saved.waitFor({timeout:30_000})
  if(await saved.inputValue()!==conversation.id)await saved.selectOption(conversation.id)
  await dialog.getByText(`Recorded discussion · ${conversation.messages.length} messages`,{exact:true}).waitFor({timeout:30_000})
  return dialog
}

await mkdir(dirname(reportPath),{recursive:true});await mkdir(screenshotDir,{recursive:true})
let browser
try{
  const [conversationState,planningState,planningEvidence]=await Promise.all([loadState(conversationStatePath),loadState(planningStatePath),readFile(planningEvidencePath,'utf8').then(JSON.parse)])
  const savedMissionRunId=String(planningEvidence.run_id||planningEvidence.run?.id||'')
  const conversationId=idFrom(conversationState.raw,'conversation_id')
  const researchSessionId=idFrom(conversationState.raw,'research_session_id')
  const researchConversationId=idFrom(conversationState.raw,'research_conversation_id')
  if(!conversationId)throw Error('The V9 public conversation state does not contain conversation_id')
  if(!researchSessionId||!researchConversationId)throw Error('The V9 public conversation state does not contain both research replay IDs')
  if(!savedMissionRunId)throw Error('reports/v9/planning-public.json does not contain the saved public mission run ID')

  browser=await chromium.launch({headless:true})

  // Actual persisted public mission Council, then its stored numerical replay.
  const missionContext=await guardedContext(browser,planningState.storageState,{width:1280,height:900})
  const missionPage=await missionContext.newPage();observePage(missionPage,'mission')
  await missionPage.goto(base,{waitUntil:'domcontentloaded',timeout:45_000})
  await missionPage.locator('.world-page').waitFor({timeout:45_000})
  const health=await fetchJSON(missionPage,'/v9/api/v1/health')
  check('public runtime identifies immutable V9 source',health.edition==='v9'&&String(health.source_commit||'').startsWith(expectedSourcePrefix),{edition:health.edition,source_commit:String(health.source_commit||'').slice(0,12)})
  const savedMission=await fetchJSON(missionPage,`/v9/api/v1/planning-runs/${encodeURIComponent(savedMissionRunId)}`)
  check('saved public mission is terminal and has seven Council claims',['ACCEPTED_FOR_SIMULATION','REVIEW_WITHHELD'].includes(String(savedMission.status).toUpperCase())&&savedMission.claims?.length===7,{status:savedMission.status,claims:savedMission.claims?.length})
  await missionPage.route('**/v9/api/v1/bootstrap',async route=>{const fetched=await route.fetch(),body=await fetched.json();await json(route,{...body,latest_run:savedMission})})
  await missionPage.reload({waitUntil:'domcontentloaded',timeout:45_000})
  await missionPage.locator('.world-page').waitFor({timeout:45_000})
  await missionPage.getByRole('button',{name:'Farm tools',exact:true}).click()
  await missionPage.getByRole('heading',{name:'Council interpretations'}).waitFor()
  await missionPage.getByRole('button',{name:'View all'}).click()
  const missionCouncil=missionPage.getByRole('dialog',{name:'Council findings'});await missionCouncil.waitFor()
  report.observed.mission_claims=await missionCouncil.locator('.advisor-card--full').count()
  report.observed.mission_fact_cards=await missionCouncil.locator('[data-fact-reference]').count()
  check('mission Council renders all seven persisted roles',report.observed.mission_claims===7,report.observed.mission_claims)
  check('mission Council exposes persisted code-rendered facts',report.observed.mission_fact_cards>0,report.observed.mission_fact_cards)
  check('mission Council typed facts remain within desktop viewport',await visibleWithinViewport(missionPage,missionCouncil.locator('[data-fact-reference]')))
  await screenshot(missionPage,'mission-council-1280')
  await missionCouncil.getByRole('button',{name:'Close'}).click()
  const missionPostsBefore=report.mutation_attempts.length
  const [missionReplayResponse]=await Promise.all([
    missionPage.waitForResponse(response=>response.request().method()==='GET'&&/\/planning-runs\/[^/]+\/replay$/.test(new URL(response.url()).pathname)),
    missionPage.getByRole('button',{name:'Replay run',exact:true}).click(),
  ])
  const missionReplay=await missionReplayResponse.json()
  check('mission replay uses stored events with no inference',missionReplay.execution_mode==='replay'&&missionReplay.inference_origin==='stored_events'&&Boolean(missionReplay.replay_of),{execution_mode:missionReplay.execution_mode,inference_origin:missionReplay.inference_origin})
  check('mission replay sends no mutation',report.mutation_attempts.length===missionPostsBefore)
  await missionContext.close()

  // Actual ten-message public conversation and its GET-only replay.
  const conversationContext=await guardedContext(browser,conversationState.storageState,{width:390,height:844})
  const conversationPage=await conversationContext.newPage();observePage(conversationPage,'conversation')
  await conversationPage.goto(base,{waitUntil:'domcontentloaded',timeout:45_000})
  await conversationPage.locator('.world-page').waitFor({timeout:45_000})
  const conversation=await fetchJSON(conversationPage,`/v9/api/v1/conversations/${encodeURIComponent(conversationId)}`)
  report.observed.conversation_messages=conversation.messages?.length
  const advisorMessages=(conversation.messages||[]).filter(message=>message.speaker==='advisor')
  const councilMessages=(conversation.messages||[]).filter(message=>message.speaker==='advisor'&&message.request_mode==='council')
  const speakers=[...new Set(councilMessages.map(message=>message.speaker_id).filter(id=>expectedCouncilSpeakers.includes(id)))].sort()
  report.observed.council_speakers=speakers
  check('stored public conversation contains exactly ten advisor messages',advisorMessages.length===10,advisorMessages.length)
  check('stored transcript total matches the private trial receipt',conversation.messages?.length===conversationState.raw.conversation_message_count,{rendered:conversation.messages?.length,receipt:conversationState.raw.conversation_message_count})
  check('stored Council contains all seven specialist speakers',speakers.length===7&&expectedCouncilSpeakers.every(id=>speakers.includes(id)),speakers)
  check('stored Council has exactly one final planner conclusion',councilMessages.filter(message=>message.planner_conclusion===true).length===1,councilMessages.filter(message=>message.planner_conclusion===true).length)
  const conversationFacts=(conversation.messages||[]).flatMap(message=>Array.isArray(message.rendered_facts)?message.rendered_facts:[])
  check('stored conversation includes code-rendered frozen facts',conversationFacts.length>0,conversationFacts.length)
  const unsupportedAbstentions=(conversation.messages||[]).filter(message=>message.speaker==='advisor'&&/unsupported|blocked/.test(`${message.validation_status||''} ${message.evidence_status||''}`.toLowerCase())&&message.relationship==='abstention')
  check('stored conversation preserves both unsupported abstentions',unsupportedAbstentions.length===2,unsupportedAbstentions.length)
  check('both unsupported abstentions retain their server-rendered fact records',unsupportedAbstentions.every(message=>Array.isArray(message.rendered_facts)&&message.rendered_facts.length>0),unsupportedAbstentions.map(message=>message.rendered_facts?.length||0))

  const dialog=await openPersistedConversation(conversationPage,conversationContext,conversation)
  check('conversation UI shows the seven-person Council roster',await dialog.getByLabel('Council speakers').locator('span').count()===7,await dialog.getByLabel('Council speakers').locator('span').count())
  check('conversation UI labels the planner conclusion',await dialog.getByText('Planner’s conclusion',{exact:true}).count()===1,await dialog.getByText('Planner’s conclusion',{exact:true}).count())
  check('conversation UI visibly preserves both unsupported states',await dialog.locator('.message-card--advisor .validation-chip--bad').count()===2,await dialog.locator('.message-card--advisor .validation-chip--bad').count())
  check('unsupported frozen values are shown without a validation claim',await dialog.getByText('Selected frozen values · response not validated',{exact:true}).count()===2,await dialog.getByText('Selected frozen values · response not validated',{exact:true}).count())
  report.observed.conversation_fact_cards=await dialog.locator('[data-fact-reference]').count()
  check('conversation UI renders frozen fact cards',report.observed.conversation_fact_cards>0,report.observed.conversation_fact_cards)
  check('conversation fact values are presented outside qualitative prose',await dialog.getByText('Values come from server records, never from the adviser’s prose. Their presence does not verify the interpretation.',{exact:true}).count()>0)
  check('conversation fact cards fit the 390px viewport',await visibleWithinViewport(conversationPage,dialog.locator('[data-fact-reference]')))
  check('conversation page has no 390px horizontal overflow',await conversationPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),await conversationPage.evaluate(()=>`${document.documentElement.scrollWidth}/${innerWidth}`))
  await dialog.locator('.message-card--advisor').last().scrollIntoViewIfNeeded();await screenshot(conversationPage,'conversation-replay-390')

  const inferencePostsBefore=report.provider_requests.length,mutationsBefore=report.mutation_attempts.length
  const [replayResponse]=await Promise.all([
    conversationPage.waitForResponse(response=>response.request().method()==='GET'&&/\/conversations\/[^/]+\/replay$/.test(new URL(response.url()).pathname)),
    dialog.getByRole('button',{name:'Replay',exact:true}).click(),
  ])
  const replay=await replayResponse.json()
  await dialog.getByText('Recorded replay · opening and replaying use no new inference.',{exact:true}).waitFor()
  check('conversation replay response records zero inference calls',replay.inference_triggered===false&&replay.new_calculation_occurred===false&&replay.inference_origin==='stored_actual_replay'&&replay.replay_of===conversation.id,{inference_triggered:replay.inference_triggered,new_calculation_occurred:replay.new_calculation_occurred,inference_origin:replay.inference_origin})
  check('conversation replay sends no inference or mutation request',report.provider_requests.length===inferencePostsBefore&&report.mutation_attempts.length===mutationsBefore)

  await conversationPage.setViewportSize({width:1280,height:900})
  check('conversation page has no 1280px horizontal overflow',await conversationPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),await conversationPage.evaluate(()=>`${document.documentElement.scrollWidth}/${innerWidth}`))
  check('conversation fact cards fit the 1280px viewport',await visibleWithinViewport(conversationPage,dialog.locator('[data-fact-reference]')))
  await dialog.locator('.message-card--advisor').last().scrollIntoViewIfNeeded();await screenshot(conversationPage,'conversation-replay-1280')
  await conversationContext.close()

  // Actual stored research-advisor response, opened without sending a question.
  const researchContext=await guardedContext(browser,conversationState.storageState,{width:390,height:844})
  await researchContext.addInitScript(({sessionId,conversationId})=>{
    sessionStorage.setItem('farmtact:v9:council-research-session',sessionId)
    sessionStorage.setItem(`farmtact:v9:council-research-actual:${sessionId}`,conversationId)
  },{sessionId:researchSessionId,conversationId:researchConversationId})
  const researchPage=await researchContext.newPage();observePage(researchPage,'research')
  await researchPage.goto(`${base}research`,{waitUntil:'domcontentloaded',timeout:45_000})
  await researchPage.getByRole('heading',{name:'Talk through a farm decision.'}).waitFor({timeout:45_000})
  const actual=researchPage.locator('.actual-advisor');await actual.waitFor()
  if(!await actual.evaluate(node=>node.open))await actual.locator(':scope > summary').click()
  const actualResponse=actual.locator('.actual-response');await actualResponse.waitFor({timeout:30_000})
  const researchConversation=await fetchJSON(researchPage,`/v9/api/v1/conversations/${encodeURIComponent(researchConversationId)}`)
  const expectedResearchFacts=(researchConversation.messages||[]).flatMap(message=>Array.isArray(message.rendered_facts)?message.rendered_facts:[]).length
  report.observed.research_fact_cards=await actualResponse.locator('[data-fact-reference]').count()
  check('stored research response includes rendered facts',expectedResearchFacts>0,expectedResearchFacts)
  check('research UI renders its stored code-authoritative facts',report.observed.research_fact_cards===expectedResearchFacts,{rendered:report.observed.research_fact_cards,stored:expectedResearchFacts})
  check('research UI labels qualitative interpretation separately',await actualResponse.getByText(/interpretation:/).count()>0&&await actualResponse.getByText(/does not verify the interpretation/).count()>0)
  check('research fact cards fit the 390px viewport',await visibleWithinViewport(researchPage,actualResponse.locator('[data-fact-reference]')))
  check('research page has no 390px horizontal overflow',await researchPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),await researchPage.evaluate(()=>`${document.documentElement.scrollWidth}/${innerWidth}`))
  await actualResponse.scrollIntoViewIfNeeded();await screenshot(researchPage,'research-replay-390')
  await researchContext.close()

  check('no mutation reached the public service',report.public_mutations_forwarded.length===0&&report.mutation_attempts.every(row=>row.path==='/v9/api/v1/conversations')&&report.blocked_requests.length===0,{browser_post_attempts:report.mutation_attempts,locally_satisfied:report.local_navigation_shims,blocked:report.blocked_requests})
  check('no inference-capable request was attempted',report.provider_requests.length===0,report.provider_requests)
  check('public reader raised no page exceptions',report.page_errors.length===0,report.page_errors)
  check('public reader raised no console errors',report.console_errors.length===0,report.console_errors)
  report.status=report.failures.length?'FAIL':'PASS'
}catch(error){report.status='FAIL';report.failures.push({name:'unhandled reader failure',detail:error instanceof Error?error.stack||error.message:String(error)});process.exitCode=1
}finally{
  report.completed_at=new Date().toISOString()
  if(browser)await browser.close()
  await writeFile(reportPath,JSON.stringify(report,null,2)+'\n')
}
console.log(`${report.status}: ${report.checks.filter(row=>row.pass).length}/${report.checks.length} checks; ${report.screenshots.length} screenshots`)
if(report.status!=='PASS')process.exitCode=1
