"""Render actual desktop/mobile capture, synchronized narration, captions and guides.

Requires ffmpeg/ffprobe (libx264, libass), Pillow and previously recorded footage.
No application state or browser content is generated by this compositor.
"""
from pathlib import Path
import json,subprocess,math,re,wave,hashlib,os,sys
from artwork import plate
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'output/demo-video';WORK=OUT/'work';CAP=Path(os.environ.get('CAPTURE_DIR',WORK/'capture'))
MEDIA=ROOT/'apps/web/public/explainers'
def run(args):subprocess.run(args,check=True,stdout=subprocess.DEVNULL)
def probe(path):return json.loads(subprocess.check_output(['ffprobe','-v','error','-show_format','-show_streams','-of','json',str(path)]))
def duration(path):return float(probe(path)['format']['duration'])
def stamp(t,sep='.'):ms=round(t*1000);return f'{ms//3600000:02d}:{ms//60000%60:02d}:{ms//1000%60:02d}{sep}{ms%1000:03d}'
def cues(scene,seconds):
    phrases=re.split(r'(?<=[.!?])\s+',scene['text']);weights=[len(x.split()) for x in phrases];total=sum(weights);start=.4;span=min(seconds-.7,duration(WORK/(scene['id']+'.wav')))
    result=[]
    for phrase,w in zip(phrases,weights):
        end=start+span*w/total;result.append((start,end,phrase));start=end
    return result

def subtitles(rows,path):
    path.write_text('WEBVTT\n\n'+'\n\n'.join(f'{stamp(a)} --> {stamp(b)}\n{text}' for a,b,text in rows)+'\n')
def ass(rows,path):
    # Reserved editorial footer; never overlays app controls or obscures input.
    header='''[Script Info]
ScriptType: v4.00+
PlayResX: 2560
PlayResY: 1440
WrapStyle: 0
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,DejaVu Sans,29,&H00FFF9EC,&H000000FF,&H00252F10,&H00252F10,0,0,0,0,100,100,0,0,1,0,0,2,80,80,21,1
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
'''
    def a(t):return stamp(t)[:-1]
    path.write_text(header+'\n'.join(f'Dialogue: 0,{a(start)},{a(end)},Default,,0,0,0,,{text}' for start,end,text in rows)+'\n')
def concat(paths,out):
    listing=WORK/(out.stem+'-concat.txt');listing.write_text(''.join(f"file '{p.resolve()}'\n" for p in paths))
    run(['ffmpeg','-hide_banner','-loglevel','error','-y','-f','concat','-safe','0','-i',str(listing),'-c','copy','-movflags','+faststart',str(out)])

def main():
    timeline=json.loads((CAP/'timeline.json').read_text());story=json.loads((ROOT/'scripts/demo_video/storyboard.json').read_text())
    if timeline['status']!='PASS':raise RuntimeError('Capture has failures; do not render it as successful.')
    scenes=timeline['scenes'];views={v['name']:v for v in timeline['views']}
    # Story text remains authoritative; timings and interaction evidence are from capture.
    scripts={s['id']:s for s in story};offset=0;allcues=[];segments=[];edl=[]
    for index,record in enumerate(scenes):
        scene={**record,**scripts[record['id']]};sid=scene['id'];target=WORK/f'{index:02d}-{sid}.mp4'
        lengths={name:d['end']-d['start'] for name,d in record['views'].items()}
        secs=math.ceil(max(scene['seconds'],*lengths.values(),duration(WORK/(sid+'.wav'))+.9)*30)/30
        rows=cues(scene,secs);caption=WORK/f'{sid}.ass';ass(rows,caption);background=WORK/f'{sid}-plate.png';plate(scene,index,background)
        edl.append({'id':sid,'title':scene['title'],'start':offset,'duration':secs,'guide':scene['guide'],'recorded':record['views']})
        allcues.extend((a+offset,b+offset,text) for a,b,text in rows);offset+=secs;segments.append(target)
        if target.exists() and abs(duration(target)-secs)<.2:print('Reusing',sid,flush=True);continue
        filters=[]
        for n,name in enumerate(['desktop','mobile']):
            start=record['views'][name]['start'];end=record['views'][name]['end'];size=views[name]['size']
            prefix=f'[{n}:v]trim=start={start:.3f}:end={end:.3f},setpts=PTS-STARTPTS,fps=30,tpad=stop_mode=clone:stop_duration={secs:.3f},trim=duration={secs:.3f}'
            markers=[f for f in views[name]['focus'] if start<=f['time']<=end and f['zoom']>=1.3]
            if name=='desktop' and markers and sid in ['council','assumptions','report','correction']:
                f=markers[0];when=max(0,f['time']-start-.3);until=min(secs-.8,when+11);zin=1.5 if sid in ['report','correction'] else 1.35
                # Ease in/out over 1 second, preserving the action's real position.
                strength=f"if(lt(it,{when:.3f}),0,if(lt(it,{when+1:.3f}),(1-cos((it-{when:.3f})*PI))/2,if(lt(it,{until:.3f}),1,if(lt(it,{until+1:.3f}),(1+cos((it-{until:.3f})*PI))/2,0))))"
                z=f'1+{zin-1:.3f}*({strength})'
                prefix+=f",scale=2560:1680,zoompan=z='{z}':x='max(0,min(iw-iw/zoom,{f['x']*2:.3f}-iw/zoom/2))':y='max(0,min(ih-ih/zoom,{f['y']*2:.3f}-ih/zoom/2))':d=1:s=1280x840:fps=30"
            w,h=(1820,1194) if name=='desktop' else (550,1190)
            filters.append(prefix+f',scale={w}:{h}:flags=lanczos,setsar=1[{name}]')
        filters+=['[2:v][desktop]overlay=x=40:y=114:shortest=1[desk]',f"[desk][mobile]overlay=x=1968:y=116:shortest=1,ass='{caption}',format=yuv420p[v]",f'[3:a]adelay=400:all=1,apad,atrim=duration={secs:.3f},loudnorm=I=-16:TP=-1.5:LRA=11,aresample=48000[a]']
        cmd=['ffmpeg','-hide_banner','-loglevel','error','-y','-threads','2','-i',str(CAP/'desktop.webm'),'-threads','2','-i',str(CAP/'mobile.webm'),'-loop','1','-framerate','30','-i',str(background),'-i',str(WORK/(sid+'.wav')),'-filter_complex_threads','2','-filter_complex',';'.join(filters),'-map','[v]','-map','[a]','-t',f'{secs:.3f}','-c:v','libx264','-preset','fast','-crf','24','-maxrate','2300k','-bufsize','4600k','-threads','4','-c:a','aac','-b:a','128k','-ar','48000','-movflags','+faststart',str(target)]
        print('Rendering',sid,round(secs,2),flush=True);run(cmd)
    mainfile=OUT/'farmtact-desktop-mobile-demo.mp4';concat(segments,mainfile);subtitles(allcues,OUT/'farmtact-desktop-mobile-demo.vtt')
    (OUT/'farmtact-desktop-mobile-demo.srt').write_text('\n\n'.join(f'{i+1}\n{stamp(a,",")} --> {stamp(b,",")}\n{text}' for i,(a,b,text) in enumerate(allcues))+'\n')
    transcripts={}
    for slug in ['observe-decide','council-evidence','act-replan']:
        selected=[(s,e,p) for s,e,p in zip(scenes,edl,segments) if scripts[s['id']]['guide']==slug]
        source=WORK/f'{slug}-captioned-source.mp4';concat([p for s,e,p in selected],source)
        # The master has burned footer captions; guides use selectable WebVTT.
        # Crop only that editorial footer, retaining the entire app and chapter title.
        run(['ffmpeg','-hide_banner','-loglevel','error','-y','-i',str(source),'-vf','crop=2560:1356:0:0,scale=1920:-2','-c:v','libx264','-preset','fast','-crf','23','-threads','4','-c:a','copy','-movflags','+faststart',str(MEDIA/f'{slug}.mp4')])
        local=0;rows=[];transcripts[slug]=[]
        for s,e,p in selected:
            scene=scripts[s['id']];rows.extend((a+local,b+local,text) for a,b,text in cues(scene,e['duration']));transcripts[slug].append({'title':scene['title'],'text':scene['text']});local+=e['duration']
        subtitles(rows,MEDIA/f'{slug}.vtt')
    (MEDIA/'transcripts.json').write_text(json.dumps(transcripts,indent=2)+'\n')
    (OUT/'edit-decision-list.json').write_text(json.dumps(edl,indent=2)+'\n')
    manifest=[]
    for path in [mainfile,*[MEDIA/f'{s}.mp4' for s in transcripts]]:
        p=probe(path);entry={'file':str(path.relative_to(ROOT)),'bytes':path.stat().st_size,'duration_seconds':float(p['format']['duration']),'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'streams':[{'type':s['codec_type'],'codec':s['codec_name'],'width':s.get('width'),'height':s.get('height'),'sample_rate':s.get('sample_rate')} for s in p['streams']]};manifest.append(entry)
        if entry['bytes']>=100_000_000:raise RuntimeError(f'{path.name} must be compressed below 100 MB before committing')
    (OUT/'media-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');print(json.dumps(manifest,indent=2),flush=True)
if __name__=='__main__':main()
