import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { BookOpen, Calculator, Check, ChevronDown, CircleAlert, Hand, Pause, Play, RotateCcw, Send, Sparkles, X } from 'lucide-react'
import { CropArt } from './Visuals'
import { FrozenFactEvidence, QualitativeContextReferences } from './AdvisorEvidence'
import { ADVISORS } from '../lib/game'
import { editionPath, editionStorageKey } from '../lib/edition'
import { researchApi, type ActualConversation, type CouncilConcept, type ResearchActionBody, type ResearchResult, type ResearchSession, type SteeringMode } from '../lib/research'
import './council-research.css'

const concepts:{id:CouncilConcept;name:string;copy:string}[]=[
  {id:'inline',name:'Inline council',copy:'Discussion and consequences share the board.'},
  {id:'sheet',name:'Council sheet',copy:'Expand the conversation while context stays pinned.'},
  {id:'cards',name:'Adviser cards',copy:'Short contributions sit beside referenced objects.'},
]
const refLabel=(ref:string,s?:ResearchSession)=>{const [kind,id]=ref.split(':');if(kind==='bed')return `Bed ${Number(id.split('-')[1])} · ${s?.farm.beds.find(x=>x.id===id)?.name||id}`;if(kind==='order')return id==='research-extra-order'?'Additional lettuce order':`Order ${id}`;if(kind==='crop')return id.replaceAll('_',' ');return `${kind} ${id}`}
const currentResult=(s:ResearchSession)=>s.results.find(r=>r.version===s.input_version)
const sessionStorageKey=()=>editionStorageKey('council-research-session')
const actualStorageKey=(id:string)=>editionStorageKey(`council-research-actual:${id}`)
const farmBatches=(s:ResearchSession)=>(s.farm.batches||[]) as Array<Record<string,unknown>>
const farmRecipes=(s:ResearchSession)=>(s.farm.recipes||[]) as Array<Record<string,unknown>>
const cropForBed=(s:ResearchSession,bedId:string)=>{const batch=farmBatches(s).find(row=>row.bed_id===bedId),recipe=farmRecipes(s).find(row=>row.id===batch?.recipe_id);return String(recipe?.crop_id||'')}

export function CouncilResearch(){
  const [session,setSession]=useState<ResearchSession|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[draft,setDraft]=useState(''),[reportOpen,setReportOpen]=useState(false),[report,setReport]=useState<Awaited<ReturnType<typeof researchApi.report>>|null>(null)
  const [actualAdvisor,setActualAdvisor]=useState('asha'),[actualPrompt,setActualPrompt]=useState('Explain the current same-policy trade-off using this frozen result.'),[actual,setActual]=useState<ActualConversation|null>(null)
  const [actualId,setActualId]=useState('')
  const [sheetExpanded,setSheetExpanded]=useState(true)
  const [reserveStart,setReserveStart]=useState(''),[reserveEnd,setReserveEnd]=useState(''),[policy,setPolicy]=useState<'Lean'|'Balanced'|'Resilient'>('Balanced')
  const transcript=useRef<HTMLDivElement>(null),nearEnd=useRef(true),[unread,setUnread]=useState(false),lastMessages=useRef(0)
  const reportDialog=useRef<HTMLElement>(null),reportTrigger=useRef<HTMLButtonElement>(null)
  const consequenceRef=useRef<HTMLElement>(null)
  const currentSession=useRef<ResearchSession|null>(null)
  const update=useCallback((next:ResearchSession)=>{const current=currentSession.current;if(current&&next.id===current.id&&next.revision<current.revision)return;currentSession.current=next;sessionStorage.setItem(sessionStorageKey(),next.id);setSession(next);setError('');if(next.messages.length>lastMessages.current){if(nearEnd.current)requestAnimationFrame(()=>transcript.current?.scrollTo({top:transcript.current.scrollHeight,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));else setUnread(true)}lastMessages.current=next.messages.length},[])
  const create=useCallback(async(concept:CouncilConcept='sheet',steering:SteeringMode='continuous')=>{setBusy('create');setActual(null);setActualId('');setReserveStart('');setReserveEnd('');setPolicy('Balanced');setUnread(false);lastMessages.current=0;try{update(await researchApi.create(concept,steering))}catch(e){setError(e instanceof Error?e.message:'Study could not start.')}finally{setBusy('')}},[update])
  useEffect(()=>{void (async()=>{setBusy('load');try{const saved=sessionStorage.getItem(sessionStorageKey()),list=await researchApi.list(),id=saved&&list.sessions.some(row=>row.id===saved)?saved:list.sessions[0]?.id;if(id)update(await researchApi.get(id));else await create()}catch{await create()}finally{setBusy('')}})()},[create,update])
  useEffect(()=>{if(!session||!['queued','running','cancellation_requested'].includes(String(session.numerical_calculation_status)))return;const id=session.id;const timer=setInterval(()=>void researchApi.get(id).then(next=>{const current=currentSession.current;if(current?.id===id&&next.id===id&&next.revision>=current.revision)update(next)}).catch(()=>{}),2000);return()=>clearInterval(timer)},[session?.id,session?.revision,session?.numerical_calculation_status,update])
  useEffect(()=>{if(!session||reserveStart)return;const batches=(session.farm.batches||[]) as Array<Record<string,unknown>>,batch=batches.find(row=>row.bed_id==='bed-04');const harvest=String(batch?.harvest_date||session.farm.planning_date||session.farm.cutoff).slice(0,10),start=new Date(`${harvest}T00:00:00Z`);start.setUTCDate(start.getUTCDate()+3);const horizon=new Date(`${String(session.farm.planning_date||session.farm.cutoff).slice(0,10)}T00:00:00Z`);horizon.setUTCDate(horizon.getUTCDate()+Number(session.farm.horizon_days||56)-1);setReserveStart(start.toISOString().slice(0,10));setReserveEnd(horizon.toISOString().slice(0,10))},[session,reserveStart])
  const act=async(body:Omit<ResearchActionBody,'revision'>):Promise<boolean>=>{if(!session||busy)return false;setBusy(body.action);try{update(await researchApi.act(session.id,{...body,revision:session.revision} as ResearchActionBody));return true}catch(e){const err=e as Error&{status?:number};if(err.status===409)try{update(await researchApi.get(session.id))}catch{}setError(err.message);return false}finally{setBusy('')}}
  const configure=(field:'concept'|'steering'|'selection_mode'|'animation',value:string)=>void act({action:'configure',[field]:value} as Omit<ResearchActionBody,'revision'>)
  const toggleRef=(ref:string)=>void act({action:'select',refs:session?.selected_refs.includes(ref)?session.selected_refs.filter(x=>x!==ref):[...(session?.selected_refs||[]),ref]})
  const proposeAndReview=async(body:Omit<ResearchActionBody,'revision'>)=>{if(await act(body))requestAnimationFrame(()=>consequenceRef.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}))}
  const result=session?currentResult(session):undefined,hasPlan=result?.status==='COMPLETED',strategies=result?.calculation?.strategies||[], baseline=session?.results.find(r=>r.status==='COMPLETED'), selectedStrategy=strategies.find(x=>x.name===policy)
  const openReport=async()=>{setReportOpen(true);if(!report)try{setReport(await researchApi.report())}catch(e){setError(e instanceof Error?e.message:'Research report unavailable.')}}
  useEffect(()=>{if(!session)return;const stored=sessionStorage.getItem(actualStorageKey(session.id));if(stored){setActualId(stored);void researchApi.getActual(stored).then(setActual).catch(()=>sessionStorage.removeItem(actualStorageKey(session.id)))}else{setActualId('');setActual(null)}},[session?.id])
  useEffect(()=>{if(!actualId||!['QUEUED','RUNNING'].includes(String(actual?.last_request_status).toUpperCase()))return;const timer=setInterval(()=>void researchApi.getActual(actualId).then(setActual).catch(e=>setError(e instanceof Error?e.message:'Actual response status unavailable.')),1500);return()=>clearInterval(timer)},[actualId,actual?.last_request_status])
  useEffect(()=>{if(!reportOpen)return;const previous=document.activeElement as HTMLElement|null;requestAnimationFrame(()=>reportDialog.current?.querySelector<HTMLElement>('button,a,summary')?.focus());const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setReportOpen(false);return}if(event.key!=='Tab'||!reportDialog.current)return;const focusable=[...reportDialog.current.querySelectorAll<HTMLElement>('button,a[href],summary')].filter(x=>!x.hasAttribute('disabled'));if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[reportOpen])
  if(!session)return <section className="council-research council-loading" aria-live="polite"><Sparkles/> <h1>Opening the council study…</h1>{error&&<button onClick={()=>void create()}>Try again</button>}</section>
  const proposal=session.proposal,extraOrder=session.farm.orders.find(row=>row.id==='research-extra-order'),extraUnconfirmed=session.inputs.unconfirmed_order_ids.includes('research-extra-order'),proposalBed=proposal?.bed_id?session.farm.beds.find(b=>b.id===proposal.bed_id):undefined,proposalBatch=proposal?.bed_id?farmBatches(session).find(b=>b.bed_id===proposal.bed_id):undefined,proposalOrder=proposal?.order_id?session.farm.orders.find(o=>o.id===proposal.order_id):undefined
  return <section className={`council-research concept-${session.concept} animation-${session.animation} ${session.concept==='sheet'&&!sheetExpanded?'sheet-collapsed':''}`}>
    <header className="council-hero"><div><p className="kicker">Playable council · synthetic farm</p><h1>Talk through a farm decision.</h1><p>Your words propose changes; the local numerical tool shows their consequences.</p></div><button ref={reportTrigger} className="council-report-button" onClick={()=>void openReport()}><BookOpen/> Research &amp; evidence</button></header>
    {error&&<div className="council-error" role="alert"><CircleAlert/><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss error"><X/></button></div>}
    <section className="guided-next" aria-label="Next council action"><div><p className="kicker">Start here</p><h2>{result?.status==='QUEUED'?'Calculating the three plans…':!result&&session.results.length?'Recalculate the changed version':!hasPlan?'Ask the council for a plan':!session.milestones.reserve_bed?'Now protect Bed 4':!session.milestones.order_status?'Test the additional order':!session.milestones.challenge?'Challenge an assumption':!session.milestones.chosen?'Review and choose':'Study complete'}</h2><p>{result?.status==='QUEUED'?'Farm time does not advance while the local numerical worker runs.':!result&&session.results.length?'Your edit is frozen in a new version. Run the local numerical tool to update all three options.':!hasPlan?'The local planning tool will calculate three options from this frozen synthetic farm. No AI call is needed.':!session.milestones.reserve_bed?'Reserve it for a date range, then recalculate to see the consequence.':!session.milestones.order_status?'Mark it unconfirmed so booked demand changes visibly.':!session.milestones.challenge?'Ask why outdoor rain should affect a sheltered crop.':!session.milestones.chosen?'Compare the same policy and choose a feasible simulation.':'You can reset or compare another layout.'}</p></div>{!result?<button onClick={()=>void act({action:'run'})} disabled={!!busy}><Calculator/> {session.results.length?'Recalculate changed inputs':'Ask council for a plan'}</button>:hasPlan&&!session.milestones.reserve_bed?<button onClick={()=>void proposeAndReview({action:'propose',operation:'reserve_bed',bed_id:'bed-04',start_date:reserveStart,end_date:reserveEnd})}>Reserve Bed 4</button>:hasPlan&&!session.milestones.order_status?<button onClick={()=>void proposeAndReview({action:'propose',operation:'order_status',order_id:'research-extra-order',confirmed:false})}>Mark order unconfirmed</button>:hasPlan&&!session.milestones.challenge?<button onClick={()=>void act({action:'challenge',text:'This crop is indoors; explain why outdoor rainfall affects its yield.'})}>Challenge rainfall assumption</button>:null}</section>
    <details className="layout-lab"><summary>Compare research layouts and pacing</summary><div className="study-controls" aria-label="Study presentation controls">
      <label>Layout<select value={session.concept} onChange={e=>configure('concept',e.target.value)}>{concepts.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><small>{concepts.find(c=>c.id===session.concept)?.copy}</small></label>
      <label>Participation<select value={session.steering} onChange={e=>configure('steering',e.target.value)}><option value="continuous">Continuous steering</option><option value="checkpoints">Intervention checkpoints</option></select><small>{session.steering==='continuous'?'Speak between any completed turns.':'Advance one contribution at a time.'}</small></label>
      <label>Context<select value={session.selection_mode} onChange={e=>configure('selection_mode',e.target.value)}><option value="chips">Removable chips</option><option value="cards">Context cards</option></select></label>
      <label>Changes<select value={session.animation} onChange={e=>configure('animation',e.target.value)}><option value="static">Static before / after</option><option value="transition">Restrained transition</option></select></label>
    </div><button className="reset-study" disabled={!!busy} onClick={()=>void create(session.concept,session.steering)}><RotateCcw/> Start a fresh isolated study</button></details>
    <ol className="research-task" aria-label="Council study task">
      {['calculated','reserve_bed','order_status','challenge','chosen'].map((key,i)=><li className={session.milestones[key]?'done':''} key={key}>{session.milestones[key]?<Check/>:<span>{i+1}</span>}{['Ask for a plan','Reserve Bed 4','Mark the additional order unconfirmed','Challenge one assumption','Choose a simulated version'][i]}</li>)}
    </ol>
    <div className="council-workspace">
      <section className="context-board" aria-label="Selected farm context"><header><div><p className="kicker">Frozen version {session.input_version}</p><h2>Farm context</h2></div><span>{session.selected_refs.length} selected</span></header>
        <div className="mini-farm" role="group" aria-label="Sixteen selectable beds">{session.farm.beds.map((bed,i)=>{const crop=cropForBed(session,bed.id);return <button key={bed.id} className={session.selected_refs.includes(`bed:${bed.id}`)?'selected':''} onClick={()=>toggleRef(`bed:${bed.id}`)} aria-pressed={session.selected_refs.includes(`bed:${bed.id}`)} aria-label={`Select Bed ${i+1}, ${bed.name}, ${crop.replaceAll('_',' ')||'open'}`}><CropArt cropId={crop||undefined} stage={crop?'growing':'empty'} compact/><b>{i+1}</b><small>{bed.name}</small></button>})}</div>
        <div className="context-objects"><button className={session.selected_refs.includes('order:research-extra-order')?'selected':''} onClick={()=>toggleRef('order:research-extra-order')} aria-pressed={session.selected_refs.includes('order:research-extra-order')}><b>Additional lettuce order</b><span>{extraOrder?.quantity_kg} kg · due {extraOrder?.due_date ? new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short'}).format(new Date(`${extraOrder.due_date}T00:00:00Z`)) : 'unknown'} · {extraUnconfirmed?'unconfirmed':'confirmed'}</span></button><button className={session.selected_refs.includes('crop:lettuce')?'selected':''} onClick={()=>toggleRef('crop:lettuce')} aria-pressed={session.selected_refs.includes('crop:lettuce')}><CropArt cropId="lettuce" stage="ready" compact/><span><b>Lettuce</b><small>Selected crop context</small></span></button></div>
        {!!session.selected_refs.length&&<div className={`selected-context mode-${session.selection_mode}`} aria-label="Conversation context">{session.selected_refs.map(ref=><button key={ref} onClick={()=>toggleRef(ref)} aria-label={`Remove ${refLabel(ref,session)}`}>{refLabel(ref,session)} <X/></button>)}</div>}
        <div className="quick-actions"><button onClick={()=>void proposeAndReview({action:'propose',operation:'reserve_bed',bed_id:'bed-04',start_date:reserveStart,end_date:reserveEnd})}>Reserve Bed 4</button><button onClick={()=>void proposeAndReview({action:'propose',operation:'order_status',order_id:'research-extra-order',confirmed:false})}>Mark order unconfirmed</button><button onClick={()=>void act({action:'challenge',text:'This crop is indoors; explain why outdoor rainfall affects its yield.'})}>Challenge rainfall assumption</button></div>
      </section>
      <section className="council-dialogue" aria-label="Council discussion"><header><div><p className="kicker">Scripted research dialogue</p><h2>Farm council</h2></div><span className="mode-label">No AI inference</span>{session.concept==='sheet'&&<button className="sheet-toggle" onClick={()=>setSheetExpanded(value=>!value)} aria-expanded={sheetExpanded}>{sheetExpanded?'Collapse':'Expand'}</button>}</header>
        {(!!session.selected_refs.length||proposal?.bed_id||proposal?.order_id)&&<div className="composer-context" aria-label="Pinned context while composing"><b>Talking about</b>{session.selected_refs.map(ref=><button key={ref} onClick={()=>toggleRef(ref)}>{refLabel(ref,session)} <X/></button>)}{proposal?.bed_id&&!session.selected_refs.includes(`bed:${proposal.bed_id}`)&&<span>{refLabel(`bed:${proposal.bed_id}`,session)} · proposed</span>}{proposal?.order_id&&!session.selected_refs.includes(`order:${proposal.order_id}`)&&<span>{refLabel(`order:${proposal.order_id}`,session)} · proposed</span>}</div>}
        <div className="sheet-expandable">
        <details className="council-roster"><summary>See the seven council roles</summary><div className="advisor-line" aria-label="Council roles">{ADVISORS.map(a=><span key={a.id} title={a.role}><img src={`art/advisors/${a.id}.svg`} alt=""/><small>{a.role}</small></span>)}</div></details>
        <div className="research-transcript" ref={transcript} onScroll={e=>{const n=e.currentTarget;nearEnd.current=n.scrollHeight-n.scrollTop-n.clientHeight<48;if(nearEnd.current)setUnread(false)}}>{session.messages.map(m=><article key={m.id} className={`research-message kind-${m.kind}`}><header><b>{m.speaker}</b><small>v{m.input_version}</small></header>{session.concept==='cards'&&m.refs?.[0]&&<div className="message-object-preview">Context · {refLabel(m.refs[0],session)}</div>}<p>{m.text}</p>{m.refs?.length>0&&<div className="message-refs">{m.refs.map(r=><button key={r} onClick={()=>r.startsWith('evidence:')?void openReport():toggleRef(r)}>{refLabel(r,session)}</button>)}</div>}</article>)}</div>
        {unread&&<button className="new-messages" onClick={()=>{transcript.current?.scrollTo({top:transcript.current.scrollHeight});setUnread(false)}}>New council update <ChevronDown/></button>}
        <form className="research-composer" aria-busy={busy==='say'} onSubmit={async e=>{e.preventDefault();const text=draft.trim();if(text&&await act({action:'say',text,advisor:ADVISORS.find(a=>a.id===actualAdvisor)?.role||'Planner'}))setDraft(current=>current.trim()===text?'':current)}}><label htmlFor="research-message">Tell the council what matters</label><div><select aria-label="Address specialist" value={actualAdvisor} onChange={e=>setActualAdvisor(e.target.value)}>{ADVISORS.map(a=><option value={a.id} key={a.id}>{a.role}</option>)}</select><input id="research-message" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={1000} placeholder="Ask, challenge, constrain or compare…"/><button disabled={!draft.trim()||!!busy} aria-label="Send to scripted council"><Send/></button></div>{busy==='say'&&<span className="composer-status" role="status">Sending your message; you can keep typing the next one.</span>}<small>Voice typing: use your device keyboard microphone if available. Text is interpreted into a proposal before any calculation.</small></form>
        {!!session.pending_turns.length&&<div className="turn-controls"><span>{session.pending_turns.length} relevant contributions waiting</span><button onClick={()=>void act({action:'next'})}><Play/> Next contribution</button><button onClick={()=>void act({action:'stop'})}><Pause/> Stop discussion</button></div>}
        </div>
      </section>
      <section ref={consequenceRef} className="consequence-panel" aria-label="Planning consequences"><header><div><p className="kicker">Local numerical tool</p><h2>Review the consequence</h2></div><span>Version {session.input_version}</span></header>
        {proposal&&<div className="proposal-card"><h3>Proposed edit · review before applying</h3>{proposal.operation==='reserve_bed'?<><label>Start<input type="date" value={reserveStart} onChange={e=>setReserveStart(e.target.value)}/></label><label>End<input type="date" value={reserveEnd} onChange={e=>setReserveEnd(e.target.value)}/></label><p>{proposalBed?.name||proposal.bed_id} is Bed {Number(proposal.bed_id?.split('-')[1])}. Existing {proposalBatch?.crop_id?String(proposalBatch.crop_id).replaceAll('_',' '):'bed'} occupancy and recorded harvest {String(proposalBatch?.harvest_date||'unknown')} remain protected.</p></>:<p>{proposal.operation==='order_status'?`${proposalOrder?.id||proposal.order_id} becomes ${proposal.confirmed?'confirmed and contributes to booked commitments':'unconfirmed; it stays visible but leaves booked demand'}.`:`Labour allowance: ${proposal.labour_percent}%`}</p>}<div><button onClick={()=>void act({action:'apply',start_date:reserveStart,end_date:reserveEnd})}><Check/> Apply to new version</button><button onClick={()=>void act({action:'discard'})}>Discard</button></div></div>}
        {session.challenge&&<div className={`challenge-card status-${session.challenge.status}`}><h3>Assumption challenge · {session.challenge.status}</h3><p>{session.challenge.text}</p><details><summary>Evidence for this assumption</summary><p>Bed 4 system: <b>{session.farm.beds.find(b=>b.id==='bed-04')?.system||'not declared'}</b>. Lettuce recipe system: <b>{String(farmRecipes(session).find(r=>r.crop_id==='lettuce')?.system||'not declared')}</b>; validation: <b>{String(farmRecipes(session).find(r=>r.crop_id==='lettuce')?.validation_status||'not declared')}</b>.</p><p>The research numerical inputs include reservations, order status, and labour. Outdoor weather is context and is not a yield input.</p></details><div><button onClick={()=>void openReport()}>Open research sources</button><button onClick={()=>void act({action:'resolve',resolution:'corrected'})}>Correct assumption</button><button onClick={()=>void act({action:'resolve',resolution:'unresolved'})}>Leave unresolved</button><button onClick={()=>void act({action:'resolve',resolution:'reject'})}>Reject recommendation</button></div></div>}
        {session.results.length>0&&<button className="calculate-button" disabled={!!proposal||['queued','running','cancellation_requested'].includes(String(session.numerical_calculation_status))||!!busy||result?.status==='COMPLETED'} onClick={()=>void act({action:'run'})}><Calculator/> {['queued','running','cancellation_requested'].includes(String(session.numerical_calculation_status))?'Calculating frozen inputs…':result?.status==='COMPLETED'?'This version is calculated':'Recalculate changed inputs'}</button>}
        {result&&<div className="research-calculation-controls" aria-label="Numerical calculation controls"><span><b>Numerical calculation</b><small>{String(session.numerical_calculation_status||result.status).replaceAll('_',' ')}</small></span>{['queued','running','cancellation_requested'].includes(String(session.numerical_calculation_status))&&<button disabled={!!busy||session.numerical_calculation_status==='cancellation_requested'} onClick={()=>void act({action:'cancel_calculation'})}><X/> {session.numerical_calculation_status==='cancellation_requested'?'Cancellation requested':'Cancel calculation'}</button>}{['failed','cancelled'].includes(String(session.numerical_calculation_status))&&<button disabled={!!busy} onClick={()=>void act({action:'retry_calculation'})}><RotateCcw/> Retry saved calculation</button>}<p>Calculation controls affect only this local numerical job. “Stop discussion” controls the scripted dialogue separately. Failed and cancelled results remain in the version history.</p></div>}
        {result?.error&&<p role="alert">{result.error}</p>}
        {!!result&&!!strategies.length&&<><div className="policy-tabs">{strategies.map(s=><button key={s.name} className={policy===s.name?'selected':''} onClick={()=>setPolicy(s.name)}>{s.name}</button>)}</div>{selectedStrategy&&<StrategyResult strategy={selectedStrategy} baseline={baseline} current={result}/>}<button className="choose-button" disabled={selectedStrategy?.status!=='FEASIBLE'||!!selectedStrategy?.violations.length||session.challenge?.status==='unresolved'||session.challenge?.status==='reject'||!!proposal||result.version!==session.input_version} onClick={()=>void act({action:'choose',policy,result_version:result.version})}><Hand/> Choose this simulated version</button></>}
        {session.results.filter(row=>row.version!==session.input_version).length>0&&<details className="archived-results"><summary>Earlier frozen results ({session.results.filter(row=>row.version!==session.input_version).length})</summary>{session.results.filter(row=>row.version!==session.input_version).map(row=><article key={row.version}><b>Version {row.version}</b><span>{row.status}</span><small>{row.inputs.reservations.length} reservations · {row.inputs.unconfirmed_order_ids.length} unconfirmed orders · {row.inputs.labour_percent}% labour</small>{row.calculation?.strategies.map(strategy=><details key={strategy.name}><summary>{strategy.name} · {strategy.status}</summary><p>{strategy.metrics.shortfall_kg} kg shortfall · {strategy.metrics.waste_kg} kg waste · SGD {strategy.metrics.margin_sgd} margin · {strategy.violations.length} violations</p></details>)}</article>)}</details>}
        {session.chosen&&<p className="chosen-note"><Check/> {session.chosen.policy} v{session.chosen.version} chosen for this study. No operational commitment was made.</p>}
        {result?.status==='COMPLETED'&&<details className="actual-advisor"><summary>Optional actual DeepSeek interpretation</summary><p>This explicit action sends one question about frozen version {session.input_version}. It does not run the whole council or change inputs.</p><label>Specialist<select value={actualAdvisor} onChange={e=>setActualAdvisor(e.target.value)}>{ADVISORS.map(a=><option value={a.id} key={a.id}>{a.name} · {a.role}</option>)}</select></label><label>Question<textarea value={actualPrompt} maxLength={1000} onChange={e=>setActualPrompt(e.target.value)}/></label><button disabled={!actualPrompt.trim()||busy==='actual'||['QUEUED','RUNNING'].includes(String(actual?.last_request_status).toUpperCase())} onClick={async()=>{setBusy('actual');try{const created=await researchApi.createActual(session.id,session.input_version,actualAdvisor);setActualId(created.id);sessionStorage.setItem(actualStorageKey(session.id),created.id);await researchApi.sendActual(created.id,actualPrompt.trim());setActual(await researchApi.getActual(created.id))}catch(e){setError(e instanceof Error?e.message:'DeepSeek interpretation unavailable.')}finally{setBusy('')}}}>Ask DeepSeek about frozen result</button>{actual&&<div className="actual-response"><b>Actual provider conversation · separate from scripted study</b><p>Status: <strong>{actual.last_request_status||'recorded'}</strong></p><p>Frozen reference: {typeof actual.snapshot_ref==='string'?actual.snapshot_ref:`${actual.snapshot_ref?.kind||'research'} · ${actual.snapshot_ref?.id||session.id} · v${actual.snapshot_ref?.version||session.input_version} · ${actual.snapshot_ref?.hash?.slice(0,10)||'hash recorded'}`}</p>{actual.messages.map(m=>{
          const unsupported=/unsupported|blocked|rejected|invalid/.test(`${m.validation_status||''} ${m.evidence_status||''}`.toLowerCase())
          return <article className={unsupported?'unsupported-actual':''} style={{minWidth:0,overflowWrap:'anywhere'}} key={m.id}>
            <p><strong>{m.speaker_name||m.speaker}:</strong> {m.content}</p>
            <small>Validation: {m.validation_status||'not reported'} · interpretation: {m.interpretation_status||'not reported'}</small>
            {unsupported&&<p role="alert">This response is unsupported and cannot authorize a change.</p>}
            <FrozenFactEvidence factRefs={m.fact_refs} renderedFacts={m.rendered_facts} catalogue={actual.typed_facts} validationStatus={m.validation_status} evidenceStatus={m.evidence_status}/>
            <QualitativeContextReferences refs={m.tool_refs} toolResults={actual.tool_results}/>
            {!!m.evidence_refs?.length&&<small>Evidence citations: {m.evidence_refs.join(', ')} · citation presence does not verify the interpretation.</small>}
          </article>
        })}<button onClick={()=>void researchApi.getActual(actual.id).then(setActual).catch(e=>setError(e instanceof Error?e.message:'Refresh failed.'))}>Refresh recorded status</button></div>}</details>}
      </section>
    </div>
    {reportOpen&&<div className="research-report-layer" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setReportOpen(false)}}><section ref={reportDialog} role="dialog" aria-modal="true" aria-label="Research and evidence"><header><h2>{report?.title||'Research and evidence'}</h2><button onClick={()=>setReportOpen(false)} aria-label="Close research"><X/></button></header>{!report?<p>Loading curated research…</p>:<><div className="research-sources">{report.sources.map(s=><a href={s.url} target="_blank" rel="noreferrer" key={s.url}>{s.title}</a>)}</div>{report.screenshots.length>0&&<div className="research-screenshots">{report.screenshots.map(s=><figure key={s.url}><img src={editionPath(s.url)} alt={s.title}/><figcaption>{s.title}</figcaption></figure>)}</div>}{report.documents.map(d=><details key={d.title}><summary>{d.title}</summary><pre>{d.markdown}</pre></details>)}</>}</section></div>}
  </section>
}

function StrategyResult({strategy,baseline,current}:{strategy:{name:string;status:string;metrics:Record<string,unknown>;violations:Array<Record<string,unknown>>;allocations?:Array<Record<string,unknown>>};baseline?:ResearchResult;current:ResearchResult}){const old=baseline?.calculation?.strategies.find(s=>s.name===strategy.name),metrics=[['fill_rate','Delivery covered','%'],['shortfall_kg','Delivery shortfall','kg'],['waste_kg','Waste','kg'],['labour_hours','Labour','hours'],['cost_sgd','Cost','SGD'],['margin_sgd','Margin','SGD']] as const;return <div className="strategy-result"><header><b>{strategy.name}</b><span>{strategy.status}</span></header><div className="delta-grid">{metrics.map(([key,label,unit])=>{const factor=key==='fill_rate'?100:1,value=Number(strategy.metrics[key]||0)*factor,before=Number(old?.metrics[key]||0)*factor,delta=value-before;return <div key={key}><small>{label}</small><b>{value.toFixed(1)} {unit}</b><span>{baseline&&baseline.version!==current.version?`${delta>=0?'+':''}${delta.toFixed(1)} ${unit} vs v${baseline.version}`:'Baseline'}</span></div>})}</div>{(current.inputs.reservations.length>0||!!strategy.allocations?.length)&&<details><summary>Allocation and reservation timeline</summary>{current.inputs.reservations.map(row=><p className="reservation-window" key={row.bed_id}><b>{row.bed_id} reserved</b> {row.start_date} → {row.end_date}</p>)}<div className="allocation-timeline">{strategy.allocations?.slice(0,64).map((row,i)=><p key={String(row.id||`${row.bed_id}-${i}`)}><b>{String(row.bed_id)}</b><span>{String(row.crop_id).replaceAll('_',' ')} · {row.executed?'existing':'planned'}</span><time>{String(row.transplant_date)} → {String(row.harvest_date)}</time><strong>{Number(row.expected_kg||0).toFixed(1)} kg</strong></p>)}</div></details>}{strategy.violations.length?<details open><summary>{strategy.violations.length} constraint violations</summary><pre>{JSON.stringify(strategy.violations,null,2)}</pre></details>:<p className="feasible-note"><Check/> No constraint violations reported.</p>}</div>}
