import type { DatasetKey, ExplorerDetail, ExplorerRecord } from '../lib/explorer'

const number=(value:unknown)=>Number(value||0)
const format=(value:number)=>value.toLocaleString('en-SG',{maximumFractionDigits:3})

/** Plain-language reference rules beside actual records, never learned coefficients. */
export function GenerationGuide({detail,onOpen}:{detail:ExplorerDetail;onOpen:(dataset:DatasetKey,id:string)=>void}) {
  const records=detail.records
  const bed=records.beds[0], recipe=records.recipes[0], batch=records.batches[0]
  const history=records.history.filter(row=>row.crop_id===recipe?.crop_id).at(-1)
  const order=records.orders[0], inventory=records.inventory[0], resource=records.resources[0]
  const settings=detail.generator_settings
  const expectedHistory=settings?(27+0*2+(11%4)*2*settings.pattern_amplitude)*settings.history_multiplier*(1+settings.history_trend*11/11):null
  const cards:Array<{dataset:DatasetKey;title:string;plain:string;formula:string;example:string;record?:ExplorerRecord}>=[
    {dataset:'beds',title:'Growing beds',plain:'The reference starts with sixteen sheltered beds, each 20 square metres. Bed names use four rows of four.',formula:'bed(i): area = 20 m²; row = floor(i / 4); column = (i mod 4) + 1',example:bed?`${String(bed.name)} has ${bed.area_m2} m². The selected dataset contains ${records.beds.length} beds.`:'This snapshot contains no beds.',record:bed},
    {dataset:'recipes',title:'Crop recipes',plain:'Caixin, pak choi, kailan and lettuce each have declared nursery time, grow time, density, marketable yield, labour and input cost. These are biological assumptions for demonstrations.',formula:'cycle days = nursery days + grow days; future yield = bed area × marketable kg/m²',example:recipe?`${recipe.crop_id}: ${recipe.nursery_days} + ${recipe.grow_days} = ${number(recipe.nursery_days)+number(recipe.grow_days)} days. At ${recipe.marketable_kg_per_m2} kg/m², a ${bed?.area_m2||20} m² bed implies ${format(number(bed?.area_m2||20)*number(recipe.marketable_kg_per_m2))} kg.`:'No declared recipe in this snapshot.',record:recipe},
    {dataset:'batches',title:'Existing batches',plain:'Eight reference batches occupy the first eight beds. Each crop has two batches; the second set harvests fourteen days after the first. Scenario delays and yields are applied after generation.',formula:'harvest(i) = planning date + floor(i / 4) × 14 + 6 days; transplant = harvest − grow days; sow = transplant − nursery days',example:batch?`${batch.id}: sow ${batch.sow_date}, transplant ${batch.transplant_date}, harvest ${batch.harvest_date}; ${batch.expected_marketable_kg} kg scheduled. Bed ${batch.bed_id} links to recipe ${batch.recipe_id}.`:'No existing batches in this snapshot.',record:batch},
    {dataset:'history',title:'Historical demand',plain:'The reference generates twelve weekly values per crop. The repeating four-week pattern is an assumption, not measured seasonality. Trend is the total change over the observed period.',formula:'(27 + crop_index × 2 + (week_index mod 4) × 2 × amplitude) × multiplier × (1 + trend × week_index / 11)',example:history?`${settings?`For crop index 0, week 11: (27 + 6 × ${settings.pattern_amplitude}) × ${settings.history_multiplier} × (1 + ${settings.history_trend}) = ${format(expectedHistory!)} kg before branch controls. `:''}The selected record for ${history.crop_id} on ${history.week} is ${history.ordered_kg} kg.`:'No historical demand records; the forecast relies on booked orders.',record:history},
    {dataset:'orders',title:'Booked orders and prices',plain:'Four crops receive one fictional booked order per future week, for eight weeks. Volume and selling-price multipliers are independent. The generator books orders seven days before cutoff.',formula:'quantity(c,w) = (22 + (c mod 2) × 4 + (w mod 3) × 2) × orders_multiplier; price(c) = (6 + c) × price_multiplier',example:order?`${order.id}: ${order.quantity_kg} kg at SGD ${order.price_sgd_per_kg}/kg, due ${order.due_date}. ${settings?`The first generated order is 22 × ${settings.orders_multiplier} = ${format(22*settings.orders_multiplier)} kg at 6 × ${settings.price_multiplier} = SGD ${format(6*settings.price_multiplier)}/kg before branch controls.`:''}`:'No booked orders in this snapshot.',record:order},
    {dataset:'inventory',title:'Opening inventory',plain:'The reference has one 5 kg caixin lot harvested the day before planning. Its expiry is two days after planning. The simulator tracks expiry and stock by lot.',formula:'opening-caixin: 5 kg; harvested = planning date − 1 day; expires = planning date + 2 days',example:inventory?`${inventory.id}: ${inventory.quantity_kg} kg of ${inventory.crop_id}, harvested ${inventory.harvested_date}, expires ${inventory.expires_date}.`:'No opening inventory in this snapshot.',record:inventory},
    {dataset:'resources',title:'Available resources',plain:'The reference supplies 2,560 simultaneous nursery sites, 32 labour hours per week and SGD 2,200 for the whole planning horizon. Branch controls multiply labour and cash.',formula:'nursery = 2,560 sites; weekly labour = 32 hours; horizon cash = SGD 2,200',example:resource?`Selected capacity: ${resource.nursery_sites} nursery sites, ${resource.labour_hours_per_week} hours/week and SGD ${resource.cash_sgd}.`:'No resource record available.',record:resource},
  ]
  return <section className="explorer-card explorer-wide generation-guide">
    <p className="kicker">How data is made</p><h2>Rules you can inspect</h2>
    <p>{settings?'These deterministic reference rules use no randomness or trained model. Every example opens the actual selected record.':'This is an imported farm snapshot. Reference-generator rules below explain the playground; they do not establish how imported values were collected. Example buttons open the imported records.'}</p>
    {detail.kind==='scenario'&&<p className="explorer-note">Scenario controls can change records after generation. The examples distinguish the generator calculation from the selected branch value.</p>}
    <div className="explorer-grid">{cards.map(card=><article key={card.dataset} style={{minWidth:0,padding:'12px 0'}}><h3>{card.title}</h3><p>{card.plain}</p><details><summary style={{minHeight:44,cursor:'pointer',padding:'10px 0'}}>Formula and worked example</summary><code style={{display:'block',whiteSpace:'normal',overflowWrap:'anywhere',padding:'10px 0'}}>{card.formula}</code><p>{card.example}</p></details>{card.record&&<button className="button button--cream" style={{minHeight:44,maxWidth:'100%',overflowWrap:'anywhere'}} onClick={()=>onOpen(card.dataset,card.record!.id)}>Inspect {card.dataset} example</button>}</article>)}</div>
    <details><summary style={{minHeight:44,cursor:'pointer',padding:'10px 0'}}>How the forecast is calculated</summary><p>EWMA is a statistical baseline. Start with the first historical demand value available at the cutoff, then give each later value weight α and the previous estimate weight 1−α.</p><code style={{overflowWrap:'anywhere'}}>estimate = α × next historical value + (1 − α) × previous estimate</code><p>At α {detail.forecast_settings.alpha}, the first available value initializes the estimate. Confirmed weekly orders are kept in full; only max(0, estimate − booked weekly demand) is added at week end. Forecast records list the history and order IDs used.</p><p>CP-SAT is an optimiser that chooses schedules under the declared constraints. Neither EWMA nor CP-SAT is a model trained on real farm outcomes.</p></details>
  </section>
}
