import { useEffect, useRef, useState } from 'react'
import { api, requestBlob } from '../lib/api'
import { farmerWorkflowApi, planningApi, rememberedPlanningSession, type PlanningSession } from '../lib/planning'
import { DEFAULT_FORECAST, DEFAULT_GENERATOR, type DatasetKey, type ExplorerDetail, type ExplorerSnapshotSummary, type PublicContext, type ExplorerRecord } from '../lib/explorer'
import type { Conversation, Quest, Scenario, ScenarioComparison, ScenarioControls } from '../lib/game'
import { ToolCard, RecordFacts, type ToolAction } from './ToolCard'
import { ExplorerChart } from './ExplorerChart'
import { staticToolCard, cardString, cardRevision, cardReferences, toolCardActions } from '../lib/cardProjection'
import { editionStorageKey } from '../lib/edition'
const recordDate=(r:ExplorerRecord)=>String(r.date||r.due_date||r.sow_date||r.harvest_date||r.week_start||'')
const numeric=(v:unknown)=>v!==null&&v!==''&&v!==undefined&&Number.isFinite(Number(v))
const controls:ScenarioControls={delay_days:0,yield_percent:100,demand_percent:100,labour_percent:100,cash_percent:100}
const menu=['Scenarios & quests','Data Explorer','Dataset generation','Waste Rescue','Research & reviews']
const datasets:DatasetKey[]=['beds','recipes','batches','history','orders','inventory','resources','forecast','allocations','ledger','weekly']
const readDraft=()=>{try{return JSON.parse(localStorage.getItem(editionStorageKey('experiment-draft'))||'{}')}catch{return {}}}
export default function IntegratedExperiments({onClose,onResearch,initialView}:{onClose:()=>void;onResearch?:()=>void;initialView?:'rescue'}) {
 const [view,setView]=useState(initialView==='rescue'?'rescue':'index'),[index,setIndex]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [scenarios,setScenarios]=useState<Scenario[]>([]),[quests,setQuests]=useState<Quest[]>([]),[scenario,setScenario]=useState<Scenario|null>(null)
 const [conversations,setConversations]=useState<Conversation[]>([]),[sourceConversation,setSourceConversation]=useState('')
 const [draft,setDraft]=useState<ScenarioControls>(()=>({...controls,...readDraft().controls})),[name,setName]=useState(()=>readDraft().name||'My frozen experiment'),[quest,setQuest]=useState(''),[parent,setParent]=useState(''),[snapshotId,setSnapshotId]=useState('')
 const [snapshots,setSnapshots]=useState<ExplorerSnapshotSummary[]>([]),[detail,setDetail]=useState<ExplorerDetail|null>(null),[dataset,setDataset]=useState<DatasetKey>('history'),[filter,setFilter]=useState(''),[sort,setSort]=useState('id'),[page,setPage]=useState(0),[policy,setPolicy]=useState('Balanced')
 const [generator,setGenerator]=useState(()=>({...DEFAULT_GENERATOR,...readDraft().generator})),[forecast,setForecast]=useState(()=>({...DEFAULT_FORECAST,...readDraft().forecast}))
 const [publicContext,setPublicContext]=useState<PublicContext|null>(null),[publicDataset,setPublicDataset]=useState<keyof PublicContext['datasets']>('weather_observations'),[publicSource,setPublicSource]=useState('')
 const [comparison,setComparison]=useState<unknown>(null),[comparisonContext,setComparisonContext]=useState(''),[compareId,setCompareId]=useState(''),[session,setSession]=useState<PlanningSession|null>(null),[rescue,setRescue]=useState<unknown>(null)
 const [crop,setCrop]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[descending,setDescending]=useState(false),[format,setFormat]=useState('csv'),[selectedRecord,setSelectedRecord]=useState('')
 const trail=useRef<Array<{view:string;index:number;scroll:number;focus:HTMLElement|null}>>([])
 const [sale,setSale]=useState('3'),[price,setPrice]=useState('1'),[cost,setCost]=useState('0.2'),[lot,setLot]=useState(''),[rescueStrategy,setRescueStrategy]=useState('')
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Request interrupted. Draft retained.')}finally{setBusy(false)}}
 useEffect(()=>{try{localStorage.setItem(editionStorageKey('experiment-draft'),JSON.stringify({controls:draft,name,generator,forecast}))}catch{}},[draft,name,generator,forecast])
 useEffect(()=>{void act(async()=>{const [s,q,x,p,c]=await Promise.all([api.scenarios(),api.quests(),api.explorerSnapshots(),planningApi.list(),api.conversations()]);setScenarios(s);setQuests(q);setSnapshots(x);setConversations(c);setSession(p.sessions.find(s=>s.id===rememberedPlanningSession()&&s.workflow)||p.sessions.find(s=>s.workflow===true)||null)})},[])
 const open=(v:string)=>{trail.current.push({view,index,scroll:window.scrollY,focus:document.activeElement as HTMLElement});setView(v);setIndex(0);setError('')}
 const back=()=>{const origin=trail.current.pop();if(!origin){onClose();return}setView(origin.view);setIndex(origin.index);setError('');requestAnimationFrame(()=>{(origin.focus?.isConnected?origin.focus:document.querySelector<HTMLElement>('.integrated-tool article'))?.focus({preventScroll:true});window.scrollTo(0,origin.scroll)})}
 const selectMenu=()=>open(['scenarios','explorer','generator','rescue','research'][index])
 let title=menu[index],body=<p>Explore frozen alternatives without replacing the current farm.</p>,primary:ToolAction|undefined={label:'Open',run:selectMenu},secondary:ToolAction|undefined
 let count=menu.length,previous=()=>setIndex(i=>Math.max(0,i-1)),next=()=>setIndex(i=>Math.min(count-1,i+1))
 if(view==='scenarios'){
  title='Frozen scenarios';count=Math.max(1,scenarios.length);const item=scenarios[index]
  body=item?<><h3>{item.name}</h3><p>{item.status} · {item.id}</p><RecordFacts value={item.controls}/><p>Frozen input: {item.input_hash}</p></>:<p>No saved scenarios. Create an isolated branch.</p>
  primary={label:item?'Inspect scenario':'Create scenario',run:()=>item?(setScenario(item),open('scenario')):open('scenario-form')};secondary={label:'New branch',run:()=>{setParent('');setSnapshotId('');setSourceConversation('');open('scenario-form')}}
 }else if(view==='scenario-form'||view==='scenario-review'){
  title=view==='scenario-review'?'Review frozen experiment':'Prepare experiment';count=0
  body=view==='scenario-review'?<><h3>{name}</h3><RecordFacts value={draft}/><p>Frozen root: {parent?`scenario ${parent}`:sourceConversation?`conversation ${sourceConversation}`:snapshotId?`dataset ${snapshotId}`:'current farm'} · Quest: {quest||'none'}</p>{snapshotId&&<p>Dataset projection selected: {policy}. The scenario engine will still compare every supported policy from this exact frozen dataset.</p>}<p>Creating this branch preserves the main farm. Run is a separate local calculation.</p></>:<><label>Name<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><label>Frozen dataset<select aria-label="Frozen dataset" value={snapshotId} disabled={Boolean(parent||sourceConversation)} onChange={e=>{setSnapshotId(e.target.value);if(e.target.value)setSourceConversation('')}}><option value="">Current farm</option>{snapshots.map(s=><option key={s.id} value={s.id}>{s.name} · {s.content_hash.slice(0,12)}</option>)}</select></label><label>Frozen adviser conversation<select aria-label="Frozen adviser conversation" value={sourceConversation} disabled={Boolean(parent||snapshotId)} onChange={e=>{setSourceConversation(e.target.value);if(e.target.value)setSnapshotId('')}}><option value="">No conversation source</option>{conversations.map(c=><option key={c.id} value={c.id}>{c.title||c.id} · {typeof c.snapshot_ref==='object'&&c.snapshot_ref?.hash?c.snapshot_ref.hash.slice(0,12):'frozen snapshot'}</option>)}</select></label><p>A conversation branch uses the exact server-frozen snapshot; adviser prose never changes controls automatically.</p><label>Quest<select aria-label="Quest" value={quest} onChange={e=>setQuest(e.target.value)}><option value="">Free experiment</option>{quests.map(q=><option key={q.id} value={q.id}>{q.title}</option>)}</select></label>{Object.entries(draft).filter(([,v])=>typeof v==='number').map(([k,v])=><label key={k}>{k.replaceAll('_',' ')}<input type="number" min={k==='delay_days'?0:50} max={k==='delay_days'?14:k==='yield_percent'?100:150} step="1" value={v as number} onChange={e=>setDraft(d=>({...d,[k]:Number(e.target.value)}))}/></label>)}<label>Batch ID (for crop delay)<input value={draft.batch_id||''} onChange={e=>setDraft(d=>({...d,batch_id:e.target.value||undefined}))}/></label><label>Demand crop ID<input value={draft.demand_crop_id||''} onChange={e=>setDraft(d=>({...d,demand_crop_id:e.target.value||undefined}))}/></label></>
  const issue=(draft.delay_days||draft.yield_percent!==100)&&!draft.batch_id?'Select a recorded batch before changing harvest delay or yield.':draft.demand_percent!==100&&!draft.demand_crop_id?'Select a modeled crop before changing demand.':!name.trim()?'Name this frozen experiment.':''
  body=<>{body}{issue&&<p role="status">{issue}</p>}</>
  primary={label:view==='scenario-review'?'Create frozen branch':'Review',disabled:Boolean(issue),run:()=>view==='scenario-review'?void act(async()=>{const s=await api.createScenario({name,controls:draft,...(parent?{parent_scenario_id:parent}:{}),...(quest?{quest_id:quest}:{}),...(!parent&&snapshotId?{explorer_snapshot_id:snapshotId}:{}),...(!parent&&!snapshotId&&sourceConversation?{source_conversation_id:sourceConversation}:{})});setScenario(s);setScenarios(await api.scenarios());open('scenario')}):open('scenario-review')}
 }else if(view==='scenario'){
  title=scenario?.name||'Scenario';count=0;const changedControls=scenario?Object.fromEntries(Object.entries(scenario.controls).filter(([key,value])=>key.endsWith('_id')?Boolean(value):value!==controls[key as keyof ScenarioControls])):{};const selectedComparison=scenario?.policy_comparisons?.find(row=>row.policy===policy)
  body=<><p>{scenario?.status} · isolated frozen branch</p>{scenario?.source_conversation_id&&<p>Frozen conversation source: {scenario.source_conversation_id}</p>}<h3>Changed controls</h3><RecordFacts value={changedControls}/><h3>Affected entities</h3><RecordFacts value={{bed_ids:scenario?.affected_bed_ids||[],crop_ids:scenario?.affected_crop_ids||[],deliveries:scenario?.affected_deliveries||[]}}/>{selectedComparison&&<><h3>{policy} same-policy comparison</h3><RecordFacts value={selectedComparison}/></>}<details><summary>All supported policy results</summary><RecordFacts value={scenario?.policy_comparisons?.length?scenario.policy_comparisons:scenario?.result}/></details><RecordFacts value={scenario?.warnings}/></>
  const running=['queued','running'].includes(scenario?.status.toLowerCase()||'')
  primary={label:running?'Refresh result':'Run locally',run:()=>void act(async()=>{if(scenario)setScenario(running?await api.scenario(scenario.id):await api.runScenario(scenario.id))})}
  secondary={label:'Scenario actions',run:()=>open('scenario-actions')}
 }else if(view==='scenario-actions'){
  title='Scenario actions';count=5;const labels=['Compare compatible roots','Continue this branch','Cancel calculation','Retry interrupted calculation','Inspect quest outcome'];body=<><h3>{labels[index]}</h3>{index===0&&<label>Compare with<select value={compareId} onChange={e=>setCompareId(e.target.value)}><option value="">Select scenario</option>{scenarios.filter(s=>s.id!==scenario?.id).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<p>Server validates frozen roots, attempts and eligibility.</p></>
  primary={label:labels[index],disabled:!scenario||(index===0&&!compareId)||(index===3&&!scenario.run_key)||(index===4&&!scenario.quest_id),run:()=>void act(async()=>{if(!scenario)return;if(index===0){setComparisonContext('scenario');setComparison(await api.compareScenarios([scenario.id,compareId]));open('comparison')}if(index===1){setParent(scenario.id);setDraft(scenario.controls);open('scenario-form')}if(index===2){setScenario(await api.cancelScenario(scenario.id));open('scenario')}if(index===3){setScenario(await api.retryScenario(scenario.id,scenario.run_key!));open('scenario')}if(index===4){setComparisonContext('scenario');setComparison(await api.inspectQuest(scenario.quest_id!,scenario.id));open('comparison')}})}
 }else if(view==='comparison'){
  title='Recorded comparison';count=0;const scenarioComparison=comparisonContext==='scenario'?comparison as ScenarioComparison:null
  body=scenarioComparison?<><p>Only compatible frozen roots can be compared. Controls and affected entities below are server-recorded branch facts.</p>{scenarioComparison.scenarios.map(item=><section key={item.id}><h3>{item.name}</h3><h4>Changed controls</h4><RecordFacts value={Object.fromEntries(Object.entries(item.controls).filter(([key,value])=>key.endsWith('_id')?Boolean(value):value!==controls[key as keyof ScenarioControls]))}/><h4>Affected entities</h4><RecordFacts value={{bed_ids:item.affected_bed_ids||[],crop_ids:item.affected_crop_ids||[],deliveries:item.affected_deliveries||[]}}/><h4>Same-policy results</h4><RecordFacts value={item.policy_comparisons}/></section>)}</>:<RecordFacts value={comparison}/>;primary=undefined
 }else if(view==='explorer'){
  title='Saved datasets';count=Math.max(1,snapshots.length);const item=snapshots[index];body=item?<><h3>{item.name}</h3><p>{item.kind} · cutoff {item.cutoff}</p><p>Frozen hash: {item.content_hash}</p></>:<p>No snapshots available.</p>
  primary={label:'Inspect records',disabled:!item,run:()=>void act(async()=>{setDetail(await api.explorerSnapshot(item.id,policy));setPage(0);open('dataset')})};secondary={label:'Public sources',run:()=>void act(async()=>{setPublicContext(await api.explorerPublic());open('public')})}
 }else if(view==='public'){
  title='Public source records';count=0
  const records=(publicContext?.datasets[publicDataset]||[]).filter(r=>(!publicSource||r.source_id===publicSource)&&JSON.stringify(r).toLowerCase().includes(filter.toLowerCase()))
  body=<><p>Public source observations retain their date, units, provenance and redistribution limits. Missing data is not a forecast.</p><label>Public dataset<select aria-label="Public dataset" value={publicDataset} onChange={e=>{setPublicDataset(e.target.value as keyof PublicContext['datasets']);setPage(0)}}>{['weather_observations','weather_forecasts','trade_observations'].map(d=><option key={d}>{d}</option>)}</select></label><label>Source<select aria-label="Source" value={publicSource} onChange={e=>{setPublicSource(e.target.value);setPage(0)}}><option value="">All sources</option>{publicContext?.sources.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Filter<input value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}/></label><label>Page<input type="number" min="1" value={page+1} onChange={e=>setPage(Math.max(0,Number(e.target.value)-1))}/></label><p>{records.length} matching records</p><RecordFacts value={publicContext?.sources.filter(s=>!publicSource||s.id===publicSource)}/><RecordFacts value={records.slice(page*8,page*8+8)}/></>
  primary={label:'Export public CSV',run:()=>void act(async()=>{const params=new URLSearchParams({dataset:publicDataset,format:'csv',q:filter,...(publicSource?{source_id:publicSource}:{})});const url=URL.createObjectURL(await requestBlob('/data-explorer/public/export?'+params));const a=document.createElement('a');a.href=url;a.download='farmtact-public.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)})};secondary={label:'Evaluation evidence',run:()=>void act(async()=>{setComparisonContext('evaluation');setComparison(await api.explorerEvaluation());open('comparison')})}
 }else if(view==='generator'||view==='generator-review'){
  title=view==='generator-review'?'Review generated preview':'Dataset & forecast settings';count=0
  body=view==='generator-review'?<><p>Preview—not saved. Synthetic assumptions only.</p><RecordFacts value={detail?.counts}/><RecordFacts value={{generator,forecast,hash:detail?.content_hash}}/></>:<><label>Snapshot name<input value={name} onChange={e=>setName(e.target.value)}/></label>{Object.keys(generator).map(k=><label key={k}>{k.replaceAll('_',' ')}<input type="number" step="0.05" value={generator[k as keyof typeof generator]} onChange={e=>setGenerator((g:typeof generator)=>({...g,[k]:Number(e.target.value)}))}/></label>)}<label>EWMA alpha<input type="number" min="0.01" max="1" step="0.01" value={forecast.alpha} onChange={e=>setForecast({alpha:Number(e.target.value)})}/></label></>
  primary={label:view==='generator-review'?'Save frozen dataset':'Preview locally',run:()=>void act(async()=>{if(view==='generator-review'){setDetail(await api.saveExplorerSnapshot(name,generator,forecast));setSnapshots(await api.explorerSnapshots());open('dataset')}else{setDetail(await api.explorerPreview(generator,forecast));open('generator-review')}})}
 }else if(view==='dataset'){
  title=detail?.name||'Dataset';count=0
  const rows=(detail?.records[dataset]||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(filter.toLowerCase())&&(!crop||r.crop_id===crop)&&(!start||!recordDate(r)||recordDate(r)>=start)&&(!end||!recordDate(r)||recordDate(r)<=end)).sort((a,b)=>{const av=a[sort],bv=b[sort];return (numeric(av)&&numeric(bv)?Number(av)-Number(bv):String(av??'').localeCompare(String(bv??''),undefined,{numeric:true}))*(descending?-1:1)}),fields=detail?.fields[dataset]||[],shown=rows.slice(page*8,page*8+8)
  body=<><p>{detail?.unsaved?'Preview—not saved':'Frozen saved snapshot'} · {detail?.content_hash}</p><label>Dataset<select aria-label="Dataset" value={dataset} onChange={e=>{setDataset(e.target.value as DatasetKey);setPage(0)}}>{datasets.map(x=><option key={x}>{x}</option>)}</select></label><label>Filter<input value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}/></label><label>Crop filter<select aria-label="Crop filter" value={crop} onChange={e=>{setCrop(e.target.value);setPage(0)}}><option value="">All crops</option>{[...new Set((detail?.records[dataset]||[]).map(r=>r.crop_id).filter(Boolean))].map(c=><option key={c}>{c}</option>)}</select></label><label>From date<input type="date" value={start} onChange={e=>{setStart(e.target.value);setPage(0)}}/></label><label>Through date<input type="date" value={end} onChange={e=>{setEnd(e.target.value);setPage(0)}}/></label><label>Sort direction<select aria-label="Sort direction" value={String(descending)} onChange={e=>{setDescending(e.target.value==='true');setPage(0)}}><option value="false">Ascending</option><option value="true">Descending</option></select></label><label>Sort<select aria-label="Sort" value={sort} onChange={e=>setSort(e.target.value)}>{fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label><label>Record page<input type="number" min="1" max={Math.max(1,Math.ceil(rows.length/8))} value={page+1} onChange={e=>setPage(Math.max(0,Math.min(Math.ceil(rows.length/8)-1,Number(e.target.value)-1)))}/></label><p>{rows.length} matching records · {fields.map(f=>`${f.label}${f.unit?' ('+f.unit+')':''}`).join(', ')}</p>{shown.map(r=><RecordFacts key={r.id} value={r}/>)}<ExplorerChart points={rows.flatMap(r=>{const v=fields.find(f=>numeric(r[f.key])&&f.key!=="id");return recordDate(r)&&v?[{id:r.id,date:recordDate(r),value:Number(r[v.key]),label:String(r.crop_id||dataset),series:String(r.crop_id||dataset)}]:[]})} unit="record units" planningDate={detail?.planning_date}/></>
  primary={label:'Snapshot actions',run:()=>open('dataset-actions')};secondary={label:'Record relationships',run:()=>{setSelectedRecord(shown[0]?.id||'');open('relationships')}}
 }else if(view==='relationships'){
  title='Linked records';count=0;const row=detail?.records[dataset].find(r=>r.id===selectedRecord)
  const links=Object.entries(row||{}).filter(([k,v])=>k.endsWith('_id')&&typeof v==='string')
  body=<><label>Record<select aria-label="Record" value={selectedRecord} onChange={e=>setSelectedRecord(e.target.value)}>{detail?.records[dataset].map(r=><option key={r.id}>{r.id}</option>)}</select></label><RecordFacts value={row}/><p>Relationships use recorded canonical identifiers in this frozen snapshot.</p>{links.map(([field,id])=><section key={field}><h3>{field.replaceAll('_',' ')}: {String(id)}</h3><RecordFacts value={Object.entries(detail?.records||{}).flatMap(([kind,records])=>(records as ExplorerRecord[]).filter(r=>r.id===id).map(record=>({dataset:kind,record})))}/></section>)}</>;primary=undefined
 }else if(view==='dataset-actions'){
  title='Snapshot actions';count=3;const labels=['Export records','Start all-policy frozen branch','Inspect provenance'];body=<><h3>{labels[index]}</h3>{index===0&&<label>Export format<select aria-label="Export format" value={format} onChange={e=>setFormat(e.target.value)}><option value="csv">CSV</option><option value="json">JSON</option></select></label>}<RecordFacts value={index===2?detail?.provenance:{snapshot:detail?.id,dataset,filter}}/>{index!==1?<label>Dataset projection policy<select aria-label="Dataset projection policy" value={policy} onChange={e=>setPolicy(e.target.value)}>{['Lean','Balanced','Resilient'].map(p=><option key={p}>{p}</option>)}</select></label>:<p>The frozen branch uses this dataset and calculates every supported policy. Choose a policy when inspecting or exporting projected records.</p>}</>
  primary={label:labels[index],disabled:!detail||detail.unsaved,run:()=>{if(index===0&&detail)void act(async()=>{const params=new URLSearchParams({snapshot_id:detail.id,dataset,format,q:filter,sort,policy,...(crop?{crop_id:crop}:{}),...(start?{start}:{}),...(end?{end}:{}) ,descending:String(descending)});const url=URL.createObjectURL(await requestBlob('/data-explorer/export?'+params));const link=document.createElement('a');link.href=url;link.download='farmtact-dataset.'+format;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});if(index===1){setParent('');setSourceConversation('');setSnapshotId(detail?.id||'');open('scenario-form')}if(index===2)void act(async()=>{if(detail)setDetail(await api.explorerSnapshot(detail.id,policy));open('dataset')})}}
 }else if(view==='rescue'){
  title='Waste Rescue';count=0;body=<><p>Local projected comparison from dated surplus lots. It does not authorize an operation.</p><label>Projected strategy<select aria-label="Projected strategy" value={rescueStrategy||session?.selected_strategy_id||''} onChange={e=>{setRescueStrategy(e.target.value);setRescue(null)}}>{session?.result?.strategies?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Lot ID (blank selects supported surplus)<input value={lot} onChange={e=>setLot(e.target.value)}/></label>{[['Sale price',sale,setSale],['Rescue price',price,setPrice],['Rescue cost',cost,setCost]].map(([label,value,set])=><label key={String(label)}>{String(label)} SGD/kg<input type="number" min="0" step="0.01" value={String(value)} onChange={e=>(set as (v:string)=>void)(e.target.value)}/></label>)}<RecordFacts value={rescue}/></>
  primary={label:'Compare rescue outcomes',disabled:!session?.result_id||!session.selected_strategy_id,run:()=>void act(async()=>{if(session)setRescue(await farmerWorkflowApi.wasteRescue({session_id:session.id,result_id:String(session.result_id),strategy_id:rescueStrategy||session.selected_strategy_id!,...(lot?{lot_id:lot}:{}),sale_price_sgd_per_kg:Number(sale),rescue_price_sgd_per_kg:Number(price),rescue_cost_sgd_per_kg:Number(cost)}))})}
 }else if(view==='research'){
  title='Council research';count=0;body=<p>Explore scripted discussion and saved numerical experiments in an isolated research session.</p>;primary={label:'Open research cards',disabled:!onResearch,run:()=>onResearch?.()}
 }
 const card=staticToolCard('experiments',view==='index'?menu[index]:view,title)
 const scenarioCard=view==='scenarios'?scenarios[index]:['scenario','scenario-actions'].includes(view)||(view==='comparison'&&comparisonContext==='scenario')?scenario:null
 const snapshotCard=view==='explorer'?snapshots[index]:['dataset','dataset-actions','relationships','generator-review'].includes(view)?detail:null
 if(scenarioCard){
  card.entityId=scenarioCard.id;card.entityKind='scenario';card.id=`experiments:${view}:${scenarioCard.id}`
  card.binding={sessionId:null,inputHash:scenarioCard.input_hash||null,revision:cardRevision(scenarioCard.revision),resultId:null,snapshotId:scenarioCard.snapshot_ref||null}
  card.provenance=cardReferences(scenarioCard.snapshot_ref,scenarioCard.baseline_hash,scenarioCard.parent_scenario_id)
  card.boardTargets=scenarioCard.affected_bed_ids||[];card.outcomeBasis='projection'
 }else if(snapshotCard){
  card.entityId=snapshotCard.id;card.entityKind='dataset_snapshot';card.id=`experiments:${view}:${snapshotCard.id}:${view==='relationships'?selectedRecord:dataset}`
  card.binding={sessionId:null,inputHash:snapshotCard.content_hash,revision:null,resultId:null,snapshotId:snapshotCard.id}
  card.provenance=cardReferences('provenance' in snapshotCard?snapshotCard.provenance:null,snapshotCard.content_hash)
  card.outcomeBasis='projection'
  if(view==='relationships'&&selectedRecord){card.entityId=selectedRecord;card.entityKind=dataset;const row=detail?.records[dataset].find(record=>record.id===selectedRecord);card.boardTargets=cardString(row?.bed_id)?[String(row?.bed_id)]:dataset==='beds'?[selectedRecord]:[]}
 }else if(view==='rescue'&&session){
  card.entityId=lot||rescueStrategy||session.selected_strategy_id||session.id;card.entityKind=lot?'inventory_lot':rescueStrategy||session.selected_strategy_id?'strategy':'planning_session'
  card.id=`experiments:rescue:${card.entityId}`;card.binding={sessionId:session.id,inputHash:session.input_hash,revision:session.revision,resultId:cardString(session.result_id)}
  card.provenance=cardReferences(session.result_id,session.input_hash);card.outcomeBasis='projection'
 }else if(view==='public'){
  card.entityId=publicSource||publicDataset;card.entityKind=publicSource?'public_source':'public_dataset';card.id=`experiments:public:${card.entityId}`
  card.provenance=cardReferences(publicContext?.sources.filter(source=>!publicSource||source.id===publicSource))
 }
 card.actions=toolCardActions(primary,secondary,busy,['Create frozen branch','Run locally','Cancel calculation','Retry interrupted calculation','Inspect quest outcome','Save frozen dataset'])
 return <ToolCard card={card} title={title} onBack={back} primary={primary} secondary={secondary} previous={count>0&&index>0?previous:undefined} next={count>0&&index<count-1?next:undefined} position={count?`${index+1} of ${count}`:undefined} busy={busy} error={error}>{body}</ToolCard>
}
