import { useEffect, useState } from 'react'
import { api, simulationEventHistory, type SimulationWorld } from '../lib/api'
import { planningApi, farmerWorkflowApi, type PlanningSession } from '../lib/planning'
import { ToolCard, RecordFacts } from './ToolCard'
import { AudioControls } from './AudioControls'
import { editionStorageKey } from '../lib/edition'
import { useCardView } from '../lib/cardNavigation'
export default function IntegratedHistory({onClose}:{onClose:()=>void}){
 const [index,setIndex]=useState(0),[view,setView,restoreView,captureView]=useCardView(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[rows,setRows]=useState<Array<{id:string;name:string;value:unknown}>>([]),[record,setRecord]=useState<unknown>(null),[world,setWorld]=useState<SimulationWorld|null>(null),[plan,setPlan]=useState<PlanningSession|null>(null),[version,setVersion]=useState('')
 const [motion,setMotion]=useState(()=>{try{return localStorage.getItem(editionStorageKey('reduced-motion'))==='true'}catch{return false}})
 const labels=['Saved plans','Discussions','Simulations','Event history','Accessibility & audio','Help']
 const act=async(fn:()=>Promise<void>)=>{captureView();setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Could not load saved history')}finally{setBusy(false)}}
 useEffect(()=>{document.documentElement.dataset.reducedMotion=String(motion);try{localStorage.setItem(editionStorageKey('reduced-motion'),String(motion))}catch{}},[motion])
 const open=()=>void act(async()=>{if(index===4){setView('preferences');return}if(index===5){setView('help');return}if(index===0)setRows((await planningApi.list()).sessions.map(p=>({id:p.id,name:String(p.name||p.id),value:p})));if(index===1)setRows((await api.conversations()).map(c=>({id:c.id,name:c.title||c.id,value:c})));if(index===2)setRows((await api.simulations()).map(s=>({id:s.id,name:`${s.clock_date||'Not started'} · ${s.status}`,value:s})));if(index===3)setRows((await farmerWorkflowApi.state()).events.map((e,i)=>({id:String(i),name:`${e.event_type||'Event'} · ${e.occurred_at||''}`,value:e})));setView('list')})
 const [days,setDays]=useState<1|7>(1)
 const [item,setItem]=useState(0)
 const load=()=>void act(async()=>{const row=rows[item];if(!row)return;setWorld(null);setPlan(null);if(index===0){const p=await planningApi.get(row.id);setPlan(p);setRecord(p)}else if(index===1)setRecord(await api.conversationReplay(row.id));else if(index===2){const w=await api.simulation(row.id);setWorld(w);setRecord({world:w,events:await simulationEventHistory(row.id)})}else setRecord(row.value);setView('replay')})
 let title=labels[index],body=<p>Read saved facts without recalculation or inference.</p>,primary:{label:string;run:()=>void;disabled?:boolean}|undefined={label:'Open',run:open},secondary:{label:string;run:()=>void}|undefined,count=labels.length,pos=index
 let prev=()=>setIndex(index-1),next=()=>setIndex(index+1)
 if(view==='list'){title=labels[index];body=<><h3>{rows[item]?.name||'No saved records'}</h3><p>{rows[item]?.id}</p></>;primary={label:'Read-only replay',run:load,disabled:!rows[item]};count=rows.length;pos=item;prev=()=>setItem(item-1);next=()=>setItem(item+1)}
 if(view==='replay'){title='Read-only saved replay';body=<><p>Recorded data. Reading this card makes no provider calls or farm mutations.</p><RecordFacts value={record}/></>;count=0;primary=undefined;if(world)secondary={label:'Review time advance',run:()=>setView('advance')};else if(plan)secondary={label:'Saved versions',run:()=>{setVersion(String(plan.history?.[0]?.result_id||''));setView('versions')}}}
 if(view==='versions'){title='Frozen planning versions';count=0;body=<><p>Each result is an immutable numerical snapshot. Replay never recalculates.</p><label>Saved result<select value={version} onChange={e=>setVersion(e.target.value)}>{plan?.history?.map(h=><option key={String(h.result_id)} value={String(h.result_id)}>{String(h.created_at)} · {String(h.kind)} · {String(h.result_id)}</option>)}</select></label></>;primary={label:'Replay saved result',disabled:!version,run:()=>void act(async()=>{if(plan){setRecord(await planningApi.replayResult(plan.id,version));setView('replay')}})};secondary={label:'Review time advance',run:()=>setView('advance')}}
 if(view==='advance'){title='Review sandbox clock advance';count=0;body=<><p>Explicitly advance {days} simulated {days===1?'day':'days'} for {world?.id||plan?.id}. This appends simulation events and may change inventory and deliveries. No actual farm operation is authorized.</p><label>Days to advance<select value={days} onChange={e=>setDays(Number(e.target.value) as 1|7)}><option value={1}>One day</option><option value={7}>Seven days</option></select></label></>;primary={label:days===1?'Advance one day':'Advance seven days',run:()=>void act(async()=>{if(world){const w=await api.advanceSimulation(world.id,world.revision,days);setWorld(w);setRecord({world:w,events:await simulationEventHistory(w.id)})}else if(plan){const p=await planningApi.advance(plan.id,plan.revision,days);setPlan(p);setRecord(p)}setView('replay')})}}
 if(view==='preferences'){title='Accessibility & audio';count=0;body=<><label><input type="checkbox" checked={motion} onChange={e=>setMotion(e.target.checked)}/>Reduced motion</label><p>Saved consequences remain available as text. System reduced-motion settings are also respected.</p><AudioControls editionKey="v15"/></>;primary=undefined}
 if(view==='help'){title='Using FarmTact';count=0;body=<><p>Read a card, swipe horizontally or use Previous/Next to compare, then act beneath it. Arrow keys work on the card surface; forms keep native keyboard behavior.</p><p>Preview is not saved. Projected plans, recorded simulation outcomes and farmer-reported work are different kinds of evidence. Explain uses stored facts. Only an explicit AI submission invokes an adviser.</p><p>You can skip or resume guidance without losing access to any tool. More opens five tool decks. Reviewed imports create a separate planning attempt; historical edition data stays separate.</p><p>For voice typing, use your device keyboard’s microphone. There is no custom recording or transcription integration.</p><p>If interrupted, retain your draft and refresh saved state before retrying. Respect any rate-limit wait. Actual farm operations are disabled.</p></>;primary=undefined}
 return <ToolCard title={title} onBack={()=>{if(view==='index')onClose();else if(view==='advance'||view==='versions')restoreView('replay');else if(view==='replay')restoreView('list');else{restoreView('index');setItem(0)}}} primary={primary} secondary={secondary} previous={count&&pos>0?prev:undefined} next={count&&pos<count-1?next:undefined} position={count?`${pos+1} of ${count}`:undefined} busy={busy} error={error}>{body}</ToolCard>
}
