import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  CheckCircle2,
  ClipboardCheck,
  FileUp,
  History,
  LoaderCircle,
  PencilLine,
  RotateCcw,
  Rows3,
} from "lucide-react";
import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type KeyboardEventHandler, type ReactNode, type TouchEventHandler } from "react";
import { createPortal } from "react-dom";
import { requestBlob } from "../lib/api";
import BoundCard from "./BoundCard";
import { editionStorageKey } from "../lib/edition";
import type { FarmCard, RecordsTarget } from "../lib/cards";
import type { Bed, FarmOrder } from "../lib/types";
import {
  farmerWorkflowApi,
  planningApi,
  rememberPlanningSession,
  rememberedPlanningSession,
  type FarmerImport,
  type FarmerProposal,
  type FarmerTask,
  type FarmerWorkflowState,
  type PlanningSession,
} from "../lib/planning";
import "./IntegratedRecords.css";
import "./tool-card.css";

type View = "home" | "setup" | "imports" | "orders" | "beds" | "inventory" | "proposals" | "tasks" | "verify" | "history";
type Form = "farmImport" | "seed" | "upload" | "manual" | "candidate" | "source" | "approve" | "recovery" | "result" | "correction" | null;

const emptyWorkflow: FarmerWorkflowState = {
  version: "farmer-workflow-v1",
  phase: "planning",
  revision: 0,
  inbox: [],
  proposals: [],
  tasks: [],
  events: [],
  real_operations_enabled: false,
};
const CardMetaContext = createContext<FarmCard | null>(null);
function CardMeta({ card, children }: { card: FarmCard; children: ReactNode }) { return <CardMetaContext.Provider value={card}>{children}</CardMetaContext.Provider>; }

export function IntegratedRecords({ onClose, onOpenPlan, onOpenWasteRescue, initialTarget }: { initialTarget?: RecordsTarget; onClose: () => void; onOpenPlan?: () => void; onOpenWasteRescue?: () => void }) {
  const [session, setSession] = useState<PlanningSession | null>(null);
  const [workflow, setWorkflow] = useState(emptyWorkflow);
  const [view, setView] = useState<View>(initialTarget?.view || "home");
  const [form, setForm] = useState<Form>(null);
  const [index, setIndex] = useState(0);
  const [homeIndex, setHomeIndex] = useState(0);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const touch = useRef<{ x: number; y: number } | null>(null);
  const refresh = useCallback(async () => {
    const flow = await farmerWorkflowApi.state();
    setWorkflow({ ...emptyWorkflow, ...flow });
    return flow;
  }, []);
  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      let current: PlanningSession | undefined;
      const remembered = rememberedPlanningSession();
      if (remembered) {
        try { current = await planningApi.get(remembered); } catch { /* use latest */ }
      }
      if (!current) current = (await planningApi.list()).sessions.find((item) => item.workflow === true);
      setSession(current || null);
      await refresh();
    } catch (caught) {
      setError(problem(caught, "Farm records could not be opened."));
    } finally { setLoading(false); }
  }, [refresh]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const sync = () => { void Promise.all([refresh(), rememberedPlanningSession() ? planningApi.get(rememberedPlanningSession()!) : Promise.resolve(null)]).then(([, next]) => { if (next) setSession(next); }).catch(caught => setError(problem(caught, "Updated workflow state could not be refreshed."))).finally(() => window.dispatchEvent(new Event("farmtact-workflow-refreshed"))); }; window.addEventListener("farmtact-workflow-refresh", sync); return () => window.removeEventListener("farmtact-workflow-refresh", sync); }, [refresh]);

  const currentProposals = useMemo(() => workflow.proposals.filter(item => item.session_id === session?.id), [workflow.proposals, session?.id]);
  const currentProposalIds = useMemo(() => new Set(currentProposals.map(item => item.id)), [currentProposals]);
  const currentTasks = useMemo(() => workflow.tasks.filter(item => currentProposalIds.has(item.proposal_id)), [workflow.tasks, currentProposalIds]);
  const currentSubjectIds = useMemo(() => new Set([session?.id, ...currentProposals.map(item => item.id), ...currentTasks.map(item => item.id)].filter(Boolean)), [session?.id, currentProposals, currentTasks]);
  const currentEvents = useMemo(() => workflow.events.filter(item => String(item.session_id || "") === session?.id || currentSubjectIds.has(String(item.subject_id || ""))), [workflow.events, session?.id, currentSubjectIds]);
  const cards = useMemo(() => {
    if (view === "imports") return workflow.inbox;
    if (view === "orders") return session?.farm.orders || [];
    if (view === "beds") return session?.farm.beds || [];
    if (view === "inventory") return Array.isArray(session?.farm.inventory) ? session.farm.inventory as Record<string, unknown>[] : [];
    if (view === "proposals") return currentProposals;
    if (view === "tasks") return currentTasks;
    if (view === "history") return currentEvents;
    return [];
  }, [view, workflow.inbox, session, currentProposals, currentTasks, currentEvents]);
  useEffect(() => setIndex((old) => Math.min(old, Math.max(0, cards.length - 1))), [cards.length]);
  const targetSelected = useRef(false);
  useEffect(() => { if (loading || targetSelected.current || !initialTarget?.entityId) return; targetSelected.current = true; const found = cards.findIndex(item => "id" in item && item.id === initialTarget.entityId); if (found >= 0) setIndex(found); }, [loading, cards, initialTarget]);
  const homeOrigin = useRef<{label:string;scroll:number}|null>(null);
  const open = (next: View) => {
    if (view === "home" && next !== "home") homeOrigin.current = {label: document.activeElement?.textContent?.trim() || "", scroll: window.scrollY};
    setView(next); setIndex(0); setForm(null); setError("");
    if (next === "home" && homeOrigin.current) requestAnimationFrame(() => requestAnimationFrame(() => {
      const origin = homeOrigin.current!;
      Array.from(document.querySelectorAll<HTMLButtonElement>(".integrated-records button")).find(button => button.textContent?.trim() === origin.label)?.focus({preventScroll:true});
      window.scrollTo(0, origin.scroll);
    }));
  };
  const back = () => { if (form) setForm(null); else if (initialTarget && view === initialTarget.view) onClose(); else if (view !== "home") open("home"); else onClose(); };
  const run = async (action: () => Promise<unknown>, fallback: string) => {
    setBusy(true); setError("");
    try { await action(); await refresh(); const remembered = rememberedPlanningSession(); if (remembered) setSession(await planningApi.get(remembered)); setForm(null); }
    catch (caught) { setError(problem(caught, fallback)); }
    finally { setBusy(false); }
  };

  if (loading) return <Shell title="Records & work" onBack={onClose}><Empty icon={<LoaderCircle className="spin" />} text="Opening farm records…" /></Shell>;
  const candidate = view === "imports" ? workflow.inbox[index] : undefined;
  const proposal = view === "proposals" ? currentProposals[index] : undefined;
  const task = view === "tasks" ? currentTasks[index] : undefined;
  const event = view === "history" ? currentEvents[index] : undefined;
  const order = view === "orders" ? session?.farm.orders[index] : undefined;
  const bed = view === "beds" ? session?.farm.beds[index] : undefined;
  const inventory = view === "inventory" && Array.isArray(session?.farm.inventory) ? (session.farm.inventory as Record<string, unknown>[])[index] : undefined;
  return (
    <Shell title={title(view, form)} onBack={back} onKeyDown={(event) => {
      if ((event.target as HTMLElement).closest("input,textarea,select,button,a")) return;
      if (form) return;
      if (view === "home" && event.key === "ArrowRight" && homeIndex < homeItems(workflow, session).length - 1) { event.preventDefault(); setHomeIndex(homeIndex + 1); return; }
      if (view === "home" && event.key === "ArrowLeft" && homeIndex > 0) { event.preventDefault(); setHomeIndex(homeIndex - 1); return; }
      if (event.key === "ArrowRight" && index < cards.length - 1) { event.preventDefault(); setIndex(index + 1); }
      if (event.key === "ArrowLeft" && index > 0) { event.preventDefault(); setIndex(index - 1); }
    }} onTouchStart={(event) => { if (form || (event.target as HTMLElement).closest("input,textarea,select,button,a")) { touch.current = null; return; } touch.current = { x: event.touches[0].clientX, y: event.touches[0].clientY }; }} onTouchEnd={(event) => {
      const from = touch.current; touch.current = null; if (!from || form) return;
      const dx = event.changedTouches[0].clientX - from.x, dy = event.changedTouches[0].clientY - from.y;
      if (Math.abs(dx) > 65 && Math.abs(dx) > Math.abs(dy) * 1.5) { if (view === "home") setHomeIndex((old) => Math.max(0, Math.min(homeItems(workflow, session).length - 1, old + (dx < 0 ? 1 : -1)))); else setIndex((old) => Math.max(0, Math.min(cards.length - 1, old + (dx < 0 ? 1 : -1)))); }
    }}>
      <p className="ir-context">Sandbox farm · real operations disabled</p>
      {error && <div className="ir-error" role="alert"><AlertTriangle />{error}</div>}
      {view === "home" && <Home workflow={workflow} session={session} index={homeIndex} setIndex={setHomeIndex} open={open} />}
      {view === "setup" && !form && <Card eyebrow="Validated farm setup" title="Choose the source for a new farm version" status="review required"><p>Import a complete validated farm document or explicitly load the project-authored synthetic fixture. Either choice creates a separate workflow session and preserves older sessions.</p><p className="ir-note">A rendered farm view is not an import template. The JSON review card offers the authenticated full-schema current farm.</p></Card>}
      {view !== "home" && !form && cards.length > 0 && (
        <nav className="ir-pager" aria-label={`${title(view, null)} cards`}>
          <button disabled={index === 0} onClick={() => setIndex(index - 1)}><ArrowLeft /> Previous</button>
          <span>{label(view)} {index + 1} of {cards.length}</span>
          <button disabled={index === cards.length - 1} onClick={() => setIndex(index + 1)}>Next <ArrowRight /></button>
        </nav>
      )}
      {view !== "home" && view !== "setup" && view !== "verify" && !form && cards.length === 0 && <Empty icon={<Rows3 />} text={`No ${label(view).toLowerCase()} records are available.`} />}
      {candidate && !form && <CandidateCard item={candidate} />}
      {proposal && !form && <ProposalCard item={proposal} session={session} />}
      {task && !form && <TaskCard item={task} proposal={currentProposals.find(item => item.id === task.proposal_id)} session={session} />}
      {event && !form && <CardMeta card={bound(`${String(event.subject_id || "event")}:${String(event.sequence ?? index)}`, "workflow_event", String(event.event_type || "Saved workflow event"), session, [String(event.subject_id || "")], [backAction], event.event_type === "reported_forecast_recalculated" ? "farmer_reported" : null, Number.isFinite(Number(event.sequence)) ? Number(event.sequence) : null)}><EventCard item={event} /></CardMeta>}
      {order && !form && <OrderCard item={order} session={session} />}
      {bed && !form && <BedCard item={bed} session={session} />}
      {inventory && !form && <InventoryCard item={inventory} session={session} />}
      {view === "verify" && !form && <CardMeta card={bound("reported-forecast", "reported_forecast", "Verify recorded work and future impact", session, currentTasks.filter(item => item.event_revision > 0).map(item => item.id), [backAction, ...(onOpenPlan && currentTasks.some(item => item.status === "recovery_required") ? [localAction("review-plan", "Review future-only plan")] : [])], "farmer_reported")}><VerifyCard session={session} tasks={currentTasks} onOpenPlan={onOpenPlan} /></CardMeta>}
      {form === "farmImport" && <FarmImportReviewForm busy={busy} submit={(farm, expectedVersion) => run(async () => { const next = await planningApi.importFarm(expectedVersion, { farm }, "Imported farm workflow"); rememberPlanningSession(next.id); setSession(next); }, "The validated farm and workflow could not be imported atomically. Your reviewed JSON is unchanged.")} />}
      {form === "seed" && <SeedReview busy={busy} submit={(expectedVersion) => run(async () => { const next = await planningApi.importFarm(expectedVersion, { fixture: "synthetic_demo" }, "Synthetic demo workflow"); rememberPlanningSession(next.id); setSession(next); }, "The synthetic demo and workflow could not be loaded atomically.")} />}
      {form === "upload" && <UploadForm busy={busy} submit={(file) => run(async () => {
        const kind = file.type.startsWith("image/") ? "photo_observation" : /\.(csv|xlsx|xls)$/i.test(file.name) ? "accounting_export" : "document_extraction";
        await farmerWorkflowApi.upload(file, kind);
      }, "The candidate could not be uploaded. Draft and file selection are unchanged.")} />}
      {form === "manual" && session && <ManualForm session={session} busy={busy} submit={(name, row) => run(() => farmerWorkflowApi.manualImport(name, [row]), "The manual candidate could not be saved. Your draft is unchanged.")} />}
      {form === "candidate" && candidate && <CardMeta card={bound(candidate.candidate_id, "import_candidate_review", candidate.source_name, session, [String(candidate.source_sha256 || "")], [backAction, serverAction("reject", "Reject candidate", !busy), serverAction("confirm", "Confirm reviewed fields", !busy)])}><CandidateReview item={candidate} busy={busy} decide={(decision, note) => run(() => farmerWorkflowApi.reviewImport(candidate.candidate_id, decision, "farmer", note), "The review decision could not be saved. Please check the candidate and retry.")} /></CardMeta>}
      {form === "source" && candidate && <CardMeta card={bound(candidate.candidate_id, "import_source", candidate.source_name, session, [String(candidate.source_sha256 || "")], [backAction, localAction("inspect", "Inspect source"), localAction("download", "Download source")])}><InlineSourceReview item={candidate} /></CardMeta>}
      {form === "approve" && proposal && <CardMeta card={proposalMeta(proposal, session, [backAction, { id: "approve", label: "Approve revision & create tasks", eligible: proposal.approval?.available === true && !busy, authority: "server_mutation", eligibilitySource: "server", ...(!(proposal.approval?.available === true && !busy) ? { disabledReason: proposal.approval?.reason || (busy ? "Approval request is in progress." : "Server eligibility is not available.") } : {}) }])}><ApprovalReview item={proposal} busy={busy} approve={() => run(() => farmerWorkflowApi.approve(proposal), "This proposal could not be approved. Refresh and review its current revision.")} /></CardMeta>}
      {form === "recovery" && proposal && <CardMeta card={proposalMeta(proposal, session, [backAction, serverAction("create-recovery", "Create recovery proposal", !busy && Boolean(proposal.undo?.available))])}><RecoveryReview item={proposal} busy={busy} create={() => run(() => farmerWorkflowApi.inverseProposal(proposal), "The recovery proposal could not be created. Refresh and review the eligible revision.")} /></CardMeta>}
      {form === "result" && task && <CardMeta card={taskMeta(task, currentProposals.find(item => item.id === task.proposal_id), session, [backAction, serverAction("save-result", "Save reported result", !busy)])}><ResultForm task={task} photos={workflow.inbox.filter((item) => item.status === "confirmed" && item.source_kind === "photo_observation")} busy={busy} submit={(values) => run(() => farmerWorkflowApi.taskResult(task, values.status, task.unit ? values.quantity : null, task.action === "delivery" ? values.rejected : null, values.note, values.checks, values.photo || null), "The reported result could not be saved. Your draft is unchanged.")} /></CardMeta>}
      {form === "correction" && task && <CardMeta card={taskMeta(task, currentProposals.find(item => item.id === task.proposal_id), session, [backAction, serverAction("save-correction", "Save auditable correction", !busy)])}><CorrectionForm task={task} busy={busy} submit={(value, reason, field = "actual_quantity") => run(() => farmerWorkflowApi.correctTask(task, field, value, reason), "The correction could not be saved. Your draft is unchanged.")} /></CardMeta>}
      <div className="ir-actions" aria-label="Card actions">
        <button onClick={back}><ArrowLeft /> Back</button>
        {view === "home" && !form && <button className="is-primary" onClick={() => open(homeItems(workflow, session)[homeIndex].view)}>Open</button>}
        {view === "setup" && !form && <button className="is-primary" onClick={() => setForm("farmImport")}><FileUp /> Review farm JSON</button>}
        {view === "setup" && !form && <button onClick={() => setForm("seed")}><Rows3 /> Review demo load</button>}
        {view === "imports" && !form && candidate?.status === "candidate" && <button className="is-primary" onClick={() => setForm("candidate")}><ClipboardCheck /> Review candidate</button>}
        {view === "imports" && !form && candidate?.status !== "candidate" && <button onClick={() => setForm("upload")}><FileUp /> Add candidate</button>}
        {view === "imports" && !form && candidate && <button onClick={() => setForm("source")}>Source</button>}
        {view === "imports" && !form && !candidate && <button className="is-primary" onClick={() => setForm("manual")}><PencilLine /> Manual record</button>}
        {view === "imports" && form === "upload" && <button onClick={() => setForm("manual")}><PencilLine /> Manual instead</button>}
        {view === "proposals" && !form && proposal?.status === "applied" && <button className="is-primary" onClick={() => setForm("approve")}><CheckCircle2 /> Review approval</button>}
        {view === "proposals" && !form && proposal?.undo?.available && <button onClick={() => setForm("recovery")}><RotateCcw /> Review recovery</button>}
        {view === "tasks" && !form && task && ["pending", "in_progress"].includes(task.status) && <button className="is-primary" onClick={() => setForm("result")}><ClipboardCheck /> Record result</button>}
        {view === "tasks" && !form && task && task.event_revision > 0 && <button onClick={() => setForm("correction")}><RotateCcw /> Correct record</button>}
        {view === "tasks" && !form && task?.status === "recovery_required" && onOpenPlan && <button onClick={onOpenPlan}><RotateCcw /> Replan future work</button>}
        {view === "inventory" && !form && onOpenWasteRescue && <button onClick={onOpenWasteRescue}>Compare Waste Rescue</button>}
        <span id="ir-form-actions" className="ir-form-actions" />
      </div>
    </Shell>
  );
}

function Shell({ title, onBack, children, ...events }: { title: string; onBack: () => void; children: ReactNode; onKeyDown?: KeyboardEventHandler<HTMLElement>; onTouchStart?: TouchEventHandler<HTMLElement>; onTouchEnd?: TouchEventHandler<HTMLElement> }) {
  return <section className="integrated-records" tabIndex={0} {...events}><header><div><small>Records &amp; work</small><h2>{title}</h2></div></header>{children}</section>;
}
function homeItems(workflow: FarmerWorkflowState, session: PlanningSession | null): Array<{ view: View; name: string; detail: string; count: number }> { const proposals = workflow.proposals.filter(item => item.session_id === session?.id), proposalIds = new Set(proposals.map(item => item.id)), tasks = workflow.tasks.filter(item => proposalIds.has(item.proposal_id)), subjects = new Set([session?.id, ...proposals.map(item => item.id), ...tasks.map(item => item.id)].filter(Boolean)), events = workflow.events.filter(item => String(item.session_id || "") === session?.id || subjects.has(String(item.subject_id || ""))); return [
  { view: "setup", name: "Farm setup", detail: "Review a complete farm JSON document or the synthetic demo before creating a new version.", count: 2 },
  { view: "imports", name: "Farm records", detail: "Import accounting, documents or photos; review every candidate explicitly.", count: workflow.inbox.length },
  { view: "orders", name: "Confirmed orders", detail: "Browse dated commitments with stable record identities.", count: session?.farm.orders.length || 0 },
  { view: "beds", name: "Growing spaces", detail: "Inspect bed identity, system, crop and reported stage.", count: session?.farm.beds.length || 0 },
  { view: "inventory", name: "Inventory", detail: "Inspect reported lots and quantities separately from projections.", count: Array.isArray(session?.farm.inventory) ? session.farm.inventory.length : 0 },
  { view: "proposals", name: "Proposal approvals", detail: "Inspect revision-bound calculations for this session before creating simulated tasks.", count: proposals.length },
  { view: "tasks", name: "Tasks & results", detail: "Record this session's reported outcomes, corrections and recovery triggers.", count: tasks.length },
  { view: "verify", name: "Verify & recover", detail: "Compare this session's farmer-reported outcomes with its saved plan, then explicitly replan future work.", count: tasks.filter(item => item.event_revision > 0).length },
  { view: "history", name: "Workflow history", detail: "Read this session's saved event sequence without recalculation. Older sessions remain in History & preferences.", count: events.length },
]; }
function Home({ workflow, session, index, setIndex, open }: { workflow: FarmerWorkflowState; session: PlanningSession | null; index: number; setIndex: (value: number) => void; open: (view: View) => void }) { const items = homeItems(workflow, session), item = items[index], card = bound(`category:${item.view}`, "records_category", item.name, session, [], [localAction("open", "Open")]); return <><nav className="ir-pager" aria-label="Records and work categories"><button disabled={index === 0} onClick={() => setIndex(index - 1)}><ArrowLeft /> Previous</button><span>Records &amp; work {index + 1} of {items.length}</span><button disabled={index === items.length - 1} onClick={() => setIndex(index + 1)}>Next <ArrowRight /></button></nav><BoundCard card={card} className="ir-card"><div className="ir-card__heading"><div><small>Records &amp; work</small><h3>{item.name}</h3></div><span>{item.count}</span></div><p>{item.detail}</p><div className="tool-category-index" aria-label="Choose records category">{items.map((entry,i)=><button key={entry.view} onClick={()=>{setIndex(i);open(entry.view)}}><strong>{entry.name} · {entry.count}</strong><span>{entry.detail}</span></button>)}</div>{!session && item.view !== "setup" && <p className="ir-note">No planning session is active.</p>}</BoundCard></>; }
function CandidateCard({ item }: { item: FarmerImport }) { const actions: FarmCard["actions"] = [backAction, localAction(item.status === "candidate" ? "review" : "add", item.status === "candidate" ? "Review candidate" : "Add candidate"), localAction("source", "Source")], card = bound(item.candidate_id, "import_candidate", item.source_name, null, [item.source_kind, item.source_name], actions); return <Card card={card} eyebrow={item.source_kind.replaceAll("_", " ")} title={item.source_name} status={item.status}><dl><Fact k="Record identity" v={item.candidate_id} /><Fact k="Authority" v={String(item.authority || "review candidate")} /><Fact k="Planning use" v={item.status === "candidate" ? "Inactive until reviewed" : item.planning_eligible ? "Eligible reviewed evidence" : "Observation only"} /><Fact k="Extracted rows" v={String(item.rows?.length || 0)} /></dl>{!!item.warnings?.length && <div className="ir-warning"><strong>Warnings</strong><ul>{item.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div>}<Rows rows={item.rows || []} /></Card>; }
function SourceReview({ item }: { item: FarmerImport }) { const [error, setError] = useState(""), source = `/farm-workflow/imports/${encodeURIComponent(item.candidate_id)}/source`; const open = (download: boolean) => void requestBlob(download ? `${source}/download` : source).then(blob => openBlob(blob, download ? item.source_name : undefined)).catch(caught => setError(problem(caught, "Source could not be opened."))); return <Card eyebrow="Original import source" title={item.source_name} status="read only"><p>Inspect the retained source and its response metadata before downloading. These actions do not change its review state or planning authority.</p><dl><Fact k="Candidate identity" v={item.candidate_id} /><Fact k="Source kind" v={item.source_kind.replaceAll("_", " ")} /><Fact k="Review state" v={item.status} /></dl>{error && <p className="ir-error" role="alert">{error}</p>}<ActionPortal><button onClick={() => open(false)}>Inspect source</button><button onClick={() => open(true)}>Download source</button></ActionPortal></Card>; }
function CandidateReview({ item, busy, decide }: { item: FarmerImport; busy: boolean; decide: (decision: "confirm" | "reject", note?: string) => void }) { const [note, setNote] = useState(""); return <Card eyebrow="Explicit review" title={item.source_name} status="candidate"><p>Confirm only the extracted fields you have reviewed. Photos and documents remain observations and never gain yield authority.</p><Rows rows={item.rows || []} /><label>Review note (optional)<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><ActionPortal><button disabled={busy} onClick={() => decide("reject", note)}>Reject candidate</button><button className="is-primary" disabled={busy} onClick={() => decide("confirm", note)}>Confirm reviewed fields</button></ActionPortal></Card>; }
function ProposalCard({ item, session }: { item: FarmerProposal; session: PlanningSession | null }) { const stale = session && item.session_id === session.id && item.base_revision > session.revision, actions: FarmCard["actions"] = [backAction]; if (item.status === "applied") actions.push(localAction("approve", "Review approval")); if (item.undo?.available) actions.push(localAction("recovery", "Review recovery")); const card = bound(item.id, "workflow_proposal", String(item.selected_strategy_id || item.id), session, [item.id, String(item.selected_strategy_id || "")], actions, "projection", item.proposal_revision), frozen = item as FarmerProposal & { session_input_hash?: string; result_id?: string; approved_result_id?: string; recalculated_result_id?: string; result_hash?: string }; card.binding.inputHash = frozen.session_input_hash || null; card.binding.resultId = frozen.approved_result_id || frozen.recalculated_result_id || frozen.result_id || null; card.binding.snapshotId = frozen.result_hash || null; return <Card card={card} eyebrow={`Proposal revision ${item.proposal_revision}`} title={String(item.selected_strategy_id || item.id)} status={item.status}><dl><Fact k="Stable proposal ID" v={item.id} /><Fact k="Session ID" v={item.session_id} /><Fact k="Base revision" v={String(item.base_revision)} /></dl><p>Approval creates simulation tasks only.</p>{stale && <p className="ir-warning">The proposal refers to a newer revision than the loaded session.</p>}<Metrics values={item.recalculated_metrics || item.calculated_metrics} />{item.inverse_of_proposal_id && <p>Recovery inverse of {item.inverse_of_proposal_id}.</p>}</Card>; }
function ApprovalReview({ item, busy, approve }: { item: FarmerProposal; busy: boolean; approve: () => void }) { const eligible = item.approval?.available === true; return <Card eyebrow="Approval review" title={`Proposal revision ${item.proposal_revision}`} status={item.status}><p>This explicit approval is bound to proposal {item.id} and creates simulated actions. It does not authorize real farm operations.</p>{!eligible && <p className="ir-warning">{item.approval?.reason || "Server eligibility is not available for this proposal."}</p>}<Metrics values={item.recalculated_metrics || item.calculated_metrics} />{item.metric_deltas && <><strong>Signed changes after recalculation</strong><Metrics values={item.metric_deltas} /></>}<ActionPortal><button className="is-primary" disabled={busy || !eligible} onClick={approve}>{busy ? <LoaderCircle className="spin" /> : <CheckCircle2 />} Approve revision &amp; create tasks</button></ActionPortal></Card>; }
function RecoveryReview({ item, busy, create }: { item: FarmerProposal; busy: boolean; create: () => void }) { return <Card eyebrow="Recovery review" title={`Inverse proposal for revision ${item.proposal_revision}`} status="not created"><p>This creates a new proposal against eligible session revision {item.undo?.expected_session_revision ?? "not supplied"}. It keeps the original proposal, event history and executed work; only future work can change.</p>{item.metric_deltas && <Metrics values={item.metric_deltas} />}<ActionPortal><button className="is-primary" disabled={busy || !item.undo?.available} onClick={create}>{busy ? <LoaderCircle className="spin" /> : <RotateCcw />} Create recovery proposal</button></ActionPortal></Card>; }
function TaskCard({ item, proposal, session }: { item: FarmerTask; proposal?: FarmerProposal; session: PlanningSession | null }) { const canRecord = ["pending", "in_progress"].includes(item.status), actions: FarmCard["actions"] = [backAction]; if (canRecord) actions.push(localAction("record-result", "Record result")); if (item.event_revision > 0) actions.push(localAction("correct-record", "Correct record")); if (item.status === "recovery_required") actions.push(localAction("replan", "Replan future work")); const card = bound(item.id, "workflow_task", item.action.replaceAll("_", " "), session, [item.id, item.proposal_id, String(item.batch_id || "")], actions, item.event_revision > 0 ? "farmer_reported" : "projection", item.event_revision), owner = proposal as (FarmerProposal & { session_input_hash?: string; approved_result_id?: string; result_hash?: string }) | undefined; card.binding.inputHash = owner?.session_input_hash || null; card.binding.resultId = owner?.approved_result_id || null; card.binding.snapshotId = owner?.result_hash || null; return <Card card={card} eyebrow={`Due ${civil(item.due_date)}`} title={`${item.action.replaceAll("_", " ")} · ${item.crop_id || "farm task"}`} status={item.status}><dl><Fact k="Stable task ID" v={item.id} /><Fact k="Location" v={String(item.location || "Not specified")} /><Fact k="Planned" v={item.planned_quantity == null ? "No quantity" : `${item.planned_quantity} ${item.unit || ""}`} /><Fact k="Reported" v={item.actual_quantity == null ? "Not reported" : `${item.actual_quantity} ${item.unit || ""}`} /></dl>{item.recovery?.required && <p className="ir-warning"><strong>Recovery required.</strong> {item.recovery.reason || "Record the outcome; completed work remains in the ledger and only future work may be replanned."}</p>}<ul>{item.checklist.map((entry) => <li key={entry}>{entry}</li>)}</ul><small>Event revision {item.event_revision}</small></Card>; }
function EventCard({ item }: { item: Record<string, unknown> }) { return <Card eyebrow={civil(String(item.occurred_at || item.created_at || item.timestamp || item.date || ""))} title={String(item.event_type || item.type || item.action || "Saved workflow event")} status={String(item.status || "recorded")}><dl>{Object.entries(item).filter(([key]) => !["event_type", "type", "action", "status"].includes(key)).slice(0, 12).map(([key, value]) => <Fact key={key} k={key.replaceAll("_", " ")} v={display(value)} />)}</dl><p className="ir-note">Saved replay only. Opening this card performs no calculation or inference.</p></Card>; }
function OrderCard({ item, session }: { item: FarmOrder; session: PlanningSession | null }) { return <Card card={bound(item.id, "farm_order", `${item.crop_id} commitment`, session, [item.id, item.crop_id], [backAction], "farmer_reported")} eyebrow={`Order · ${item.id}`} title={`${item.crop_id.replaceAll("_", " ")} commitment`} status="confirmed"><dl><Fact k="Stable record ID" v={item.id} /><Fact k="Due date" v={civil(item.due_date)} /><Fact k="Booked quantity" v={`${item.quantity_kg} kg`} /><Fact k="Booked price" v={`SGD ${item.price_sgd_per_kg}/kg`} /></dl><p className="ir-note">This is a confirmed record. Forecast demand and projected delivery remain separate.</p></Card>; }
function BedCard({ item, session }: { item: Bed; session: PlanningSession | null }) { return <Card card={bound(item.id, "grow_space", item.name, session, [item.id, String(item.batch_id || "")], [backAction], "farmer_reported")} eyebrow={`Growing space · ${item.id}`} title={item.name} status={item.stage || "reported"}><dl><Fact k="Stable record ID" v={item.id} /><Fact k="System" v={item.system.replaceAll("_", " ")} /><Fact k="Area" v={`${item.area_m2} m²`} /><Fact k="Reported crop" v={item.crop_id?.replaceAll("_", " ") || "None"} /><Fact k="Batch ID" v={item.batch_id || "None"} /></dl><p className="ir-note">The reported stage is a farm record; future allocations are projections.</p></Card>; }
function InventoryCard({ item, session }: { item: Record<string, unknown>; session: PlanningSession | null }) { const id = String(item.id || item.lot_id || item.batch_id || "identity unavailable"); return <Card card={bound(id, "inventory_lot", String(item.crop_id || item.name || id), session, [id, String(item.batch_id || "")], [backAction], "farmer_reported")} eyebrow={`Inventory lot · ${id}`} title={String(item.crop_id || item.name || "Reported inventory").replaceAll("_", " ")} status={String(item.status || "reported")}><dl><Fact k="Stable record ID" v={id} /><Fact k="Reported quantity" v={`${display(item.quantity_kg ?? item.quantity)} ${String(item.unit || "kg")}`} /><Fact k="Recorded date" v={civil(String(item.harvested_date || item.recorded_at || item.date || ""))} /><Fact k="Expiry" v={civil(String(item.expires_on || item.expiry_date || ""))} /><Fact k="Origin" v={display(item.origin || item.source)} /></dl><p className="ir-note">Reported inventory is shown as recorded and is not a projected harvest.</p></Card>; }
function VerifyCard({ session, tasks, onOpenPlan }: { session: PlanningSession | null; tasks: FarmerTask[]; onOpenPlan?: () => void }) { const report = session?.reported_forecast as { metrics?: Record<string, number | null>; basis?: string; source_result_id?: string; recovery_required?: boolean; independently_verified?: boolean } | undefined, recovery = tasks.filter(item => item.status === "recovery_required"); const metrics = report?.metrics || {}; const selected = Object.fromEntries(["booked_delivered_kg", "booked_shortfall_kg", "rejected_kg", "margin_sgd"].filter(key => key in metrics).map(key => [key, metrics[key]])); return <Card eyebrow="Farmer-reported outcome" title="Verify recorded work and future impact" status={report?.recovery_required ? "recovery required" : report ? "recorded" : "awaiting result"}>{report ? <><p>Server-derived projection from farmer-reported task events. It is not independently verified.</p><Metrics values={selected} /><dl><Fact k="Outcome basis" v={String(report.basis || "user reported projection").replaceAll("_", " ")} /><Fact k="Source result" v={String(report.source_result_id || "Not supplied")} /></dl></> : <p>No reported forecast is available yet. Record a task result before comparing outcome changes.</p>}<p>Completed work and prior events remain recorded. Recovery may change future simulation work only and must start from the current session revision.</p>{recovery.map(item => <p className="ir-warning" key={item.id}><strong>{item.id}</strong> · {item.recovery?.reason || "Reported result requires recovery."}</p>)}{onOpenPlan && recovery.length > 0 && <ActionPortal><button className="is-primary" onClick={onOpenPlan}>Review future-only plan</button></ActionPortal>}</Card>; }

function FarmImportForm({ busy, submit }: { busy: boolean; submit: (farm: unknown, expectedVersion: number) => void }) {
  const [json, setJson] = usePersistentState("v15-farm-json-draft", "");
  const [preview, setPreview] = useState<Record<string, unknown> | null>(null);
  const [current, setCurrent] = useState<Record<string, unknown> | null>(null);
  const [parseError, setParseError] = useState("");
  const [reviewing, setReviewing] = useState(false);
  const expectedVersion = current ? Number(current.version) : null;
  const review = async () => {
    setReviewing(true);
    try {
      const parsed: unknown = JSON.parse(json);
      const farm = typeof parsed === "object" && parsed !== null && "farm" in parsed ? (parsed as { farm: unknown }).farm : parsed;
      if (!farm || typeof farm !== "object" || Array.isArray(farm)) throw new Error("The JSON must contain one farm object.");
      if (new Blob([json]).size > 1_000_000) throw new Error("Farm JSON must be under 1 MB.");
      setCurrent(await currentFarmSnapshot()); setPreview(farm as Record<string, unknown>); setParseError("");
    } catch (caught) { setPreview(null); setCurrent(null); setParseError(problem(caught, "The JSON or current farm snapshot could not be reviewed.")); }
    finally { setReviewing(false); }
  };
  const download = () => void requestBlob("/farms/demo-farm/snapshot").then(blob => openBlob(blob, "farmtact-full-farm-sample.json")).catch(caught => setParseError(problem(caught, "The full-schema farm could not be downloaded.")));
  const summary = (farm: Record<string, unknown>) => <dl><Fact k="Farm ID" v={display(farm.id)} /><Fact k="Name" v={display(farm.name)} /><Fact k="Version" v={display(farm.version)} /><Fact k="Cutoff" v={display(farm.cutoff)} /><Fact k="Timezone" v={display(farm.timezone)} /><Fact k="Planning horizon" v={`${display(farm.horizon_days)} days`} />{["orders", "beds", "batches", "inventory"].map(key => <Fact key={key} k={key} v={Array.isArray(farm[key]) ? String(farm[key].length) : "Missing"} />)}<Fact k="Data origin" v={display(farm.data_mode)} /></dl>;
  const missing = preview ? ["id", "name", "cutoff", "orders", "beds", "recipes", "resources"].filter(key => preview[key] == null) : [];
  return <Card eyebrow="Reviewed farm transition" title={preview ? "Review farm import" : "Paste farm JSON"} status={preview ? "review required" : "draft"}>
    {!preview ? <><p>Paste the complete farm object, or an object with a <code>farm</code> field. Parsing creates a local preview and does not import anything.</p><Field label="Farm JSON"><textarea className="ir-json" value={json} onChange={event => setJson(event.target.value)} spellCheck={false} /></Field>{parseError && <p className="ir-error" role="alert">{parseError}</p>}<ActionPortal><button onClick={download}>Download full-schema farm</button><button className="is-primary" disabled={!json.trim() || reviewing} onClick={() => void review()}>{reviewing ? "Reviewing current version…" : "Review parsed farm"}</button></ActionPortal></>
      : <><p>Source: the exact pasted JSON. Confirmation replaces the current imported farm for a new workflow session. Existing plans, tasks and events remain in their original sessions; no historical edition data is merged.</p><section aria-label="Current farm before import"><h3>Current imported farm</h3>{current && summary(current)}</section><section aria-label="Incoming farm review"><h3>Incoming farm</h3>{summary(preview)}</section><p className="ir-note">Review warnings: {missing.length ? `Missing required fields: ${missing.join(", ")}. ` : "No missing summary fields detected. "}Full schema, crop, date and resource validation occurs on submit. This preview is not a validated or saved farm.</p><p>The server must still match current farm version {expectedVersion}; a changed version requires another review. Back or Edit JSON leaves the current farm untouched.</p><ActionPortal><button disabled={busy} onClick={() => setPreview(null)}>Edit JSON</button><button className="is-primary" disabled={busy || expectedVersion == null} onClick={() => expectedVersion != null && submit(preview, expectedVersion)}>Confirm atomic import</button></ActionPortal></>}
  </Card>;
}
function SeedReview({ busy, submit }: { busy: boolean; submit: (expectedVersion: number) => void }) { const [expectedVersion, setExpectedVersion] = useState<number | null>(null), [error, setError] = useState(""); useEffect(() => { void currentFarmSnapshot().then(value => setExpectedVersion(Number(value.version))).catch(caught => setError(problem(caught, "Current farm version is unavailable."))); }, []); return <Card eyebrow="Farm setup review" title="Load synthetic demo" status="not loaded"><p>This requests the backend’s versioned synthetic demonstration fixture. The server atomically creates the farm version and its separate workflow session after confirmation.</p><dl><Fact k="Fixture" v="synthetic_demo" /><Fact k="Current farm version" v={expectedVersion == null ? "Loading…" : String(expectedVersion)} /><Fact k="Origin" v="Project-authored synthetic records" /><Fact k="Operations" v="Simulation only" /></dl>{error && <p className="ir-error" role="alert">{error}</p>}<ActionPortal><button className="is-primary" disabled={busy || expectedVersion == null} onClick={() => expectedVersion != null && submit(expectedVersion)}>Confirm atomic demo load</button></ActionPortal></Card>; }

function UploadForm({ busy, submit }: { busy: boolean; submit: (file: File) => void }) { const [file, setFile] = useState<File | null>(null), extraction = Boolean(file && (file.type.startsWith("image/") || file.type === "application/pdf")); return <Card eyebrow="New review candidate" title="Import a farm record" status="unsaved"><p>CSV and XLSX accounting candidates are parsed locally. An unencrypted native PDF of at most five pages, or one PNG, JPEG, GIF or WEBP image up to 700 KB and 4096 px, requires one explicit AI extraction request. Every result remains a candidate until review.</p><label>Candidate file<input type="file" accept=".csv,.xlsx,.pdf,image/png,image/jpeg,image/gif,image/webp" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label>{extraction && <p className="ir-warning">Submitting this file invokes one bounded provider extraction request. It remains observation evidence and cannot establish yield.</p>}<ActionPortal><button className="is-primary" disabled={!file || busy} onClick={() => file && submit(file)}>{busy ? <LoaderCircle className="spin" /> : <FileUp />} {extraction ? "Submit for AI extraction" : "Upload accounting candidate"}</button></ActionPortal></Card>; }
function ManualForm({ session, busy, submit }: { session: PlanningSession; busy: boolean; submit: (name: string, row: Record<string, unknown>) => void }) { const [name, setName] = usePersistentState("v15-manual-name", "Farmer manual record"), [date, setDate] = usePersistentState("v15-manual-date", session.farm.planning_date), [kind, setKind] = usePersistentState("v15-manual-kind", "expense"), [reference, setReference] = usePersistentState("v15-manual-reference", `manual-${Date.now()}`), [target, setTarget] = usePersistentState("v15-manual-target", ""), [description, setDescription] = usePersistentState("v15-manual-description", ""), [amount, setAmount] = usePersistentState("v15-manual-amount", ""); const valid = name.trim() && date && reference.trim() && amount !== "" && (kind !== "correction" || target.trim()); return <Card eyebrow="Manual entry" title="Create an unverified candidate" status="unsaved"><p>The record stays inactive until it is reviewed on its own candidate card.</p><div className="ir-form-grid"><Field label="Source name"><input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="Record date"><input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></Field><Field label="Record kind"><select value={kind} onChange={(e) => setKind(e.target.value)}><option value="expense">Expense</option><option value="sale">Sale</option><option value="correction">Correction</option></select></Field><Field label="Record reference"><input value={reference} onChange={(e) => setReference(e.target.value)} /></Field>{kind === "correction" && <Field label="Target transaction reference"><input value={target} onChange={(e) => setTarget(e.target.value)} /></Field>}<Field label="Description (optional)"><input value={description} onChange={(e) => setDescription(e.target.value)} /></Field><Field label={kind === "correction" ? "Signed correction amount (SGD)" : "Amount (SGD)"}><input type="number" min={kind === "correction" ? undefined : "0"} step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} /></Field></div>{kind === "correction" && <p className="ir-note">Use a signed delta and target one distinct reviewed sale or expense reference.</p>}<ActionPortal><button className="is-primary" disabled={!valid || busy} onClick={() => submit(name.trim(), { date, kind, reference: reference.trim(), corrects_reference: kind === "correction" ? target.trim() : undefined, description: description.trim(), amount, currency: "SGD", provenance: "farmer_manual_unverified" })}>Create review candidate</button></ActionPortal></Card>; }
function ResultForm({ task, photos, busy, submit }: { task: FarmerTask; photos: FarmerImport[]; busy: boolean; submit: (v: { status: "completed" | "failed"; quantity: number; rejected: number; note: string; checks: string[]; photo: string }) => void }) { const [status, setStatus] = usePersistentState<"completed" | "failed">(`v15-result-${task.id}-status`, "completed"), [quantity, setQuantity] = usePersistentState(`v15-result-${task.id}-quantity`, Number(task.actual_quantity ?? task.planned_quantity ?? 0)), [rejected, setRejected] = usePersistentState(`v15-result-${task.id}-rejected`, 0), [note, setNote] = usePersistentState(`v15-result-${task.id}-note`, ""), [checks, setChecks] = usePersistentState<string[]>(`v15-result-${task.id}-checks`, []), [photo, setPhoto] = usePersistentState(`v15-result-${task.id}-photo`, ""); return <Card eyebrow="Farmer-reported result" title={task.action.replaceAll("_", " ")} status="unsaved"><p>Reported values remain distinct from projections. Check every entered field before saving. A failed result can trigger recovery while retaining executed work.</p><Field label="Result"><select value={status} onChange={(e) => setStatus(e.target.value as typeof status)}><option value="completed">Completed</option><option value="failed">Blocked or failed</option></select></Field>{task.unit && <Field label={`Actual quantity (${task.unit})`}><input type="number" min="0" step="0.01" value={quantity} onChange={(e) => setQuantity(Number(e.target.value))} /></Field>}{task.action === "delivery" && <Field label="Rejected quantity (kg)"><input type="number" min="0" step="0.01" value={rejected} onChange={(e) => setRejected(Number(e.target.value))} /></Field>}<fieldset><legend>Checklist completed</legend>{task.checklist.map((entry) => <label key={entry}><input type="checkbox" checked={checks.includes(entry)} onChange={(e) => setChecks((old) => e.target.checked ? [...old, entry] : old.filter((value) => value !== entry))} /> {entry}</label>)}</fieldset>{photos.length > 0 && <Field label="Reviewed task photo"><select value={photo} onChange={(e) => setPhoto(e.target.value)}><option value="">No photo</option>{photos.map((item) => <option key={item.candidate_id} value={item.candidate_id}>{item.source_name}</option>)}</select></Field>}<Field label="Farmer note"><textarea required value={note} onChange={(e) => setNote(e.target.value)} /></Field><ActionPortal><button className="is-primary" disabled={!note.trim() || busy} onClick={() => submit({ status, quantity, rejected, note: note.trim(), checks, photo })}>Save reported result</button></ActionPortal></Card>; }
function CorrectionForm({ task, busy, submit }: { task: FarmerTask; busy: boolean; submit: (value: number | string | null, reason: string, field?: string) => void }) { const [field, setField] = usePersistentState(`v15-correction-${task.id}-field`, "actual_quantity"), [value, setValue] = usePersistentState(`v15-correction-${task.id}-value`, String(task.actual_quantity ?? "")), [reason, setReason] = usePersistentState(`v15-correction-${task.id}-reason`, ""); const numeric = field === "actual_quantity" || field === "rejected_quantity"; const corrected: number | string = numeric ? Number(value) : value; return <Card eyebrow={`Correction from event revision ${task.event_revision}`} title="Correct a reported field" status="unsaved"><p>The prior event remains in history. Check the field, corrected value and reason before saving the new auditable event.</p><Field label="Field"><select value={field} onChange={(event) => { setField(event.target.value); setValue(event.target.value === "actual_quantity" ? String(task.actual_quantity ?? "") : event.target.value === "rejected_quantity" ? String(task.rejected_quantity ?? 0) : event.target.value === "note" ? String(task.result_note || "") : event.target.value === "result_status" ? String(task.status) : String(task.unit || "")); }}><option value="actual_quantity">Actual quantity</option><option value="rejected_quantity">Rejected quantity</option><option value="unit">Unit</option><option value="note">Result note</option><option value="result_status">Result status</option></select></Field><Field label="Corrected value">{field === "result_status" ? <select value={value} onChange={(e) => setValue(e.target.value)}><option value="completed">Completed</option><option value="failed">Failed</option><option value="recovery_required">Recovery required</option></select> : <input type={numeric ? "number" : "text"} min={numeric ? "0" : undefined} step={numeric ? "0.01" : undefined} value={value} onChange={(e) => setValue(e.target.value)} />}</Field><Field label="Reason"><input value={reason} onChange={(e) => setReason(e.target.value)} /></Field><ActionPortal><button className="is-primary" disabled={!reason.trim() || !value || (numeric && Number(value) < 0) || busy} onClick={() => submit(corrected, reason.trim(), field)}>Save auditable correction</button></ActionPortal></Card>; }

const backAction: FarmCard["actions"][number] = { id: "back", label: "Back", eligible: true, authority: "local_navigation", eligibilitySource: "local" };
function localAction(id: string, label: string): FarmCard["actions"][number] { return { id, label, eligible: true, authority: "local_navigation", eligibilitySource: "local" }; }
function serverAction(id: string, label: string, eligible = true): FarmCard["actions"][number] { return { id, label, eligible, authority: "server_mutation", eligibilitySource: "local", ...(!eligible ? { disabledReason: "Complete the required fields or wait for the current request." } : {}) }; }
function bound(entityId: string, entityKind: string, title: string, session: PlanningSession | null, provenance: string[], actions: FarmCard["actions"] = [], outcomeBasis: FarmCard["outcomeBasis"] = null, revision = session?.revision ?? null, boardTargets: string[] = []): FarmCard { const result = session?.result as { id?: string; result_id?: string } | null | undefined, targets = entityKind === "grow_space" ? [entityId] : boardTargets; return { id: `records:${entityKind}:${entityId}`, entityId, entityKind, title, provenance: provenance.filter(Boolean), binding: { sessionId: session?.id ?? null, inputHash: session?.input_hash ?? null, revision, resultId: String(result?.result_id || result?.id || session?.tactical_context?.planning_snapshot.result_id || "") || null }, boardTargets: targets, actions, outcomeBasis }; }
function proposalMeta(item: FarmerProposal, session: PlanningSession | null, actions: FarmCard["actions"]): FarmCard { const frozen = item as FarmerProposal & { session_input_hash?: string; result_id?: string; approved_result_id?: string; recalculated_result_id?: string; result_hash?: string }, card = bound(item.id, "workflow_proposal", String(item.selected_strategy_id || item.id), session, [item.id], actions, "projection", item.proposal_revision); card.binding.inputHash = frozen.session_input_hash || null; card.binding.resultId = frozen.approved_result_id || frozen.recalculated_result_id || frozen.result_id || null; card.binding.snapshotId = frozen.result_hash || null; return card; }
function taskMeta(item: FarmerTask, proposal: FarmerProposal | undefined, session: PlanningSession | null, actions: FarmCard["actions"]): FarmCard { const owner = proposal as (FarmerProposal & { session_input_hash?: string; approved_result_id?: string; result_hash?: string }) | undefined, location = String(item.location || ""), isBed = Boolean(session?.farm.beds.some(bed => bed.id === location)), card = bound(item.id, "workflow_task", item.action.replaceAll("_", " "), session, [item.id, item.proposal_id, String(item.batch_id || "")], actions, item.event_revision > 0 ? "farmer_reported" : "projection", item.event_revision, isBed ? [location] : []); card.binding.inputHash = owner?.session_input_hash || null; card.binding.resultId = owner?.approved_result_id || null; card.binding.snapshotId = owner?.result_hash || null; return card; }
function fallbackActions(title: string): FarmCard["actions"] { if (title === "Choose the source for a new farm version") return [backAction, localAction("review-json", "Review farm JSON"), localAction("review-demo", "Review demo load")]; if (title === "Paste farm JSON") return [backAction, localAction("download-schema", "Download full-schema farm"), localAction("review-farm", "Review parsed farm")]; if (title === "Review farm import") return [backAction, localAction("edit-json", "Edit JSON"), serverAction("confirm-import", "Confirm atomic import")]; if (title === "Load synthetic demo") return [backAction, serverAction("confirm-demo", "Confirm atomic demo load", false)]; if (title === "Import a farm record") return [backAction, localAction("manual", "Manual instead"), serverAction("upload-accounting", "Upload accounting candidate", false), serverAction("extract-document", "Submit for AI extraction", false)]; if (title === "Create an unverified candidate") return [backAction, serverAction("create-candidate", "Create review candidate", false)]; return [backAction]; }
function useLiveFooterActions(card: FarmCard, signature: string): FarmCard { const [live, setLive] = useState(card); useEffect(() => { const footer = document.querySelector<HTMLElement>(".integrated-records > .ir-actions"); if (!footer) { setLive(card); return; } const sync = () => { const buttons = Array.from(footer.querySelectorAll<HTMLButtonElement>("button")).filter(button => button.getClientRects().length > 0), actions = buttons.map((button, index) => { const label = button.textContent?.replace(/\s+/g, " ").trim() || `Action ${index + 1}`, declared = card.actions.find(action => action.label === label); return { ...(declared || localAction(`visible-${index}`, label)), eligible: !button.disabled, ...(!button.disabled ? { disabledReason: undefined } : { disabledReason: declared?.disabledReason || "Complete the required fields or wait for the current request." }) }; }); setLive({ ...card, actions }); }; sync(); const observer = new MutationObserver(sync); observer.observe(footer, { subtree: true, childList: true, attributes: true, characterData: true, attributeFilter: ["disabled"] }); return () => observer.disconnect(); }, [signature]); return live; }
function Card({ card, eyebrow, title, status, children }: { card?: FarmCard; eyebrow: string; title: string; status: string; children: ReactNode }) { const contextual = useContext(CardMetaContext), content = <><div className="ir-card__heading"><div><small>{eyebrow}</small><h3>{title}</h3></div><span>{status.replaceAll("_", " ")}</span></div>{children}</>, resolved = card || contextual || bound(`local:${title.toLowerCase().replaceAll(/[^a-z0-9]+/g, "-")}`, "records_local_card", title, null, [eyebrow], fallbackActions(title)), signature = JSON.stringify(resolved), live = useLiveFooterActions(resolved, signature); return <BoundCard card={live} className="ir-card">{content}</BoundCard>; }
function ActionPortal({ children }: { children: ReactNode }) { const [target, setTarget] = useState<HTMLElement | null>(null); useEffect(() => { setTarget(document.getElementById("ir-form-actions")); }, []); return target ? createPortal(children, target) : null; }
function Empty({ icon, text }: { icon: ReactNode; text: string }) { return <div className="ir-empty">{icon}<p>{text}</p></div>; }
function Fact({ k, v }: { k: string; v: string }) { return <div><dt>{k}</dt><dd>{v}</dd></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label>{label}{children}</label>; }
function Rows({ rows }: { rows: Record<string, unknown>[] }) { if (!rows.length) return <p className="ir-note">No structured rows were extracted. Review metadata and warnings before deciding.</p>; return <details><summary>Inspect extracted fields</summary>{rows.map((row, i) => <dl className="ir-row" key={i}>{Object.entries(row).map(([key, value]) => <Fact key={key} k={key.replaceAll("_", " ")} v={display(value)} />)}</dl>)}</details>; }
function Metrics({ values }: { values: Record<string, number | null> }) { return <dl className="ir-metrics">{Object.entries(values).map(([key, value]) => <Fact key={key} k={key.replaceAll("_", " ")} v={value == null ? "Unavailable" : Number(value).toLocaleString(undefined, { maximumFractionDigits: 2 })} />)}</dl>; }
function title(view: View, form: Form) { if (form === "farmImport") return "Review farm JSON"; if (form === "seed") return "Review demo load"; if (form === "upload") return "Import candidate"; if (form === "manual") return "Manual record"; if (form === "candidate") return "Review candidate"; if (form === "approve") return "Review approval"; if (form === "recovery") return "Review recovery"; if (form === "result") return "Record task result"; if (form === "correction") return "Correct task record"; return ({ home: "Records & work", setup: "Farm setup", imports: "Farm records", orders: "Confirmed orders", beds: "Growing spaces", inventory: "Inventory", proposals: "Proposal approvals", tasks: "Tasks & results", verify: "Verify & recover", history: "Workflow history" } as const)[view]; }
function label(view: View) { return ({ setup: "Setup", imports: "Record", orders: "Order", beds: "Bed", inventory: "Lot", proposals: "Proposal", tasks: "Task", verify: "Outcome", history: "Event", home: "Card" } as const)[view]; }
function display(value: unknown): string { if (value == null || value === "") return "Not supplied"; if (typeof value === "object") return JSON.stringify(value); return String(value); }
function civil(value: string) { if (!value) return "Date not recorded"; return value.slice(0, 10); }
function problem(error: unknown, fallback: string) { return error instanceof Error && error.message ? error.message : fallback; }
async function currentFarmSnapshot(): Promise<Record<string, unknown>> { const blob = await requestBlob("/farms/demo-farm/snapshot"); return JSON.parse(await blob.text()) as Record<string, unknown>; }
function openBlob(blob: Blob, downloadName?: string) { const url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; if (downloadName) anchor.download = downloadName; else anchor.target = "_blank"; anchor.rel = "noreferrer"; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
function InlineSourceReview({ item }: { item: FarmerImport }) {
  const [error, setError] = useState("");
  const [text, setText] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [nativeNotice, setNativeNotice] = useState("");
  const source = `/farm-workflow/imports/${encodeURIComponent(item.candidate_id)}/source`;
  const inspect = () => void requestBlob(source).then(async blob => {
    setImageUrl(""); setText(""); setNativeNotice(""); setError("");
    if (blob.type.startsWith("image/")) setImageUrl(await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || "")); reader.onerror = () => reject(reader.error); reader.readAsDataURL(blob); }));
    else if (blob.type.startsWith("text/") || /\.(csv|json|txt)$/i.test(item.source_name)) setText(await blob.text());
    else setNativeNotice("This source format is not rendered inline. Review the extracted/raw rows below and use Download source for the retained original bytes.");
  }).catch(caught => setError(problem(caught, "Source could not be inspected.")));
  const download = () => void requestBlob(`${source}/download`).then(blob => openBlob(blob, item.source_name)).catch(caught => setError(problem(caught, "Source could not be downloaded.")));
  return <Card eyebrow="Original import source" title={item.source_name} status="read only"><p>Inspect the retained source inside this card before downloading. These actions do not change its review state or planning authority.</p><dl><Fact k="Candidate identity" v={item.candidate_id} /><Fact k="Source hash" v={String(item.source_sha256 || "Not supplied")} /><Fact k="Source kind" v={item.source_kind.replaceAll("_", " ")} /><Fact k="Review state" v={item.status} /></dl>{text && <pre className="ir-source-text">{text}</pre>}{imageUrl && <img className="ir-source-image" src={imageUrl} alt={`Retained source ${item.source_name}`} />}{nativeNotice && <p className="ir-note">{nativeNotice}</p>}<Rows rows={item.rows || []} />{error && <p className="ir-error" role="alert">{error}</p>}<ActionPortal><button onClick={inspect}>Inspect source</button><button onClick={download}>Download source</button></ActionPortal></Card>;
}

const FarmImportReviewForm = FarmImportForm;
function usePersistentState<T>(name: string, initial: T) { const key = editionStorageKey(`records:${name}`); const [value, setValue] = useState<T>(() => { try { const saved = localStorage.getItem(key); return saved == null ? initial : JSON.parse(saved) as T; } catch { return initial; } }); useEffect(() => { try { localStorage.setItem(key, JSON.stringify(value)); } catch { /* draft persistence is best effort */ } }, [key, value]); return [value, setValue] as const; }
