import { useEffect, useState } from 'react'
import { farmerWorkflowApi, planningApi, rememberPlanningSession, rememberedPlanningSession, type FarmerAssumptions, type FarmerProposal, type PlanningSession } from '../lib/planning'
import { editionStorageKey } from '../lib/edition'
import { RecordFacts, ToolCard } from './ToolCard'
const blank:FarmerAssumptions={tentative_orders:[],future_demand:[],seasonal:[],order_changes:[],reservations:[]}
export default function IntegratedPlan({onClose}:{onClose:()=>void}){
 const [session,setSession]=useState<PlanningSession|null>(null),[index,setIndex]=useState(0),[view,setView]=useState('index'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[proposal,setProposal]=useState<FarmerProposal|null>(null)
 const [draft,setDraft]=useState(()=>{try{return localStorage.getItem(editionStorageKey('planning-assumptions-draft'))||JSON.stringify(blank,null,2)}catch{return JSON.stringify(blank,null,2)}}),[strategy,setStrategy]=useState('')
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Request interrupted. Review retained.')}finally{setBusy(false)}}
 useEffect(()=>{void act(async()=>{const list=await planningApi.list();const saved=rememberedPlanningSession();const s=list.sessions.find(s=>s.id===saved&&s.workflow)||list.sessions.find(s=>s.workflow);setSession(s||null);setStrategy(s?.selected_strategy_id||s?.result?.strategies?.[0]?.id||'')})},[])
 useEffect(()=>{try{localStorage.setItem(editionStorageKey('planning-assumptions-draft'),draft)}catch{}},[draft])
 useEffect(()=>{if(!session||!['QUEUED','RUNNING'].includes(session.job?.status||''))return;const timer=window.setInterval(()=>void planningApi.get(session.id).then(setSession).catch(e=>setError(e instanceof Error?e.message:'Status unavailable')),2000);return()=>window.clearInterval(timer)},[session?.id,session?.job?.status])
 const labels=['Objectives & all demand','Strategies & schedules','Resources & assumptions','Proposals & recalculation','New planning attempt']
 const strategies=session?.result?.strategies||[]
 const back=()=>view==='index'?onClose():setView('index')
 let title=labels[index],body=<p>Calculate from the ordinary farm with all supported local strategies.</p>,label='Open',action=()=>setView(['objectives','strategies','assumptions','proposals','new'][index]),secondary: {label:string;run:()=>void}|undefined
 if(view==='objectives'){title='Objectives and all demand';body=<><p>All confirmed orders and modeled demand stay in the calculation. One introductory objective never filters the plan.</p><RecordFacts value={session?.farm.orders}/><RecordFacts value={session?.farm.resources}/></>;label=session?.result||['QUEUED','RUNNING'].includes(session?.job?.status||'')?'Refresh':'Calculate locally';action=()=>void act(async()=>{if(session)setSession(session.result||['QUEUED','RUNNING'].includes(session.job?.status||'')?await planningApi.get(session.id):await planningApi.calculate(session.id,session.revision))})}
 if(view==='objectives'&&['QUEUED','RUNNING'].includes(session?.job?.status||''))secondary={label:'Review cancellation',run:()=>setView('cancel')}
 if(view==='cancel'){title='Review calculation cancellation';body=<><p>Cancel the active local calculation. Saved results and history remain available. A replacement calculation requires an explicit action.</p><RecordFacts value={session?.job}/></>;label='Cancel active calculation';action=()=>void act(async()=>{if(session)setSession(await planningApi.cancel(session.id,session.revision));setView('objectives')})}
 if(view==='strategies'){title='Strategies & allocation schedules';const selected=strategies.find(s=>s.id===strategy);body=<><label>Compare strategy<select value={strategy} onChange={e=>setStrategy(e.target.value)}>{strategies.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><p>Preview—not saved. Projected outcomes from result {String(session?.result_id||'not calculated')}.</p><RecordFacts value={selected?.metrics}/><RecordFacts value={selected?.violations}/><RecordFacts value={selected?.allocations}/></>;label='Prepare proposal';action=()=>{setDraft(JSON.stringify({...blank,...session?.assumptions},null,2));setView('assumptions')}}
 if(view==='assumptions'||view==='review'){title=view==='review'?'Review planning changes':'Resource & demand assumptions';body=<><p>Supported changes: tentative orders, future demand, seasonal yield/delay assumptions, confirmed order edits, dated bed reservations, nursery/labour/cash capacity. Values are validated by the server. Only four existing crop recipes are modeled.</p><label>Selected strategy<select value={strategy} onChange={e=>setStrategy(e.target.value)}>{strategies.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{view==='review'?<pre style={{whiteSpace:'pre-wrap'}}>{draft}</pre>:<label>Planning assumptions JSON<textarea rows={14} value={draft} onChange={e=>setDraft(e.target.value)}/></label>}<p>Farm {session?.farm.name} · revision {session?.revision}. Applying queues a local recalculation.</p></>;label=view==='review'?'Create proposal':'Review';action=()=>void act(async()=>{const value=JSON.parse(draft) as FarmerAssumptions;if(!session)return;if(view==='review'){setProposal(await farmerWorkflowApi.createProposal(session,strategy,value));setView('proposal')}else setView('review')})}
 if(view==='proposals'){title='Saved proposals';body=<p>Review current proposals and their server-derived metrics. Apply is separate from creating a draft.</p>;label='Load latest proposal';action=()=>void act(async()=>{const state=await farmerWorkflowApi.state();setProposal([...state.proposals].reverse().find(p=>p.session_id===session?.id)||null);setView('proposal')})}
 if(view==='proposal'){title='Proposal and recalculation';body=<><RecordFacts value={proposal}/><p>Only server-confirmed state is saved. Refresh reconciles an interrupted operation.</p></>;label=proposal?.status==='draft'?'Apply & recalculate':'Refresh result';action=()=>void act(async()=>{if(!proposal||!session)return;if(proposal.status==='draft')await farmerWorkflowApi.applyProposal(proposal);setSession(await planningApi.get(session.id));const state=await farmerWorkflowApi.state();setProposal(state.proposals.find(p=>p.id===proposal.id)||null)});secondary={label:'Review assumptions',run:()=>setView('assumptions')}}
 if(view==='new'){title='Review new planning attempt';body=<p>This creates another frozen planning session from the current imported farm. Previous plans, tasks and history remain recorded. The server limits the number of saved sessions.</p>;label='Create new attempt';action=()=>void act(async()=>{const next=await planningApi.create('New integrated planning attempt',true);rememberPlanningSession(next.id);setSession(next);setView('objectives')})}
 return <ToolCard title={title} onBack={back} primary={{label,run:action,disabled:!session}} secondary={secondary} previous={view==='index'&&index>0?()=>setIndex(index-1):undefined} next={view==='index'&&index<labels.length-1?()=>setIndex(index+1):undefined} position={`${index+1} of ${labels.length}`} busy={busy} error={error}>{body}</ToolCard>
}
