import { CURRENT_EDITION } from '../lib/edition'
import { useEffect, useRef, useState } from 'react'
import { api, simulationEventHistory, type SimulationWorld } from '../lib/api'
import { planningApi, farmerWorkflowApi, rememberPlanningSession, type PlanningSession } from '../lib/planning'
import { ToolCard, RecordFacts } from './ToolCard'
import { AudioControls } from './AudioControls'
import { editionStorageKey } from '../lib/edition'
import { staticToolCard, cardString, cardRevision, cardRecord, cardReferences, toolCardActions } from '../lib/cardProjection'
import { useCardView } from '../lib/cardNavigation'
import type { HistoryTarget } from '../lib/cards'
export default function IntegratedHistory({onClose,initialTarget}:{onClose:()=>void;initialTarget?:HistoryTarget}){
 const [index,setIndex]=useState(0),[view,setView,restoreView,captureView]=useCardView(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[rows,setRows]=useState<Array<{id:string;name:string;value:unknown}>>([]),[record,setRecord]=useState<unknown>(null),[world,setWorld]=useState<SimulationWorld|null>(null),[plan,setPlan]=useState<PlanningSession|null>(null),[version,setVersion]=useState('')
 const [motion,setMotion]=useState(()=>{try{return localStorage.getItem(editionStorageKey('reduced-motion'))==='true'}catch{return false}})
 const [attemptFarm,setAttemptFarm]=useState<unknown>(null)
 const newest=(values:Array<{id:string;name:string;value:unknown}>)=>values.sort((a,b)=>{const stamp=(v:unknown)=>{const r=cardRecord(v);return Date.parse(String(r.updated_at||r.occurred_at||r.created_at||''))||0};return stamp(b.value)-stamp(a.value)||b.id.localeCompare(a.id)})
 const labels=['Saved plans','Discussions','Simulations','Event history','Accessibility & audio','Help']
 const act=async(fn:()=>Promise<void>)=>{captureView();setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Could not load saved history')}finally{setBusy(false)}}
 useEffect(()=>{document.documentElement.dataset.reducedMotion=String(motion);try{localStorage.setItem(editionStorageKey('reduced-motion'),String(motion))}catch{}},[motion])
 const open=(section=index)=>void act(async()=>{setIndex(section);setItem(0);if(section===4){setView('preferences');return}if(section===5){setView('help');return}if(section===0)setRows(newest((await planningApi.list()).sessions.map(p=>({id:p.id,name:String(p.name||p.id),value:p}))));if(section===1)setRows(newest((await api.conversations()).map(c=>({id:c.id,name:c.title||c.id,value:c}))));if(section===2)setRows(newest((await api.simulations()).map(s=>({id:s.id,name:`${s.clock_date||'Not started'} · ${s.status}`,value:s}))));if(section===3)setRows((await farmerWorkflowApi.state()).events.slice().reverse().map(e=>({id:`${e.subject_id}:${e.sequence}`,name:`${e.event_type||'Event'} · ${e.occurred_at||''}`,value:e})));setView('list')})
 const [days,setDays]=useState<1|7>(1)
 const [item,setItem]=useState(0)
 const targetOpened=useRef(false)
 useEffect(()=>{if(targetOpened.current||!initialTarget)return;targetOpened.current=true;const selected=['plans','discussions','simulations','events','preferences','help'].indexOf(initialTarget);if(selected>=0)open(selected)},[initialTarget])
 const load=()=>void act(async()=>{const row=rows[item];if(!row)return;setWorld(null);setPlan(null);if(index===0){const p=await planningApi.get(row.id);setPlan(p);setRecord(p)}else if(index===1)setRecord(await api.conversationReplay(row.id));else if(index===2){const w=await api.simulation(row.id);setWorld(w);setRecord({world:w,events:await simulationEventHistory(row.id)})}else setRecord(row.value);setView('replay')})
 let title=labels[index],body=<p>Read saved facts without recalculation or inference.</p>,primary:{label:string;run:()=>void;disabled?:boolean}|undefined={label:'Open',run:()=>open()},secondary:{label:string;run:()=>void}|undefined,count=labels.length,pos=index
 if(view==='index'){body=<><p>Pick a saved record or preference. Reading history never reruns a calculation or adviser.</p><div className="tool-category-index" aria-label="History categories">{labels.map((label,i)=><button key={label} disabled={busy} onClick={()=>open(i)}><strong>{label}</strong><span>{['Compare stored plans and inspect frozen versions','Read full saved adviser conversations','Inspect recorded delivery, inventory and clock events','Trace reviewed changes, approvals and corrections','Choose reduced motion and sound','Learn previews, planning, advisers and experiments'][i]}</span></button>)}</div></>}
 let prev=()=>setIndex(index-1),next=()=>setIndex(index+1)
 if(view==='list'){title=labels[index];const entry=cardRecord(rows[item]?.value);body=<><h3>{rows[item]?.name||'No saved records'}</h3><p>{rows[item]?.id}</p><RecordFacts value={{type:['planning session','discussion','simulation','workflow event'][index],status:entry.status||entry.event_type||'Recorded',revision:entry.revision??entry.sequence??null,effective_date:entry.clock_date||entry.occurred_at||entry.updated_at||entry.created_at||null,result_id:entry.result_id||null,snapshot:entry.snapshot_ref||entry.snapshot_id||null,provenance:entry.input_hash||entry.provenance||entry.run_id||null}}/></>;primary={label:'Read-only replay',run:load,disabled:!rows[item]};count=rows.length;pos=item;prev=()=>setItem(item-1);next=()=>setItem(item+1)}
 if(view==='replay'){title='Read-only saved replay';body=<><p>Recorded data. Reading this card makes no provider calls or farm mutations.</p><RecordFacts value={record}/></>;count=0;primary=undefined;if(world)secondary={label:'Review time advance',run:()=>setView('advance')};else if(plan){primary={label:'Saved versions',run:()=>{setVersion(String(plan.history?.[0]?.result_id||''));setView('versions')}};secondary={label:'New attempt',run:()=>void act(async()=>{setAttemptFarm((await api.bootstrap()).farm);setView('newAttempt')})}}}
 if(view==='versions'){title='Frozen planning versions';count=0;body=<><p>Each result is an immutable numerical snapshot. Replay never recalculates.</p><label>Saved result<select value={version} onChange={e=>setVersion(e.target.value)}>{plan?.history?.map(h=><option key={String(h.result_id)} value={String(h.result_id)}>{String(h.created_at)} · {String(h.kind)} · {String(h.result_id)}</option>)}</select></label></>;primary={label:'Replay saved result',disabled:!version,run:()=>void act(async()=>{if(plan){setRecord(await planningApi.replayResult(plan.id,version));setView('replay')}})};secondary={label:'Review time advance',run:()=>setView('advance')}}
 if(view==='advance'){title='Review sandbox clock advance';count=0;body=<><p>Explicitly advance {days} simulated {days===1?'day':'days'} for {world?.id||plan?.id}. This appends simulation events and may change inventory and deliveries. No actual farm operation is authorized.</p><label>Days to advance<select value={days} onChange={e=>setDays(Number(e.target.value) as 1|7)}><option value={1}>One day</option><option value={7}>Seven days</option></select></label></>;primary={label:days===1?'Advance one day':'Advance seven days',run:()=>void act(async()=>{if(world){const w=await api.advanceSimulation(world.id,world.revision,days);setWorld(w);setRecord({world:w,events:await simulationEventHistory(w.id)})}else if(plan){const p=await planningApi.advance(plan.id,plan.revision,days);setPlan(p);setRecord(p)}setView('replay')})}}
 if(view==='newAttempt'){title='Review a new planning attempt';count=0;body=<><p>Create a separate planning session from the current imported farm shown below. The saved replay and its historical inputs remain unchanged. This does not copy an old result into current records or start a calculation.</p><RecordFacts value={attemptFarm}/></>;primary={label:'Create new attempt',run:()=>void act(async()=>{const created=await planningApi.create('New attempt from saved plan review',true);rememberPlanningSession(created.id);setPlan(created);setWorld(null);setRecord(created);setView('replay')})}}
 if(view==='preferences'){title='Accessibility & audio';count=0;body=<><label><input type="checkbox" checked={motion} onChange={e=>setMotion(e.target.checked)}/>Reduced motion</label><p>Saved consequences remain available as text. System reduced-motion settings are also respected.</p><AudioControls editionKey={CURRENT_EDITION}/></>;primary=undefined}
 if(view==='help'){title='Using FarmTact';count=0;body=<><p>Read a card, swipe horizontally or use Previous/Next to compare, then act beneath it. Arrow keys work on the card surface; forms keep native keyboard behavior.</p><p>Every calculated plan has a compact decision brief. It names affected grow spaces, shows key outcome measures and keeps dated allocations behind Decision details. Preview is not saved. Projected plans, recorded simulation outcomes and farmer-reported work are different kinds of evidence. Explain uses stored facts.</p><p>The emphasized Council action is optional: it opens recorded findings when they exist, or explicitly submits the frozen plan for advisory review through the validated gateway. Council cannot change assumptions, approve work or invoke a physical operation. Only that explicit submission invokes an adviser.</p><p>You can skip or resume guidance without losing access to any tool. More shows a tools index: Plan; Records & work; Knowledge & evidence (crop library, sources and advisers); Experiments (Data Explorer, scenarios and Council research); History & preferences. The category pickers let you jump directly; sequential navigation is optional. Reviewed imports create a separate planning attempt; historical edition data stays separate.</p><p>Planning Council reviews your ordinary frozen plan. Council research is a separate optional study: discussion → reviewed edit → calculation → challenge → saved result. Neither a saved answer nor an adviser portrait means a new AI call has happened.</p><p>For voice typing, use your device keyboard’s microphone. There is no custom recording or transcription integration.</p><p>If interrupted, retain your draft and refresh saved state before retrying. Respect any rate-limit wait. Actual farm operations are disabled.</p></>;primary=undefined}
 const card=staticToolCard('history',view==='index'?labels[index]:view,title)
 const row=rows[item], saved=cardRecord(view==='list'?row?.value:record), activeWorld=view==='list'?null:world, activePlan=view==='list'?null:plan
 const frozenResult=saved.replay===true?cardString(saved.result_id):null
 const frozenHistory=activePlan?.history?.find(entry=>entry.result_id===frozenResult)
 if(['list','replay','versions','advance'].includes(view)&&row){
  card.entityKind=['planning_session','conversation','simulation','event'][index]||'saved_record'
  card.entityId=frozenResult||activeWorld?.id||activePlan?.id||cardString(saved.id)||row.id
  if(frozenResult)card.entityKind='planning_result'
  card.id=`history:${view}:${card.entityKind}:${card.entityId}`
  card.binding={sessionId:activePlan?.id||cardString(saved.session_id)||(index===0?row.id:null),inputHash:frozenResult?cardString(frozenHistory?.input_hash):activePlan?.input_hash||cardString(saved.input_hash),revision:frozenResult?null:activeWorld?.revision??activePlan?.revision??cardRevision(saved.revision)??(index===3?cardRevision(saved.sequence):null),resultId:frozenResult||cardString(activePlan?.result_id)||cardString(saved.result_id),snapshotId:cardString(saved.snapshot_id)}
  card.provenance=cardReferences(saved.snapshot_ref,saved.provenance,frozenResult?frozenHistory?.input_hash:activePlan?.input_hash,activeWorld?.run_id)
  card.boardTargets=activeWorld?.scene_transition?.entity_ids||[]
  card.outcomeBasis=activeWorld||index===2?'recorded_simulation':index===0?'projection':null
 }
 card.actions=toolCardActions(primary,secondary,busy,['Advance one day','Advance seven days','Create new attempt'])
 return <ToolCard card={card} title={title} onBack={()=>{if(view==='index'||(initialTarget&&((view==='list'&&!['preferences','help'].includes(initialTarget))||view===initialTarget)))onClose();else if(view==='advance'||view==='versions'||view==='newAttempt')restoreView('replay');else if(view==='replay')restoreView('list');else{restoreView('index');setItem(0)}}} primary={primary} secondary={secondary} previous={count&&pos>0?prev:undefined} next={count&&pos<count-1?next:undefined} position={count?`${pos+1} of ${count}`:undefined} busy={busy} error={error}>{body}</ToolCard>
}
