import { useEffect, useState } from 'react'
import { farmerWorkflowApi, planningApi, rememberPlanningSession, rememberedPlanningSession, type FarmerAssumptions, type FarmerProposal, type PlanningSession } from '../lib/planning'
import { editionStorageKey } from '../lib/edition'
import { staticToolCard, cardString, cardReferences, toolCardActions } from '../lib/cardProjection'
import { useCardView } from '../lib/cardNavigation'
import { RecordFacts, ToolCard } from './ToolCard'
import PlanningAssumptionFields from './PlanningAssumptionFields'
const blank:FarmerAssumptions={tentative_orders:[],future_demand:[],seasonal:[],order_changes:[],reservations:[]}
function parsedSettings(raw:string):FarmerAssumptions|null {
 try {const value=JSON.parse(raw);if(!value||typeof value!=='object'||Array.isArray(value))return null;
  for(const key of ['tentative_orders','future_demand','seasonal','order_changes','reservations'])if(value[key]!==undefined&&(!Array.isArray(value[key])||value[key].some((row:unknown)=>!row||typeof row!=='object'||Array.isArray(row))))return null;
  if(value.capacity!=null&&(typeof value.capacity!=='object'||Array.isArray(value.capacity)))return null;
  return {...blank,...value};
 } catch{return null}
}
export default function IntegratedPlan({onClose}:{onClose:()=>void}){
 const [session,setSession]=useState<PlanningSession|null>(null),[index,setIndex]=useState(0),[view,setView,restoreView,captureView]=useCardView(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[proposal,setProposal]=useState<FarmerProposal|null>(null)
 const [assumptionsOrigin,setAssumptionsOrigin]=useState('index')
 const [draft,setDraft]=useState(()=>{try{return localStorage.getItem(editionStorageKey('planning-assumptions-draft'))||JSON.stringify(blank,null,2)}catch{return JSON.stringify(blank,null,2)}}),[strategy,setStrategy]=useState('')
 const act=async(fn:()=>Promise<void>)=>{captureView();setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Request interrupted. Review retained.')}finally{setBusy(false)}}
 useEffect(()=>{void act(async()=>{const list=await planningApi.list();const saved=rememberedPlanningSession();const s=list.sessions.find(s=>s.id===saved&&s.workflow)||list.sessions.find(s=>s.workflow);setSession(s||null);setStrategy(s?.selected_strategy_id||s?.result?.strategies?.[0]?.id||'')})},[])
 useEffect(()=>{try{localStorage.setItem(editionStorageKey('planning-assumptions-draft'),draft)}catch{}},[draft])
 useEffect(()=>{if(!session||!['QUEUED','RUNNING'].includes(session.job?.status||''))return;const timer=window.setInterval(()=>void planningApi.get(session.id).then(setSession).catch(e=>setError(e instanceof Error?e.message:'Status unavailable')),2000);return()=>window.clearInterval(timer)},[session?.id,session?.job?.status])
 const labels=['Objectives & all demand','Strategies & schedules','Resources & assumptions','Proposals & recalculation','New planning attempt']
 const strategies=session?.result?.strategies||[]
 const settings=parsedSettings(draft)
 const back=()=>view==='index'?onClose():restoreView(view==='comparison'?'strategies':view==='review'?'assumptions':view==='assumptions'?assumptionsOrigin:view==='cancel'?'objectives':'index')
 let title=labels[index],body=<p>Calculate from the ordinary farm with all supported local strategies.</p>,label='Open',action=()=>{setAssumptionsOrigin('index');setView(['objectives','strategies','assumptions','proposals','new'][index])},secondary: {label:string;run:()=>void}|undefined
 if(view==='objectives'){title='Objectives and all demand';body=<><p>All confirmed orders and modeled demand stay in the calculation. One introductory objective never filters the plan.</p><dl className="record-facts"><div><dt>Planning date</dt><dd>{session?.farm.cutoff ? new Intl.DateTimeFormat('en-CA',{timeZone:session.farm.timezone}).format(new Date(session.farm.cutoff)) : 'Not available'}</dd></div><div><dt>Planning horizon</dt><dd>{session?.farm.horizon_days ?? 'Not available'} days</dd></div><div><dt>Confirmed demand after cancellations</dt><dd>{(session?.farm.orders || []).reduce((total,order)=>total+Number(order.quantity_kg)-Number(order.cancelled_kg||0),0).toLocaleString(undefined,{maximumFractionDigits:3})} kg</dd></div><div><dt>Tentative demand (separate from confirmed orders)</dt><dd>{(session?.assumptions?.tentative_orders || []).reduce((total,order)=>total+Number(order.quantity_kg||0),0).toLocaleString(undefined,{maximumFractionDigits:3})} kg</dd></div></dl><h3>Confirmed orders</h3><RecordFacts value={session?.farm.orders}/><h3>Tentative and future demand assumptions</h3><RecordFacts value={{tentative_orders:session?.assumptions?.tentative_orders||[],future_demand:session?.assumptions?.future_demand||[]}}/><h3>Available resources</h3><RecordFacts value={session?.farm.resources}/></>;label=session?.result||['QUEUED','RUNNING'].includes(session?.job?.status||'')?'Refresh':'Calculate locally';action=()=>void act(async()=>{if(session)setSession(session.result||['QUEUED','RUNNING'].includes(session.job?.status||'')?await planningApi.get(session.id):await planningApi.calculate(session.id,session.revision))})}
 if(view==='objectives'&&!['QUEUED','RUNNING'].includes(session?.job?.status||''))secondary={label:'Review demand changes',run:()=>{setAssumptionsOrigin('objectives');setDraft(JSON.stringify({...blank,...session?.assumptions},null,2));setView('assumptions')}}
 if(view==='objectives'&&['QUEUED','RUNNING'].includes(session?.job?.status||''))secondary={label:'Review cancellation',run:()=>setView('cancel')}
 if(view==='cancel'){title='Review calculation cancellation';body=<><p>Cancel the active local calculation. Saved results and history remain available. A replacement calculation requires an explicit action.</p><RecordFacts value={session?.job}/></>;label='Cancel active calculation';action=()=>void act(async()=>{if(session)setSession(await planningApi.cancel(session.id,session.revision));setView('objectives')})}
 if(view==='strategies'){title='Strategies & allocation schedules';const selected=strategies.find(s=>s.id===strategy);body=<><label>Compare strategy<select value={strategy} onChange={e=>setStrategy(e.target.value)}>{strategies.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><p>Preview—not saved. Projected outcomes from result {String(session?.result_id||'not calculated')}.</p><p>Planning status: <strong>{selected?.status || "Not calculated"}</strong>. Only a feasible current result can be approved for sandbox work.</p><h3>Projected metrics</h3><RecordFacts value={selected?.metrics}/><h3>Constraint findings</h3><RecordFacts value={selected?.violations}/><h3>Dated bed allocations</h3><RecordFacts value={selected?.allocations}/></>;label='Prepare proposal';action=()=>{setAssumptionsOrigin('strategies');setDraft(JSON.stringify({...blank,...session?.assumptions},null,2));setView('assumptions')}}
 if(view==='strategies'&&session?.result?.retained_strategy)secondary={label:'Compare retained schedule',run:()=>setView('comparison')}
 if(view==='comparison'){title='Compare the retained schedule';body=<><p>The previous schedule is re-evaluated against the same revised inputs. Differences below come from the saved numerical result; opening this card does not recalculate.</p><h3>Retained schedule</h3><RecordFacts value={session?.result?.retained_strategy}/><h3>Changed allocations and metrics</h3><RecordFacts value={session?.result?.comparisons}/></>;label='Back to strategies';action=()=>setView('strategies')}
 if(view==='assumptions'||view==='review'){title=view==='review'?'Review planning changes':'Resource & demand assumptions';body=<><p>Set available resources and review optional demand, seasonal and bed changes. Empty groups keep the existing baseline. Only the four existing crop recipes are modeled; these are projected planning inputs.</p><label>Selected strategy<select value={strategy} onChange={e=>setStrategy(e.target.value)}>{strategies.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{view==='review'?<RecordFacts value={settings}/>:<>{session&&settings?<PlanningAssumptionFields session={session} value={settings} onChange={value=>setDraft(JSON.stringify(value,null,2))}/>:<p role="alert">The imported settings need valid lists of planning entries before they can be edited.</p>}<details><summary>Import saved settings</summary><p>Optional: paste previously exported planning settings. Review them before creating a proposal.</p><label>Planning assumptions JSON<textarea rows={10} value={draft} onChange={e=>setDraft(e.target.value)}/></label></details></>}<p>Farm {session?.farm.name} · revision {session?.revision}. Applying queues a local recalculation.</p></>;label=view==='review'?'Create proposal':'Review';action=()=>void act(async()=>{const value=parsedSettings(draft);if(!value)throw new Error('Settings must be an object containing lists of planning entries.');if(!session)return;if(view==='review'){setProposal(await farmerWorkflowApi.createProposal(session,strategy,value));setView('proposal')}else setView('review')})}
 if(view==='proposals'){title='Saved proposals';body=<p>Review current proposals and their server-derived metrics. Apply is separate from creating a draft.</p>;label='Load latest proposal';action=()=>void act(async()=>{const state=await farmerWorkflowApi.state();setProposal([...state.proposals].reverse().find(p=>p.session_id===session?.id)||null);setView('proposal')})}
 if(view==='proposal'){title='Proposal and recalculation';body=<><RecordFacts value={proposal}/><p>Only server-confirmed state is saved. Refresh reconciles an interrupted operation.</p></>;label=proposal?.status==='draft'?'Apply & recalculate':'Refresh result';action=()=>void act(async()=>{if(!proposal||!session)return;if(proposal.status==='draft')await farmerWorkflowApi.applyProposal(proposal);setSession(await planningApi.get(session.id));const state=await farmerWorkflowApi.state();setProposal(state.proposals.find(p=>p.id===proposal.id)||null)});secondary={label:'Review assumptions',run:()=>{setAssumptionsOrigin('proposal');setView('assumptions')}}}
 if(view==='new'){title='Review new planning attempt';body=<p>This creates another frozen planning session from the current imported farm. Previous plans, tasks and history remain recorded. The server limits the number of saved sessions.</p>;label='Create new attempt';action=()=>void act(async()=>{const next=await planningApi.create('New integrated planning attempt',true);rememberPlanningSession(next.id);setSession(next);setView('objectives')})}
 const card=staticToolCard('plan',view==='index'?labels[index]:view,title)
 if(session&&view!=='index'){
  const selected=view==='strategies'?strategies.find(s=>s.id===strategy):null
  card.entityId=view==='proposal'&&proposal?proposal.id:selected?.id||session.id
  card.entityKind=view==='proposal'&&proposal?'proposal':selected?'strategy':'planning_session'
  card.id=`plan:${view}:${card.entityId}`
  card.binding=view==='proposal'&&proposal?{sessionId:proposal.session_id,inputHash:cardString(proposal.session_input_hash),revision:proposal.proposal_revision,resultId:cardString(proposal.result_id)}:{sessionId:session.id,inputHash:session.input_hash,revision:session.revision,resultId:cardString(session.result_id)}
  card.provenance=view==='proposal'&&proposal?cardReferences(proposal.session_input_hash,proposal.result_hash,proposal.explanation?.evidence,proposal.discussion):cardReferences(session.input_hash,session.result_id)
  card.boardTargets=selected?.allocations.map(a=>a.bed_id)||[]
  card.outcomeBasis='projection'
 }
 card.actions=toolCardActions({label,disabled:!session},secondary,busy,['Calculate locally','Cancel active calculation','Create proposal','Apply & recalculate','Create new attempt'])
 return <ToolCard card={card} title={title} onBack={back} primary={{label,run:action,disabled:!session}} secondary={secondary} previous={view==='index'&&index>0?()=>setIndex(index-1):undefined} next={view==='index'&&index<labels.length-1?()=>setIndex(index+1):undefined} position={`${index+1} of ${labels.length}`} busy={busy} error={error}>{body}</ToolCard>
}
