import {useEffect,useState} from 'react'
import {ArrowLeft, ChevronDown, ExternalLink, Monitor, Smartphone} from 'lucide-react'

type Evidence={id:string;type:string;path:string;description:string}
type Finding={severity:string;title:string;observation:string;impact:string;recommendation:string;evidence_ids:string[]}
type Score={criterion:string;score:number|null;rationale:string;evidence_ids:string[]}
type Review={id:string;persona:string;reviewer_type:string;reviewer_agent:string;disclosure:string;reviewed_at:string;build:unknown;rubric_status:string;rubric_source:string;rubric_scores:Score[];usability_score:number|null;summary:string;strengths:string[];findings:Finding[];journeys:{id:string;device:string;viewport:unknown;steps:string[];outcome:string;observations:string[]}[];evidence:Evidence[];limitations:string[];priority_improvements:string[];retest?:{summary:string;build:unknown;observations:string[]}}
type Panel={title:string;published_at:string;release_notes?:string[];methodology:string[];rubric:{source_url:string;page:number;criteria:string[];scoring:string};reviews:Review[]}
const printable=(value:unknown)=>typeof value==='string'?value:JSON.stringify(value)
export function ReviewPage(){
 const [panel,setPanel]=useState<Panel|null>(null),[error,setError]=useState(''),[role,setRole]=useState('all'),[severity,setSeverity]=useState('all'),[query,setQuery]=useState('')
 useEffect(()=>{const c=new AbortController();void fetch('/api/v1/reviews',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('The review panel is unavailable.');setPanel(await r.json())}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[])
 const reviews=(panel?.reviews||[]).filter(r=>(role==='all'||r.reviewer_type===role)&&(!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase())))
 const linkEvidence=(review:Review,ids:string[])=><span className="review-evidence-links">{ids.map(id=><a key={id} href={`#${review.id}-${id}`} onClick={()=>document.getElementById(`${review.id}-${id}`)?.closest("details")?.setAttribute("open","")}>{id}</a>)}</span>
 return <main className="review-page"><a className="review-back" href="/"><ArrowLeft size={18}/> Play FarmTact</a>
  <header className="review-hero"><p className="kicker">Public review room</p><h1>Ten perspectives.<br/>Evidence you can inspect.</h1><p>Independent AI reviewer personas play FarmTact, grade what they can observe, and explain what would make it more useful.</p><div className="review-disclosure">These are agent-generated assessments, not official hackathon results, real farmer testimonials, or a human user study.</div></header>
  {error&&<p role="alert">{error} <a href="/review">Retry</a></p>}{!panel&&!error&&<p role="status">Loading published reviews…</p>}
  {panel&&<>
   <section className="review-intro"><div><p className="kicker">How to read this panel</p><h2>{panel.reviews.length} independent reviewers</h2><p><Smartphone size={16}/> Mobile web <Monitor size={16}/> Desktop web</p><p>Published {new Date(panel.published_at).toLocaleDateString('en-SG',{timeZone:'UTC',day:'numeric',month:'long',year:'numeric'})}. Each review identifies its tested build, journeys, evidence and limitations.</p></div><details><summary>Method, source rubric and scoring <ChevronDown size={16}/></summary>{panel.methodology.map((t,i)=><p key={i}>{t}</p>)}<p><a href={panel.rubric.source_url} target="_blank" rel="noreferrer">ShowMeYourAgent briefing · page {panel.rubric.page} <ExternalLink size={14}/></a></p><p>{panel.rubric.scoring}</p></details></section>
   <section className="review-scorecard"><h2>Rubric coverage and scores</h2><p>Means use only scored reviews. “Untested” is excluded, never counted as zero. Criteria are shown separately; no official total or weighting is implied.</p><div className="review-table-scroll"><table><caption>Unofficial panel assessment · score out of 5</caption><thead><tr><th>Criterion</th><th>Mean</th><th>Scored reviews</th></tr></thead><tbody>{panel.rubric.criteria.map(criterion=>{const scored=panel.reviews.flatMap(r=>r.rubric_scores.filter(s=>s.criterion===criterion&&typeof s.score==='number').map(s=>s.score as number));return <tr key={criterion}><th>{criterion}</th><td>{scored.length?(scored.reduce((a,b)=>a+b,0)/scored.length).toFixed(1):'Untested'}</td><td>{scored.length} / {panel.reviews.length}</td></tr>})}</tbody></table></div></section>
   {!!panel.release_notes?.length&&<section className="review-retest"><h2>Changes made during the review</h2><ul>{panel.release_notes.map((note,i)=><li key={i}>{note}</li>)}</ul><p>Individual reviews retain their original observations and tested builds. These changes do not imply that every finding below is resolved.</p></section>}
   <section className="review-filters" aria-label="Review filters"><label>Perspective<select aria-label="Perspective" value={role} onChange={e=>setRole(e.target.value)}><option value="all">All reviewers</option><option value="judge">Judging panel</option><option value="end_user">End-user personas</option></select></label><label>Findings<select aria-label="Findings" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">All priorities</option>{['high','medium','low'].map(v=><option key={v}>{v}</option>)}</select></label><label>Search reviews<input aria-label="Search reviews" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Drag, evidence, cost, onboarding…"/></label></section>
   <p role="status">{reviews.length} reviews shown</p>
   <div className="review-list">{reviews.map(r=><article className="review-card" id={r.id} key={r.id}><header><div><p className="kicker">{r.id} · {r.reviewer_type==='judge'?'Judging panel':'End-user persona'}</p><h2>{r.persona}</h2></div>{r.usability_score!==null&&<span className="review-rating"><strong>{r.usability_score}/10</strong>Subjective usability</span>}</header><p className="review-summary">{r.summary}</p>
    <details><summary>Reviewer provenance and tested build</summary><p>{r.disclosure}</p><p>{r.reviewer_agent} · {r.reviewed_at}</p><p className="review-build">{printable(r.build)}</p><p>Rubric: {printable(r.rubric_source)}</p></details>
    {r.retest&&<section className="review-retest"><h3>Release retest</h3><p>{r.retest.summary}</p><ul>{r.retest.observations.map((s,i)=><li key={i}>{s}</li>)}</ul><small className="review-build">{printable(r.retest.build)}</small></section>}
    <div className="review-columns"><section><h3>What works</h3><ul>{r.strengths.map((s,i)=><li key={i}>{s}</li>)}</ul></section><section><h3>What to improve next</h3><ol>{r.priority_improvements.map((s,i)=><li key={i}>{s}</li>)}</ol></section></div>
    <section><h3>Findings and recommendations</h3>{r.findings.filter(f=>severity==='all'||f.severity===severity).map((f,i)=><div className="review-finding" key={i}><h4><span className={`review-priority review-priority--${f.severity}`}>{f.severity}</span>{f.title}</h4><p>{f.observation}</p><p><b>User impact:</b> {f.impact}</p><p><b>Recommendation:</b> {f.recommendation}</p>{linkEvidence(r,f.evidence_ids)}</div>)}{!r.findings.some(f=>severity==='all'||f.severity===severity)&&<p>No findings at this priority.</p>}</section>
    <details><summary>Seven rubric criteria · scores and rationale</summary>{r.rubric_scores.map(s=><section className="review-rubric-row" key={s.criterion}><h4>{s.criterion} <span>{s.score===null?'Untested':`${s.score}/5`}</span></h4><p>{s.rationale}</p>{linkEvidence(r,s.evidence_ids)}</section>)}</details>
    <details><summary>Mobile and desktop journeys</summary>{r.journeys.map((j,i)=><section key={i}><h4>{j.device} · {printable(j.viewport)} · {j.outcome}</h4><ol>{j.steps.map((s,i)=><li key={i}>{s}</li>)}</ol>{j.observations.map((s,i)=><p key={i}>{s}</p>)}</section>)}</details>
    <details><summary>Evidence gallery · {r.evidence.length} items</summary><div className="review-gallery">{r.evidence.map(e=><figure id={`${r.id}-${e.id}`} key={e.id}>{e.type==='screenshot'&&e.path.startsWith('/review-evidence/')?<a href={e.path} target="_blank" rel="noreferrer"><img src={e.path} alt={e.description} loading="lazy"/></a>:<strong>{e.id} · Browser check</strong>}<figcaption>{e.id}: {e.description}</figcaption></figure>)}</div></details>
    <section className="review-limitations"><h3>Limits of this review</h3><ul>{r.limitations.map((s,i)=><li key={i}>{s}</li>)}</ul></section>
   </article>)}</div>{!reviews.length&&<p>No reviewers match these filters.</p>}
   <footer><p>Reviews describe a synthetic planning demonstration. They do not establish real farm performance or commercial readiness.</p><a href="/api/v1/reviews" download="farmtact-review-panel.json">Download the published review data</a> · <a href="/">Return to the farm</a></footer>
  </>}
 </main>
}
