#!/usr/bin/env python3
"""Generate the web response types from the authoritative Pydantic view models."""
from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from services.api.view_contracts import WEB_MODELS


TARGET = ROOT / "apps/web/src/lib/types.ts"
HEADER = "// Generated by scripts/generate_web_contracts.py; do not edit by hand.\n\n"


def _literal(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"
    return str(value)


def _type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(value) for value in schema["enum"])
    variants = schema.get("anyOf") or schema.get("oneOf")
    if variants:
        if schema.get("x-typescript-omit-null"):
            variants = [variant for variant in variants if variant.get("type") != "null"]
        rendered = []
        for variant in variants:
            value = _type(variant)
            if value not in rendered:
                rendered.append(value)
        return " | ".join(rendered)
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(_type({"type": item}) for item in kind)
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        item = _type(schema.get("items", {}))
        return f"Array<{item}>" if " | " in item else f"{item}[]"
    if kind == "object" or "properties" in schema or "additionalProperties" in schema:
        properties = schema.get("properties", {})
        if properties:
            required = set(schema.get("required", []))
            fields = [
                f"{name}{'' if name in required else '?'}: {_type(value)}"
                for name, value in properties.items()
            ]
            if schema.get("additionalProperties") is True:
                fields.append("[key: string]: unknown")
            return "{ " + "; ".join(fields) + " }"
        extra = schema.get("additionalProperties")
        return f"Record<string, {_type(extra)}>" if isinstance(extra, dict) else "Record<string, unknown>"
    return "unknown"


def _definition(name: str, schema: dict[str, Any]) -> str:
    if schema.get("type") == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        lines = [f"export interface {name} {{"]
        for field, value in schema.get("properties", {}).items():
            optional = "" if field in required else "?"
            lines.append(f"  {field}{optional}: {_type(value)}")
        if schema.get("additionalProperties") is True:
            lines.append("  [key: string]: unknown")
        lines.append("}")
        return "\n".join(lines)
    return f"export type {name} = {_type(schema)}"


def render_typescript() -> str:
    # Each schema is rendered from its own authoritative model so output order is
    # explicit and changes do not depend on Pydantic's internal $defs ordering.
    blocks = [HEADER.rstrip()]
    emitted_aliases: set[str] = set()
    for model in WEB_MODELS:
        schema = model.model_json_schema()
        for alias, definition in schema.get("$defs", {}).items():
            if alias not in {item.__name__ for item in WEB_MODELS} and alias not in emitted_aliases:
                blocks.append(_definition(alias, definition))
                emitted_aliases.add(alias)
        blocks.append(_definition(model.__name__, schema))
    blocks.append("export type AppView = 'board' | 'crops' | 'data' | 'outcomes' | 'setup'")
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = parser.parse_args()
    rendered = render_typescript()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != rendered:
            print(f"{TARGET.relative_to(ROOT)} is stale; run {Path(__file__).name}")
            return 1
        return 0
    TARGET.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
