// Generated by scripts/generate_web_contracts.py; do not edit by hand.

export type BedStage = 'empty' | 'nursery' | 'growing' | 'ready'

export interface Bed {
  id: string
  name: string
  area_m2: number
  system: string
  crop_id?: string
  batch_id?: string
  transplant_date?: string
  stage: BedStage
  sow_date?: string
  harvest_date?: string
  progress: number
  [key: string]: unknown
}

export interface FarmResources {
  area_m2: number
  nursery_sites: number
  labour_hours_per_week: number
  cash_sgd: number
  [key: string]: unknown
}

export interface FarmOrder {
  id: string
  crop_id: string
  due_date: string
  quantity_kg: number
  price_sgd_per_kg: number
  [key: string]: unknown
}

export interface Farm {
  id: string
  name: string
  location: string
  timezone: string
  data_mode: string
  cutoff: string
  planning_date?: string
  horizon_days: number
  beds: Bed[]
  resources: FarmResources
  orders: FarmOrder[]
  version: number | string
  [key: string]: unknown
}

export interface CropRecipe {
  cycle_days: number
  nursery_days: number
  yield_kg_per_m2: number
  validation_status: string
  [key: string]: unknown
}

export interface EvidenceRecord {
  evidence_id: string
  title?: string | null
  year?: number | null
  finding?: string | null
  limit?: string | null
  scope?: string | null
  licence_state?: string | null
  access_review_status?: string | null
  source_url?: string | null
  [key: string]: unknown
}

export interface Crop {
  id: string
  label: string
  aliases: string[]
  color?: string
  harvested_part: string
  evidence_ids: string[]
  warnings: string[]
  recipe: CropRecipe | null
  evidence?: EvidenceRecord[] | null
  popularity_rank?: number | null
  taxonomy_status?: string | null
  [key: string]: unknown
}

export type SourceOrigin = 'public' | 'synthetic'

export interface Source {
  id: string
  name: string
  status: string
  observed_at: string | null
  retrieved_at: string
  available_at?: string | null
  freshness: string
  origin: SourceOrigin
  execution_mode: string
  summary: string
  unit?: string | string[] | null
  value?: string | number | null
  url?: string | null
  snapshot_id?: string | null
  coverage?: Record<string, unknown> | null
  licence_state?: string | null
  availability_status?: string | null
  [key: string]: unknown
}

export interface DeepSeekCapability {
  status: string
  models: string[]
  reason?: string | null
  overall_trial_status?: string | null
  [key: string]: unknown
}

export interface VisionCapability {
  status: string
  [key: string]: unknown
}

export interface Capabilities {
  deepseek: DeepSeekCapability
  vision: VisionCapability
  data_mode: string
  execution_mode: string
  [key: string]: unknown
}

export interface StrategyMetrics {
  fill_rate: number
  margin_sgd: number
  waste_kg: number
  harvest_kg: number
  shortfall_kg: number
  cost_sgd: number
  labour_hours: number
  area_m2: number
  closing_stock_kg?: number | null
  opening_stock_kg?: number | null
  revenue_sgd?: number | null
  [key: string]: unknown
}

export interface Allocation {
  bed_id: string
  crop_id: string
  sow_date: string
  transplant_date: string
  harvest_date: string
  area_m2: number
  expected_kg: number
  id?: string
  recipe_id?: string
  executed?: boolean
  [key: string]: unknown
}

export interface WeeklyResult {
  week: number
  date: string
  demand_kg: number
  harvest_kg: number
  delivered_kg: number
  shortfall_kg: number
  [key: string]: unknown
}

export interface ConstraintViolation {
  constraint_code?: string | null
  entity_id?: string | null
  period?: string | null
  required?: number | null
  available?: number | null
  unit?: string | null
  severity?: string | null
  repair_options?: string[] | null
  [key: string]: unknown
}

export type StrategyName = 'Lean' | 'Balanced' | 'Resilient'

export interface Strategy {
  id: string
  name: StrategyName
  status: string
  description: string
  metrics: StrategyMetrics
  allocations: Allocation[]
  weekly: WeeklyResult[]
  violations: Array<string | ConstraintViolation>
  assumptions: string[]
  policy_parameters?: Record<string, unknown> | null
  cost_breakdown?: Record<string, unknown> | null
  ledger?: Record<string, unknown>[] | null
  scenario_results?: Record<string, unknown>[] | null
  scenario_set_id?: string | null
  scenario_seed?: number | null
  solver?: Record<string, unknown> | null
  input_hash?: string | null
  model_version?: string | null
  calculation_version?: string | null
  risk?: Record<string, unknown> | null
  [key: string]: unknown
}

export interface Claim {
  role: string
  claim_type: string
  statement: string
  evidence_ids: string[]
  tool_result_refs: string[]
  status: string
  recommendation?: string | null
  run_id?: string | null
  snapshot_id?: string | null
  rejection_reasons?: string[] | null
  [key: string]: unknown
}

export interface RunEvent {
  sequence: number
  event_type: string
  occurred_at: string
  body: unknown
  run_id?: string | null
  schema_version?: string | null
  [key: string]: unknown
}

export interface Run {
  id: string
  status: string
  input_version: number | string
  created_at: string
  execution_mode: string
  data_mode: string
  council_status: string
  strategies: Strategy[]
  claims: Claim[]
  events: RunEvent[]
  warnings: string[]
  accepted_strategy_id?: string
  parent_run_id?: string | null
  disruption?: string | Record<string, unknown> | null
  shared_demo?: boolean
  superseded_by?: string
  input_hash?: string | null
  source_snapshot?: Source[] | null
  evidence_version?: string | null
  development_phase?: string | null
  decision_policy?: string | null
  council_requested?: boolean | null
  with_vision?: boolean | null
  completed_at?: string | null
  original_execution_mode?: string | null
  inference_origin?: string | null
  replay_of?: string | null
  acceptance_stale?: boolean | null
  forecast?: Record<string, unknown> | null
  scenario_set?: Record<string, unknown>[] | null
  scenario_set_id?: string | null
  visual_observation?: Record<string, unknown> | null
  inference_budget?: Record<string, unknown> | null
  inference_audit?: Record<string, unknown>[] | null
  acceptance?: Record<string, unknown> | null
  simulated_outcome?: Record<string, unknown> | null
  [key: string]: unknown
}

export interface Bootstrap {
  farm: Farm
  crops: Crop[]
  sources: Source[]
  capabilities: Capabilities
  latest_run: Run | null
  [key: string]: unknown
}

export type AppView = 'world' | 'board' | 'crops' | 'data' | 'outcomes' | 'setup'
